window.courseUnits = [
{
 id:'00', title:'Linear Algebra Review · 控制课需要的线性代数', question:'rank、eigenvalue、left/right eigenvector、similarity transform 到底为什么会反复出现在控制理论里？',
 goals:['会用 kernel / image / rank 判断线性方程与可控、可观子空间。','能计算并解释左右特征向量、谱与代数/几何重数。','理解 similarity transformation 与 diagonalization 只是换坐标，不改变系统本质。','掌握 Cayley–Hamilton、quadratic form 与 positive definite，为 Lyapunov/LQR 做准备。'],
 source:'HS2023 R00_algebra.pdf（Exercise 0 / Linear Algebra Review）',
 sections:[
  {title:'Vector spaces, image, kernel 与 rank',html:String.raw`<p>把矩阵 $A\in\mathbb R^{p\times n}$ 看成一个线性映射 $x\mapsto Ax$，控制里很多概念马上变得直观。<strong>image</strong> 是所有能被映射到的方向，<strong>kernel</strong> 是被映射成 0 的方向：</p><p class="cs-equation">$$\operatorname{Im}(A)=\{Ax:x\in\mathbb R^n\},\qquad \ker(A)=\{x:Ax=0\}.$$</p><p>rank 就是 image 的维数。rank-nullity 给出 $\dim\ker A+\operatorname{rank}A=n$。以后 $W_c$ 的 image 会变成“可到达状态子空间”，$W_o$ 的 kernel 会变成“不可观状态子空间”。所以这不是复习题，而是状态空间理论的语言。</p><div class="cs-example"><span class="cs-label">Mini example</span><strong>为什么 rank deficiency 表示少了一个方向？</strong><p>若 $A=\begin{bmatrix}1&2\\2&4\end{bmatrix}$，第二列是第一列的两倍，image 只有一维。存在非零 $x=[-2,1]^T$ 使 $Ax=0$；这个方向对输出完全“不可见”。</p></div>`},
  {title:'Ax=b：存在解、唯一解与 least squares',html:String.raw`<p>$Ax=b$ 有解当且仅当 $b\in\operatorname{Im}(A)$，等价于 $\operatorname{rank}(A)=\operatorname{rank}([A\ b])$。如果 $A$ 还有 full column rank，解才唯一。</p><p>控制里经常遇到非方阵：例如多输入系统的 controllability matrix 是“宽矩阵”。这时我们并不追求普通逆，而会用 Moore–Penrose pseudo-inverse 找最小范数解：</p><p class="cs-equation">$$x^*=A^Tb, \text{并不一般成立；若 }A\text{ full row rank, }x^*=A^T(AA^T)^{-1}b.$$</p><p>后面 minimum-energy control 的公式正是同一个几何思想：满足约束的所有输入中，选择与 nullspace 正交的那一个。</p>`},
  {title:'Eigenvalues 与 right / left eigenvectors',html:String.raw`<p>右特征向量满足 $Av=\lambda v$；左特征向量满足 $w^TA=\lambda w^T$，也就是 $A^Tw=\lambda w$。特征值来自 characteristic polynomial：</p><p class="cs-equation">$$\det(\lambda I-A)=0.$$</p><p>在状态方程 $\dot x=Ax$ 中，右特征向量给出“状态沿哪个方向运动”，而左特征向量告诉我们初始状态在某个 mode 上投影了多少。若左右特征向量归一化使 $w_i^Tv_j=\delta_{ij}$，那么 modal expansion 是</p><p class="cs-equation">$$x(t)=\sum_i e^{\lambda_i t}v_i\,w_i^Tx_0.$$</p><div class="cs-checkpoint"><strong>理解检查</strong><p>为什么只知道 eigenvalues 还不一定知道 transient 会不会很大？因为非正交 eigenvectors 可以产生强烈的 mode interaction / transient amplification；这会在 L13 成为 pole placement 的局限。</p></div>`},
  {title:'Diagonalization 与 similarity transformation',html:String.raw`<p>如果有 $n$ 个线性无关右特征向量，令 $V=[v_1\cdots v_n]$，则</p><p class="cs-equation">$$A=V\Lambda V^{-1},\qquad \Lambda=\operatorname{diag}(\lambda_1,\ldots,\lambda_n).$$</p><p>坐标变换 $x=Vz$ 把 $\dot x=Ax$ 变成 $\dot z=\Lambda z$。每个坐标独立演化，于是原本耦合的系统被分解成 modes。</p><p>重要的是：similarity transform 不改变 eigenvalues、transfer behavior、controllability/observability 这些“物理性质”。它只改变你描述状态的坐标。CCF、observable canonical form、modal form 都是利用这一点选择最方便的坐标。</p>`},
  {title:'Quadratic forms 与 positive definite',html:String.raw`<p>Lyapunov 与 LQR 会不断出现 $x^TPx$。若对所有 $x\neq0$ 都有 $x^TPx>0$，则 $P\succ0$；若只保证 $\ge0$，则 $P\succeq0$。当 $P=P^T$ 时，可以通过 eigenvalues 判断：</p><p class="cs-equation">$$P\succ0\iff \lambda_i(P)>0\ \forall i.$$</p><p>几何上 $x^TPx=c$ 是椭球。$P$ 的大 eigenvalue 表示对应方向代价高、椭球半径短。以后 LQR 的 $Q$ 就是在告诉 controller：“哪些状态方向偏离最贵？”</p><div class="cs-example"><span class="cs-label">LQR preview</span><p>$Q=\operatorname{diag}(100,1)$ 表示 $x_1$ 的平方误差比 $x_2$ 贵 100 倍；优化器通常会更积极地压低 $x_1$。</p></div>`},
  {title:'Cayley–Hamilton：为什么只需要到 A^(n−1)',html:String.raw`<p>若 characteristic polynomial 为</p><p class="cs-equation">$$p(\lambda)=\lambda^n+a_{n-1}\lambda^{n-1}+\cdots+a_0,$$</p><p>Cayley–Hamilton 告诉我们矩阵本身满足 $p(A)=0$。因此 $A^n,A^{n+1},\ldots$ 都能写成 $I,A,\ldots,A^{n-1}$ 的线性组合。</p><p>这解释了三个之后会反复出现的事实：controllability matrix 只需要 $[B,AB,\ldots,A^{n-1}B]$；observability matrix 只需要到 $CA^{n-1}$；matrix exponential $e^{At}$ 也能化成有限个矩阵幂的组合。</p>`}
 ],
 practice:String.raw`<ol><li>对 $A=\begin{bmatrix}1&2\\2&4\end{bmatrix}$ 求 rank、kernel 与 image。</li><li>对 $A=\begin{bmatrix}0&1\\-2&-3\end{bmatrix}$ 求 eigenvalues 与一组右特征向量。</li><li>证明 similarity transform $\tilde A=TAT^{-1}$ 与 $A$ 有相同 characteristic polynomial。</li><li>判断 $P=\begin{bmatrix}2&1\\1&2\end{bmatrix}$ 是否 positive definite。</li></ol><details><summary>答案提示</summary><p>第 1 题 rank=1，kernel 由 $[-2,1]^T$ 张成。第 4 题 eigenvalues 为 1 与 3，因此 $P\succ0$。</p></details>`
},
{
 id:'01', title:'Introduction · Why Feedback?', question:'为什么“模型算准一点再开环控制”通常不够，而 feedback 却能让不确定的现实世界变得可控？',
 goals:['认清 plant、actuator、sensor、reference、disturbance、controller。','用公式比较 feedforward 与 feedback 对模型误差和扰动的敏感度。','理解 2-DOF：feedforward 做 nominal performance，feedback 做 robustness。','理解整门课的 design pipeline：model → analyze → design → implement。'],
 source:'HS2023 L01_Introduction.pdf + B01 Introduction + Lecture 1',
 sections:[
  {title:'控制系统的基本元素',html:String.raw`<p>ETH 第一讲把 plant 定义成“物理过程 + actuator + sensor”。controller 不直接改变世界，它通过 actuator 施加输入 $u(t)$；sensor 把真实状态压缩成测量 $y(t)$。</p><p>若 $u,y$ 都是标量，就是 SISO；若它们是向量，就是 MIMO。reference $r(t)$ 是你希望输出做到什么，disturbance $w(t)$ 是你无法直接命令却会影响系统的外部作用。</p><div class="cs-callout"><strong>读 block diagram 的固定顺序</strong><p>先找 signal flow，再写每个 block 的输入输出方程，最后消元。不要靠“看图猜 transfer function”。</p></div>`},
  {title:'Feedforward：nominally perfect',html:String.raw`<p>开环控制器只根据 reference 和模型算出 $u_{ff}$。若 plant 是静态增益 $G_0$，最自然的选择是 $u_{ff}=G_0^{-1}r$。在模型完全准确、没有扰动时，$y=r$。</p><p>问题是现实 plant 常写成 $G=G_0+\Delta G$，而且有 disturbance。于是逆模型不能同时消除未知 $\Delta G$ 与未知扰动。更糟糕的是：若 plant 不可逆、含 RHP zero、delay 或本身 unstable，精确 inverse 可能根本无法稳定因果实现。</p>`},
  {title:'Feedback：根据现实修正模型',html:String.raw`<p>负反馈先形成 $e=r-y$，再用 $u=Ke$。对静态 plant $y=G(u+w)$，闭环为</p><p class="cs-equation">$$y=\frac{GK}{1+GK}r+\frac{G}{1+GK}w.$$</p><p>当 $|GK|\gg1$ 时，reference 通道趋近 1，而 disturbance 通道约为 $1/K$。这就是反馈的核心：它不要求你“知道所有扰动”，而是用测量看到扰动造成的结果，再纠正它。</p>`},
  {title:'Cruise control 数字例子',html:String.raw`<p>HS2023 第一讲把汽车的静态增益写成 $10+\Delta$，nominal feedforward 用 $u=r/10$。因此</p><p class="cs-equation">$$y_{ol}=\left(1+\frac{\Delta}{10}\right)r+(10+\Delta)w.$$</p><p>只要 $\Delta=1$，即使平路 $w=0$，reference error 也约 10%。若加入 gain $K=100$ 的 feedback，reference 系数变为</p><p class="cs-equation">$$\frac{100(10+\Delta)}{1+100(10+\Delta)},$$</p><p>而 disturbance 系数变为 $(10+\Delta)/(1+100(10+\Delta))$。nominal plant 下 reference 误差约从量级 $10^{-1}$ 降到 $10^{-3}$。</p><div class="cs-checkpoint"><strong>不要误解 high gain</strong><p>高 gain 不是免费午餐。后面会看到噪声、delay、RHP zeros、actuator limits 都会限制 gain 与 bandwidth。</p></div>`},
  {title:'2-DOF：把“跟踪”和“抗扰”分工',html:String.raw`<p>实际系统常用</p><p class="cs-equation">$$u=u_{ff}+u_{fb}.$$</p><p>feedforward 根据 reference 与模型产生主要动作；feedback 只纠正 residual error。这样可以既保留 nominal model 的快速跟踪，又不把所有鲁棒性任务压在一个 feedback loop 上。</p><p>L08 会系统讨论 2-DOF、disturbance decoupling、cascade、Smith predictor 与 anti-windup。</p>`},
  {title:'从连续物理到数字 controller',html:String.raw`<p>真实 plant 通常是 continuous-time，但现代 controller 基本运行在计算机上：sensor → A/D → sampled measurement → algorithm → D/A/command → actuator。采样太慢会 alias，controller discretization 也会改变稳定性与相位。</p><p>所以本课程不是“只学连续系统”。L12 会专门把 continuous plant 与 discrete controller 接起来。</p>`},
  {title:'整门课的设计 pipeline',html:String.raw`<p>后面 13 讲都可以放进同一个流程：</p><ol><li><strong>Model：</strong>ODE / state space / transfer function。</li><li><strong>Analyze：</strong>modes、stability、frequency response、controllability/observability。</li><li><strong>Specify：</strong>settling、overshoot、tracking、disturbance、noise、robustness。</li><li><strong>Design：</strong>PID / loop shaping / state feedback / LQR。</li><li><strong>Estimate：</strong>observer / Kalman filter。</li><li><strong>Implement：</strong>sampling、digital controller、saturation。</li></ol>`}
 ],
 practice:String.raw`<ol><li>画出 cruise control 的 feedforward 与 feedback block diagram，并分别写出 $r,w\to y$ 的传递关系。</li><li>解释为什么一个准确的 feedforward controller 仍无法处理未知坡度。</li><li>给出一个必须用 2-DOF 而不是纯 feedback 更自然的例子。</li></ol><details><summary>答案提示</summary><p>核心是：feedforward 不使用当前输出；feedback 利用 $y$ 形成误差，因此能感知“模型没预见到但已经发生”的偏差。</p></details>`
},
{
 id:'02', title:'Representations of Dynamical Systems', question:'同一个系统为什么要在 ODE、state space、transfer function 之间来回切换？',
 goals:['从高阶 ODE 构造 state-space model。','从 state space 推导 transfer function，并理解零初值假设。','找到 nonlinear equilibrium 并做 Jacobian linearization。','理解坐标变换不改变输入输出行为。'],
 source:'HS2023 L02_Representations.pdf + B02 Representations + R01_representations + Exercise 1',
 sections:[
  {title:'General state-space 与 equilibrium',html:String.raw`<p>一般连续系统写成</p><p class="cs-equation">$$\dot x=f(t,x,u),\qquad y=h(t,x,u).$$</p><p>离散时间写成 $x^+=f(t,x,u)$。LTI 特例是 $\dot x=Ax+Bu,\ y=Cx+Du$。维度必须匹配：$A\in\mathbb R^{n\times n}, B\in\mathbb R^{n\times p}, C\in\mathbb R^{q\times n}, D\in\mathbb R^{q\times p}$。</p><p>非线性系统的 equilibrium $(x^*,u^*)$ 满足连续时间 $f(x^*,u^*)=0$；离散时间则满足 $f(x^*,u^*)=x^*$。</p>`},
  {title:'Higher-order ODE → state space',html:String.raw`<p>课程的 running example 是</p><p class="cs-equation">$$y^{(3)}+3\ddot y-2\dot y+y=u.$$</p><p>选自然状态 $x_1=y,x_2=\dot y,x_3=\ddot y$，得到</p><p class="cs-equation">$$\dot x=\begin{bmatrix}0&1&0\\0&0&1\\-1&2&-3\end{bmatrix}x+\begin{bmatrix}0\\0\\1\end{bmatrix}u,\qquad y=[1\ 0\ 0]x.$$</p><p>这里 state 的作用是把高阶 ODE 拆成一阶 vector ODE。state choice 不唯一；只要变换可逆，不同坐标描述的是同一个 internal dynamics。</p>`},
  {title:'Laplace transform → transfer function',html:String.raw`<p>零初值时 $\mathcal L\{y^{(k)}\}=s^kY(s)$。因此上面的 ODE 变成</p><p class="cs-equation">$$(s^3+3s^2-2s+1)Y(s)=U(s),$$</p><p>于是 $G(s)=Y/U=1/(s^3+3s^2-2s+1)$。</p><p><strong>零初值为什么重要？</strong>Transfer function 描述“输入如何映射到输出”，而 initial condition 是另一条独立激励通道。若 $x(0)=x_0\neq0$，输出中还会多出 $C(sI-A)^{-1}x_0$。</p>`},
  {title:'State space → transfer function',html:String.raw`<p>对 $\dot x=Ax+Bu$，零初值：</p><p class="cs-equation">$$sX=AX+BU\Rightarrow X=(sI-A)^{-1}BU.$$</p><p>代入 $Y=CX+DU$：</p><p class="cs-equation">$$G(s)=C(sI-A)^{-1}B+D.$$</p><p>这是整门课最常用的转换公式之一。它也揭示一个重要现象：$\det(sI-A)$ 中的某些内部 poles 可能与 numerator cancellation，从 transfer function 中“消失”。L04 会看到这导致 BIBO stable 但 internally unstable。</p>`},
  {title:'输入含导数时怎样构造 state space',html:String.raw`<p>若 ODE 右侧有 $\dot u$，直接把 $[y,\dot y,\ddot y]$ 当 state 可能产生 input derivative。课程用一个 dummy variable 先构造 strictly proper dynamics。</p><p>例如</p><p class="cs-equation">$$y^{(3)}+3\ddot y-2\dot y+y=\dot u-2u$$</p><p>在 Laplace 域写 $Y=(s-2)V$、$(s^3+3s^2-2s+1)V=U$，再以 $v,\dot v,\ddot v$ 为 state。这样 $C=[-2,1,0]$，避免把 $\dot u$ 作为状态方程输入。</p><div class="cs-callout"><strong>工程含义</strong><p>state-space realization 必须可实现。一个看似简单的 transfer function 可能需要你重新选择内部变量，才能得到 causal model。</p></div>`},
  {title:'Nonlinear linearization',html:String.raw`<p>令 $x=x^*+\delta x,u=u^*+\delta u$，在 equilibrium 处做一阶 Taylor：</p><p class="cs-equation">$$\delta\dot x=A\delta x+B\delta u,\quad \delta y=C\delta x+D\delta u,$$</p><p class="cs-equation">$$A=\left.\frac{\partial f}{\partial x}\right|_*,\ B=\left.\frac{\partial f}{\partial u}\right|_*,\ C=\left.\frac{\partial h}{\partial x}\right|_*,\ D=\left.\frac{\partial h}{\partial u}\right|_*.$$</p><p>注意 controller 实际施加的是 $u=u^*+\delta u$。$u^*$ 是维持工作点的 feedforward，$\delta u$ 是线性 controller 产生的 feedback correction。</p>`},
  {title:'Coordinate transforms 与 Python workflow',html:String.raw`<p>若 $z=Tx$，则</p><p class="cs-equation">$$\dot z=TAT^{-1}z+TBu,\qquad y=CT^{-1}z+Du.$$</p><p>输入输出 transfer function 不变。以后我们会故意挑选 $T$，把系统变成 modal / controllable / observable canonical form。</p><pre class="cs-code"><code>import control as ct
sys_ss = ct.ss(A,B,C,D)
sys_tf = ct.ss2tf(sys_ss)
sys2   = ct.tf2ss(sys_tf)</code></pre><p>数值软件适合验证，不代替推导。考试和设计时最重要的是知道每个转换为什么成立、哪些假设被用了。</p>`}
 ],
 practice:String.raw`<ol><li>把 $y^{(3)}+3\ddot y-2\dot y+y=u$ 写成 state space，并验证 $C(sI-A)^{-1}B$。</li><li>对 $\dot x=x-x^3+u$ 找 $u^*=0$ 下所有 equilibria 并线性化。</li><li>证明 $z=Tx$ 前后 transfer function 不变。</li></ol><details><summary>答案提示</summary><p>第 2 题 $x^*=0,\pm1$；线性化 $A=1-3(x^*)^2$。</p></details>`
},
{
 id:'03', title:'Solutions to LTI Systems & Internal Stability', question:'给定 A、B 与初值，状态究竟怎样随时间演化？什么才叫“内部稳定”？',
 goals:['理解 matrix exponential 与 modal expansion。','能处理 diagonalizable 与 Jordan block 两种情况。','掌握 CT/DT spectral stability criteria。','理解 Lyapunov equation / function 作为不依赖显式解的稳定性工具。'],
 source:'HS2023 L03_Solutions_to_LTI_Systems.pdf + B03 + R02_LTI + Exercise 2',
 sections:[
  {title:'Matrix exponential 是状态转移算子',html:String.raw`<p>齐次系统 $\dot x=Ax$ 的唯一解是</p><p class="cs-equation">$$x(t)=e^{A(t-t_0)}x(t_0),\qquad e^{At}=I+At+\frac{A^2t^2}{2!}+\cdots.$$</p><p>$e^{At}$ 对矩阵所做的事，与标量 $e^{at}$ 完全类似：把初始状态从 $t_0$ 推到 $t$。它满足 $e^{A0}=I$、$e^{A(t+s)}=e^{At}e^{As}$、$\frac d{dt}e^{At}=Ae^{At}$。</p>`},
  {title:'Modal decomposition：每个 eigenvalue 是一个 mode',html:String.raw`<p>若 $A=V\Lambda W$ 且 $W=V^{-1}$，令 $z=Wx$，系统变成 $\dot z_i=\lambda_i z_i$。所以</p><p class="cs-equation">$$x(t)=\sum_{i=1}^n (w_i^Tx_0)e^{\lambda_i t}v_i.$$</p><p>三个因素各司其职：$w_i^Tx_0$ 决定初值激发第 $i$ 个 mode 的程度；$e^{\lambda_i t}$ 决定增长/衰减/振荡；$v_i$ 决定这个 mode 在 state space 中的方向。</p><div class="cs-example"><span class="cs-label">Phase portrait intuition</span><p>一个 eigenvalue $-1$、另一个 $+1$ 的二维系统，会沿一个 eigenspace 收敛、沿另一个 eigenspace 发散，因此原点是 saddle，不可能稳定。</p></div>`},
  {title:'Jordan blocks：重复 eigenvalue 也可能不稳定',html:String.raw`<p>不可对角化时，Jordan block</p><p class="cs-equation">$$J=\lambda I+N,\qquad e^{Jt}=e^{\lambda t}\left(I+tN+\frac{t^2N^2}{2!}+\cdots\right).$$</p><p>所以除了 $e^{\lambda t}$ 还会出现 $t e^{\lambda t},t^2e^{\lambda t}$。当 $\Re\lambda<0$ 时，多项式仍被 exponential 压住；但当 $\Re\lambda=0$ 时，非平凡 Jordan block 会产生无界多项式增长。</p>`},
  {title:'Forced LTI solution / variation of constants',html:String.raw`<p>加入输入后：</p><p class="cs-equation">$$x(t)=e^{A(t-t_0)}x(t_0)+\int_{t_0}^t e^{A(t-\tau)}Bu(\tau)d\tau.$$</p><p>第一项是 zero-input / free response，第二项是 zero-state / forced response。输出为</p><p class="cs-equation">$$y(t)=Ce^{A(t-t_0)}x_0+\int_{t_0}^tCe^{A(t-\tau)}Bu(\tau)d\tau+Du(t).$$</p><p>L04 会把第二项重新解释成 convolution，并引出 impulse response 与 transfer function。</p>`},
  {title:'Continuous-time internal stability',html:String.raw`<p>对 LTI $\dot x=Ax$：</p><ul><li>asymptotically stable $\iff \Re\lambda_i(A)<0$；</li><li>stable $\iff \Re\lambda_i\le0$ 且虚轴 eigenvalues 的 Jordan blocks 都是 $1\times1$；</li><li>否则 unstable。</li></ul><p>所有 eigenvalues 严格在左半平面的矩阵称 Hurwitz。</p><div class="cs-checkpoint"><strong>关键词：internal</strong><p>这里讨论的是所有内部 states 是否收敛，而不是只看输入输出。后面 pole-zero cancellation 会把两者区分开。</p></div>`},
  {title:'Discrete-time stability 与 s→z mapping',html:String.raw`<p>离散系统 $x_{k+1}=Ax_k$ 的解是 $x_k=A^kx_0$。asymptotic stability 要求</p><p class="cs-equation">$$|\lambda_i(A)|<1.$$</p><p>sample-hold discretization 给 $A_d=e^{AT}$，因此连续 pole $s=\alpha+j\beta$ 映射为</p><p class="cs-equation">$$z=e^{sT}=e^{\alpha T}e^{j\beta T}.$$</p><p>$\alpha<0\iff |z|<1$，所以 exact ZOH discretization 保持 internal stability。</p>`},
  {title:'Lyapunov equation：不用显式求轨迹也能证明稳定',html:String.raw`<p>若存在 $P\succ0$ 使</p><p class="cs-equation">$$A^TP+PA=-Q,\qquad Q\succ0,$$</p><p>取 $V=x^TPx$，则 $\dot V=-x^TQx<0$，故原点 asymptotically stable。反过来，对 Hurwitz $A$ 与任意 $Q\succ0$，该方程有唯一 $P\succ0$。</p><p>离散时间对应</p><p class="cs-equation">$$A^TPA-P=-Q.$$</p><p>这套思想会在 LQR 中以 Riccati equation 的形式再次出现。</p>`},
  {title:'Nonlinear Lyapunov 与 LaSalle',html:String.raw`<p>对 $\dot x=f(x)$，若找到 $V(x)>0$ 且 $\dot V=\nabla V^Tf(x)<0$，就能证明 asymptotic stability，而不必解 ODE。</p><p>若只有 $\dot V\le0$，LaSalle 看集合 $\{x:\dot V=0\}$ 中最大的 invariant set。若唯一能永远留在其中的轨迹是 $x=0$，仍可推出 asymptotic stability。</p><p>物理系统中总能量经常是好 Lyapunov candidate；但一般 nonlinear system 没有自动寻找 $V$ 的通用简单方法。</p>`}
 ],
 practice:String.raw`<ol><li>用 diagonalization 计算 $A=\begin{bmatrix}-1&0\\0&-2\end{bmatrix}$ 的 $e^{At}$。</li><li>说明 eigenvalue $0$ 配 $2\times2$ Jordan block 为什么 unstable。</li><li>连续 pole $-2\pm3j$ 在 $T=0.1$ s 下映射到哪里？模长是多少？</li><li>找一个 $P\succ0$ 验证 $\dot x=-x$ 稳定。</li></ol>`
},
{
 id:'04', title:'Responses to LTI Systems & BIBO Stability', question:'为什么 impulse、step、sinusoid 三种实验就能揭示一个 LTI 系统几乎全部的输入输出行为？',
 goals:['从 state-space solution 推出 convolution。','理解 impulse response、transfer function、step response、DC gain。','理解 poles/zeros/properness 与 Bode plot。','区分 internal stability 与 BIBO stability。'],
 source:'HS2023 L04_Responses to LTI Systems.pdf + B04 + R03_IO_maps + Exercise 3',
 sections:[
  {title:'Convolution：LTI 的输入输出总公式',html:String.raw`<p>零初值时</p><p class="cs-equation">$$y(t)=\int_0^t Ce^{A(t-\tau)}Bu(\tau)d\tau+Du(t).$$</p><p>定义 impulse response $g(t)=Ce^{At}B+D\delta(t)$，则</p><p class="cs-equation">$$y(t)=(g*u)(t)=\int_0^t g(t-\tau)u(\tau)d\tau.$$</p><p>直觉：把任意输入看成无穷多个缩放、平移的小 impulses，输出就是每个 impulse response 的线性叠加。</p>`},
  {title:'Impulse response 与 transfer function',html:String.raw`<p>单位 impulse 输入 $u=\delta(t)$ 直接“挑出” $g(t)$。其 Laplace transform 就是</p><p class="cs-equation">$$G(s)=\mathcal L\{g(t)\}=C(sI-A)^{-1}B+D.$$</p><p>因此 state-space、impulse response、transfer function 是同一个 LTI input-output map 的三种语言。</p>`},
  {title:'Step response 与 DC gain',html:String.raw`<p>对单位 step $u=1(t)$ 且 $A$ invertible：</p><p class="cs-equation">$$y(t)=CA^{-1}e^{At}B-CA^{-1}B+D.$$</p><p>若系统 asymptotically stable，$e^{At}\to0$，最终值是</p><p class="cs-equation">$$y_\infty=-CA^{-1}B+D=G(0).$$</p><p>这就是 DC gain。final value theorem 也给 $\lim_{t\to\infty}y(t)=\lim_{s\to0}sY(s)$，但前提是最终值确实存在。</p>`},
  {title:'Frequency response：sinusoid 经过 LTI 只改 amplitude/phase',html:String.raw`<p>对稳定 LTI，输入 $e^{j\omega t}$ 的 steady-state 输出为</p><p class="cs-equation">$$y_{ss}(t)=G(j\omega)e^{j\omega t}=|G(j\omega)|e^{j(\omega t+\angle G(j\omega))}.$$</p><p>所以 $|G(j\omega)|$ 是 amplitude ratio，$\angle G(j\omega)$ 是 phase shift。Bode plot 把 magnitude 用 dB $20\log_{10}|G|$ 表示，并把频率轴取 log，乘法就变加法。</p>`},
  {title:'Poles、zeros、properness',html:String.raw`<p>对 rational transfer function</p><p class="cs-equation">$$G(s)=K\frac{\prod_i(s-z_i)}{\prod_i(s-p_i)},$$</p><p>$p_i$ 是 poles，$z_i$ 是 zeros。若 denominator degree $n\ge m$ numerator degree，系统 proper；若 $n>m$ 则 strictly proper。relative degree 是 $n-m$。</p><p>RHP pole 意味着 unstable mode；RHP zero 则是 non-minimum-phase constraint，常表现为 inverse response 与额外 phase lag，限制可实现 bandwidth。</p>`},
  {title:'手画 Bode 的标准积木',html:String.raw`<p>把 $G$ 分解成 gain、integrator、real poles/zeros、complex pairs。幅值斜率和 phase 可以逐项相加：</p><div class="cs-table-wrap"><table class="cs-table"><thead><tr><th>元素</th><th>高频斜率</th><th>phase 趋势</th></tr></thead><tbody><tr><td>$1/s$</td><td>−20 dB/dec</td><td>−90°</td></tr><tr><td>$s$</td><td>+20</td><td>+90°</td></tr><tr><td>LHP pole</td><td>再 −20</td><td>0→−90°</td></tr><tr><td>LHP zero</td><td>再 +20</td><td>0→+90°</td></tr><tr><td>RHP zero</td><td>再 +20</td><td>0→−90°</td></tr></tbody></table></div><p>RHP zero 与 LHP zero magnitude 相同、phase 符号相反，这是后面 robust design 的关键。</p>`},
  {title:'Internal stability vs BIBO stability',html:String.raw`<p>Internal stability 看 $A$ 的全部 eigenvalues；BIBO stability 看 input-output impulse response 是否 absolutely integrable：</p><p class="cs-equation">$$\int_0^\infty |g(t)|dt<\infty.$$</p><p>对 rational SISO，这等价于 transfer function 所有 poles 在 LHP。internal stable 一定 BIBO stable；反过来若没有 unstable pole-zero cancellation 才成立。</p><div class="cs-example"><span class="cs-label">Hidden unstable mode</span><p>一个 state-space realization 可以含 $+1$ 的 unstable internal mode，但若该 mode 完全 uncontrollable 或 unobservable，transfer function 中可能 cancellation，外部看起来 BIBO stable，内部状态却发散。</p></div>`},
  {title:'为什么不要 cancel unstable pole/zero',html:String.raw`<p>用 controller zero 精确 cancel unstable plant pole 看起来能把它从 transfer function 里删掉，但 internal dynamics 并没有凭空消失。模型只要有一点误差，cancellation 就不精确，残留 unstable pole 会重新出现。</p><p>所以控制设计里一个基本原则是：<strong>stable cancellation 尚可谨慎使用；unstable cancellation 不应作为稳定化手段。</strong></p>`}
 ],
 practice:String.raw`<ol><li>由 $\dot x=-2x+u,y=x$ 求 impulse response、transfer function、step final value。</li><li>说明为什么稳定系统的 frequency response 是 $G(j\omega)$。</li><li>构造一个 BIBO stable 但 internally unstable 的 state-space realization。</li><li>手画 $(s+1)/(s(s+10))$ 的渐近 Bode magnitude。</li></ol>`
},
{
 id:'05', title:'The Concept of Feedback & PID', question:'P、I、D 分别在闭环里“改变了什么”，为什么 PID 到今天仍然如此重要？',
 goals:['会写闭环 characteristic equation 并理解 root locus。','掌握 P/I/D 对稳定、瞬态和稳态误差的不同作用。','能从 tracking error dynamics 解释 PID，而不是背调参口诀。','理解 derivative filtering 与实现限制。'],
 source:'HS2023 L05_PID_control.pdf + B05 + R04_PID + Exercise 4',
 sections:[
  {title:'Closed-loop characteristic equation',html:String.raw`<p>单位负反馈下</p><p class="cs-equation">$$T(s)=\frac{G(s)K(s)}{1+G(s)K(s)}.$$</p><p>闭环 poles 来自 $1+GK=0$。若 $GK=kz(s)/p(s)$，characteristic polynomial 是</p><p class="cs-equation">$$p(s)+kz(s)=0.$$</p><p>因此 controller 改变 dynamics 的本质，就是改变这条多项式的 roots。</p>`},
  {title:'Root locus 的几何规则',html:String.raw`<p>Root locus 描述 $k:0\to\infty$ 时闭环 poles 的轨迹。分支从 open-loop poles 出发，终止于 open-loop zeros 或 infinity。</p><ul><li>实轴上，某点右侧若有奇数个 real poles/zeros，该点在 locus 上。</li><li>$n_p-n_z$ 条 infinity asymptotes 的角度为 $\phi_q=\frac{2q+1}{n_p-n_z}180^\circ$。</li><li>centroid 为 $(\sum p_i-\sum z_i)/(n_p-n_z)$。</li></ul><p>一个重要推论：有 RHP zero 时，high gain 往往把某个 closed-loop pole 推向那个 unstable zero；relative degree $\ge3$ 时，也会有 asymptote 进入 RHP。</p>`},
  {title:'P control：先让系统稳定',html:String.raw`<p>课程用汽车位置模型 $\ddot p+\dot p=u$。若 reference dynamics 通过 feedforward 抵消，tracking error $e_p=p-p_{ref}$ 在 P control 下满足</p><p class="cs-equation">$$\ddot e_p+\dot e_p+k_Pe_p=0.$$</p><p>characteristic polynomial $s^2+s+k_P$。$k_P>0$ 可稳定，但 poles 受一条 root locus 限制，不能任意放置。</p><div class="cs-callout"><strong>P 的角色</strong><p>产生与 error 成比例的 restoring action；它通常负责“把系统拉回去”。</p></div>`},
  {title:'D control：改变 damping 与 transient',html:String.raw`<p>加入 derivative feedback：</p><p class="cs-equation">$$u=u_{ff}-k_Pe_p-k_D\dot e_p,$$</p><p>误差 characteristic polynomial 变成 $s^2+(1+k_D)s+k_P$。现在 $k_P,k_D$ 能独立影响 constant 与 first-order coefficient，于是自然频率和 damping 都可设计。</p><p>机械直觉：P 像 spring，D 像 damper。D 并不是“让误差更小”的积分机制，而是抑制快速变化和振荡。</p>`},
  {title:'I control：消除 constant disturbance 的 steady-state error',html:String.raw`<p>若存在未知 constant disturbance $w$，仅 P control 的 steady-state 常满足 $e_{ss}\propto w/k_P$，不为零。定义 integral state</p><p class="cs-equation">$$q(t)=\int_0^t e_p(\tau)d\tau,\qquad \dot q=e_p,$$</p><p>再用 $u=u_{ff}-k_Pe_p-k_Iq$。若 augmented closed loop 稳定，steady state 必须满足 $\dot q=e_p=0$，因此 constant error 被强制消失。</p><div class="cs-checkpoint"><strong>Internal model principle 的影子</strong><p>要无偏跟踪 constant signal，需要在 loop 中包含 constant 的生成模型——integrator $1/s$。</p></div>`},
  {title:'PID 作为 pole-zero shaping',html:String.raw`<p>标准 PID</p><p class="cs-equation">$$K(s)=k\left(1+T_Ds+\frac1{T_Is}\right)$$</p><p>有一个 pole at origin 和两个 controller zeros。换句话说，PID 并不是三个“神秘旋钮”，而是一个低阶 dynamic compensator：integrator 控制 low-frequency gain，zeros 用来改变 root locus / phase，overall gain 决定 crossover 与速度。</p>`},
  {title:'Ideal derivative 为什么不可实现',html:String.raw`<p>理想 differentiator $K_D(s)=kT_Ds$ 是 non-proper，high-frequency gain 无界。measurement noise 恰好通常集中在高频，因此会被严重放大。</p><p>实际使用 filtered derivative：</p><p class="cs-equation">$$K_D(s)=k\frac{1+T_Ds}{1+T_fs},\qquad 0<T_f\ll T_D.$$</p><p>高频 gain 被限制，controller 变 proper / causal。选择 $T_f$ 时要小到不破坏目标频段的 phase lead，但不能小到重新放大 sensor noise。</p>`},
  {title:'从 time-domain intuition 到 frequency-domain design',html:String.raw`<p>到这里，P/I/D 的介绍仍偏“作用机理”。L06–L07 会给更系统的设计规则：用 Nyquist/margins 判断 robustness，再通过 Bode loop shaping 决定 PI zero、lead zero/pole 和 crossover。</p><p>因此 PID 的真正掌握标准不是会背 Ziegler–Nichols，而是能回答：<em>我现在缺的是低频 gain、phase margin，还是 damping？这个 controller element 会在哪个频段改变 loop？</em></p>`}
 ],
 practice:String.raw`<ol><li>对 $G(s)=1/[s(s+1)]$ 加 P control，写闭环 characteristic polynomial 并判断 $k>0$ 时稳定性。</li><li>画出两个 open-loop poles、一个 zero 时的 root-locus 起点与终点。</li><li>解释为什么 integral action 能消除 constant disturbance，却可能造成 windup。</li><li>设计一个 filtered PD，并说明 filter pole 应相对 crossover 放在哪里。</li></ol>`
},
{
 id:'06', title:'Closed-Loop Stability & Robustness Criteria', question:'仅仅“nominally stable”为什么不够？我们怎样从 Nyquist、margins 与 S/T 看见真正的鲁棒闭环？',
 goals:['理解 argument principle 到 Nyquist criterion 的逻辑。','会区分 small-gain、Bode、Nyquist 三种稳定判据的适用范围。','会读 gain margin、phase margin、crossover 与 delay robustness。','掌握 sensitivity S 与 complementary sensitivity T 的全部信号通道。'],
 source:'HS2023 L06_Closed_Loop_Stability_Criteria.pdf + B06 + R05 + Exercise 5',
 sections:[
  {title:'Argument principle 与 Nyquist 的核心逻辑',html:String.raw`<p>闭环 characteristic function 写成 $F(s)=1+L(s)$。我们想知道 RHP 中 $F$ 有多少 zeros，因为这些 zeros 就是 unstable closed-loop poles。</p><p>Argument principle 说：沿包围 RHP 的 contour 映射 $F(D)$，绕原点次数满足 $N=Z-P$。而 $F=1+L$ 相当于把 $L(D)$ 平移 1，因此看 $L(D)$ 绕 $-1$ 的次数即可。</p>`},
  {title:'Nyquist stability criterion',html:String.raw`<p>采用课程的 clockwise convention，可写成</p><p class="cs-equation">$$Z=N+P.$$</p><p>$P$ 是 open-loop RHP poles 数，$N$ 是 Nyquist plot 对 $-1$ 的 clockwise encirclements，$Z$ 是 closed-loop RHP poles 数。闭环稳定要求 $Z=0$。</p><p>如果 open loop stable，$P=0$，于是只需避免净 encirclement $-1$；若 open loop 本身 unstable，反而<strong>必须</strong>恰当地 encircle $-1$ 来补偿 $P$。</p>`},
  {title:'Small-gain 与 Bode criterion 什么时候能用',html:String.raw`<p>若 open loop stable 且 $|L(j\omega)|<1$ 对所有频率成立，Nyquist curve 完全在 unit disk 内，不可能围住 $-1$，所以闭环稳定。这是 small-gain criterion：简单但 conservative。</p><p>Bode criterion 需要更强假设：open-loop stable，而且 magnitude / phase 大致 monotonic。此时只看 phase 到 $-180^\circ$ 时 magnitude 是否低于 1。条件不满足时，回到 Nyquist。</p>`},
  {title:'Gain margin、phase margin 与 delay',html:String.raw`<p>crossover frequency $\omega_c$ 定义为 $|L(j\omega_c)|=1$。phase margin</p><p class="cs-equation">$$PM=180^\circ+\angle L(j\omega_c).$$</p><p>gain margin 则在 phase $=-180^\circ$ 的频率上看还允许放大多少倍才碰到 unit gain。</p><p>delay $e^{-sT}$ 不改 magnitude，只增加 phase lag $-\omega T$，所以 PM 可近似理解为 delay margin 的“相位预算”。crossover 越高，同一时间延迟产生的相位损失越大。</p>`},
  {title:'把所有扰动通道一次推清楚',html:String.raw`<p>标准 loop 定义</p><p class="cs-equation">$$S=\frac1{1+GK},\qquad T=\frac{GK}{1+GK},\qquad S+T=1.$$</p><p>若 input disturbance 为 $d_1$、output disturbance 为 $d_2$、measurement noise 为 $\eta$，可得到</p><p class="cs-equation">$$y=Tr-T\eta+SGd_1+Sd_2.$$</p><p>误差则为 $e=Sr+T\eta-SGd_1-Sd_2$。这四个 transfer channels 是后续 loop shaping 的真正设计对象。</p>`},
  {title:'Fundamental dilemma：S+T=1',html:String.raw`<p>你希望 tracking 与 disturbance rejection 好，就要 low-frequency $|S|\ll1$、$T\approx1$；你希望 measurement noise 不进输出，就要 high-frequency $|T|\ll1$。</p><p>由于 $S+T=1$，不能让两者在同一频率同时很小。幸运的是 reference / load disturbance 往往偏低频，而 sensor noise 往往偏高频，所以 frequency separation 让控制成为可能。</p>`},
  {title:'Bandwidth 与 performance / effort trade-off',html:String.raw`<p>closed-loop bandwidth 常定义为 $|T(j\omega_b)|$ 第一次下降到 $1/\sqrt2$（−3 dB）的频率。通常 $\omega_b\approx\omega_c$。</p><p>更高 bandwidth 意味着更快 tracking / disturbance rejection，但也意味着 controller 必须在更高频率产生动作，更容易受到 unmodeled dynamics、delay、noise 与 actuator limits 影响。</p><div class="cs-callout"><strong>设计不是“把 bandwidth 拉满”</strong><p>合理 bandwidth 应低于模型不可信与 actuator 不够快的频段，同时高于你需要跟踪/抑制的主要 disturbance 频段。</p></div>`},
  {title:'闭环设计检查表',html:String.raw`<ol><li>Nominal stability：Nyquist / characteristic roots。</li><li>Robustness：GM / PM 与 distance to −1。</li><li>Low-frequency tracking：$S(0)$ 是否够小，是否需要 integrator。</li><li>Disturbance rejection：$S,SG$ 在 disturbance band 是否小。</li><li>Noise rejection：$T$ 在 sensor-noise band 是否小。</li><li>Bandwidth / actuator：$KS$ 与实际 actuator capability 是否合理。</li></ol>`}
 ],
 practice:String.raw`<ol><li>open loop 有一个 RHP pole 时，稳定闭环的 Nyquist plot 应怎样绕 $-1$？</li><li>若 $\omega_c=10$ rad/s、PM=45°，估算可容忍的纯 delay 量级。</li><li>从 block diagram 重新推导 $y=Tr-T\eta+SGd_1+Sd_2$。</li><li>解释为什么 $S+T=1$ 并不意味着 feedback 没用。</li></ol>`
},
{
 id:'07', title:'Frequency-Domain Control Design', question:'知道“想要什么样的 S/T”以后，怎样真正把 controller K(s) 设计出来？',
 goals:['把闭环要求翻译成 open-loop shape。','会用 P/PI/lag/PD/lead 逐步塑造 Bode。','理解 crossover、phase lead 与 low-frequency gain 的分工。','掌握 inversion-based design 与 IMC 的基本逻辑及限制。'],
 source:'HS2023 L07_Frequency-Domain_Control_Design.pdf + B07 + sum6 + Exercise 6',
 sections:[
  {title:'为什么改 shape 的是 L=GK',html:String.raw`<p>$S=1/(1+GK)$、$T=GK/(1+GK)$ 对 $K$ 是非线性的，直接“指定 S”不方便。open loop $L=GK$ 却能直接通过乘 controller 改 shape，所以工程设计通常围绕 $L$ 展开。</p><p>目标是：low frequency $|L|\gg1$；high frequency $|L|\ll1$；crossover 附近有足够 phase margin；并让 Nyquist 保持安全。</p>`},
  {title:'一张理想 open-loop Bode 应满足什么',html:String.raw`<ol><li>稳定：Nyquist/Bode 条件满足。</li><li>robust：有足够 GM/PM。</li><li>steady-state：$|L(0)|$ 大，step tracking 常希望有 integrator。</li><li>performance：$\omega_c$ 足够高。</li><li>noise/actuator：高频 roll-off 足够快。</li></ol><p>这五项互相牵制。设计过程本质是找一条“可实现的折中曲线”。</p>`},
  {title:'P 与 PI：先定 crossover，再补 low-frequency gain',html:String.raw`<p>P control $K=k$ 只把 magnitude 整体上下移动，不改 phase。常先用它把 crossover 移到目标范围。</p><p>PI：</p><p class="cs-equation">$$K_{PI}=k\left(1+\frac1{T_Is}\right).$$</p><p>它在低频有 integrator，使 $|L(0)|\to\infty$；在 $\omega\gg1/T_I$ 时近似 P。设计 tip：让 PI zero $1/T_I$ 明显低于 $\omega_c$，这样能改善 steady-state 又尽量不吃掉 PM。</p>`},
  {title:'Lag compensation：有限低频增益的温和版本',html:String.raw`<p>lag 常写成</p><p class="cs-equation">$$K_{lag}=\alpha\frac{Ts+1}{\alpha Ts+1},\qquad \alpha>1.$$</p><p>低频 gain 约提高 $\alpha$，高频趋近 1。若 pole/zero 都放在 crossover 下方较远处，crossover 附近影响小。相比 PI，它不给 infinite DC gain，因此更温和但不能保证任意 constant error 都为零。</p>`},
  {title:'PD / lead：用 phase lead 买 robustness',html:String.raw`<p>PD zero 在 crossover 附近能增加 phase，但 ideal PD 高频增益无界。实际常用 lead</p><p class="cs-equation">$$K_{lead}=k\frac{Ts+1}{\alpha Ts+1},\qquad 0<\alpha<1.$$</p><p>最大 phase lead 出现在</p><p class="cs-equation">$$\omega_{max}=\frac1{T\sqrt\alpha},\qquad \sin\phi_{max}=\frac{1-\alpha}{1+\alpha}.$$</p><p>通常令 $\omega_{max}$ 接近目标 crossover，让 phase boost 正好出现在最需要的地方。</p>`},
  {title:'一个可重复的 loop-shaping workflow',html:String.raw`<ol><li>画 plant Bode，标出 unstable / NMP features。</li><li>选择目标 $\omega_c$：高于需要的 disturbance band，低于 unmodeled dynamics。</li><li>用 gain 把 magnitude 推到 0 dB 附近。</li><li>若 low-frequency gain 不够，加 PI/lag。</li><li>若 PM 不够，加 lead/filtered PD。</li><li>重新计算 Nyquist、GM/PM、S/T、control effort。</li><li>最后做 time-domain simulation 与 saturation test。</li></ol>`},
  {title:'Inversion-based open-loop shaping',html:String.raw`<p>另一思路是先指定 desired loop $L_d(s)$，再令</p><p class="cs-equation">$$K(s)=L_d(s)G^{-1}(s).$$</p><p>这把“反复调 compensator”变成 model matching。但 inverse 可能 unstable、noncausal 或 high-order：RHP zero 会变成 unstable controller pole，relative degree 也可能让 $K$ non-proper。</p><p>因此 inversion 设计的核心不是“会求逆”，而是知道哪些 dynamics <em>不能</em>被安全逆掉。</p>`},
  {title:'Internal Model Control (IMC)',html:String.raw`<p>IMC 把 plant model $\hat G$ 放进 controller architecture 中。若 $G=\hat G$ 且无 disturbance，模型输出与真实输出一致，feedback correction 为 0；只有 model mismatch / disturbance 才驱动 correction。</p><p>通过参数 $Q$ 设计，标准 feedback controller 可写为</p><p class="cs-equation">$$K=\frac{Q}{1-\hat GQ}.$$</p><p>在 perfect-model 情况下 $T=GQ,\ S=1-GQ$，两者对 $Q$ 都是 affine，设计很直接。若想要 $T_d$，可取 $Q\approx G^{-1}T_d$，但仍必须做 stable / causal inverse approximation。</p>`},
  {title:'Stable / causal approximate inverse',html:String.raw`<p>三类不能直接 inverse 的东西：</p><ul><li>RHP zero → inverse 有 unstable pole：保留 all-pass / NMP 部分，不去逆。</li><li>delay $e^{-sT}$ → inverse 是 time advance：不能 causal 实现，只能保留 delay。</li><li>relative degree 不够 → inverse non-proper：加 stable low-pass poles 使其 proper。</li></ul><p>“近似逆到一个 delay / low-pass”为后面 2-DOF、disturbance decoupling 和 Smith predictor 的共同基础。</p>`}
 ],
 practice:String.raw`<ol><li>给定 plant Bode 在目标 $\omega_c$ 处 phase = −150°，你希望 PM≈60°，需要多少 phase lead？</li><li>设计 lead 的 $\alpha$ 使最大 phase lead 约 30°。</li><li>解释为什么 $G(s)$ 有 RHP zero 时不能把 $G^{-1}$ 直接放入 controller。</li><li>写出 IMC perfect-model 情况下的 $S,T$。</li></ol>`
}
];