window.courseUnits.push(
{
 id:'08', title:'Augmented Feedback Control Architectures', question:'一个普通 feedback loop 不够时，应该加 feedforward、cascade、anti-windup 还是 Smith predictor？',
 goals:['理解 disturbance decoupling 与 plant inverse 的条件。','会把 2-DOF 中 tracking 与 robustness 分开设计。','理解 cascade control 为什么要求 inner loop 更快。','掌握 saturation / windup 与 delay compensation 的基本结构。'],
 source:'HS2023 L08_Augmented_Feedback_Control_Architectures.pdf + B08 + sum7 + Exercise 7',
 sections:[
  {title:'Disturbance decoupling：如果 disturbance 可测',html:String.raw`<p>若 disturbance $w$ 通过 $G_w$ 进入输出，而 control input 通过 $G$ 进入，可以增加 feedforward $K_f$ 让两条通道相消：</p><p class="cs-equation">$$GK_f+G_w=0\quad\Rightarrow\quad K_f=-G_wG^{-1}.$$</p><p>这不是 feedback，因为 $K_f$ 直接用 disturbance measurement，而不是 error。优点是动作可提前；缺点是必须知道 $w$、$G$、$G_w$，而且 inverse 要稳定、causal、proper。</p><div class="cs-checkpoint"><strong>什么时候特别有效？</strong><p>如果 disturbance 可提前测量，例如 upstream flow、road slope estimate、known load schedule，feedforward 可以在 error 发生前就补偿。</p></div>`},
  {title:'Stable / causal inverse：哪些 dynamics 不能硬逆',html:String.raw`<p>课程把 inverse 的三类困难放在一起：</p><ul><li><strong>non-proper：</strong>$G^{-1}$ 分子阶数太高；加 low-pass filter。</li><li><strong>delay：</strong>$e^{-sT}$ 的 inverse 是 $e^{+sT}$，需要未来信息；保留 delay。</li><li><strong>RHP zero：</strong>inverse 产生 unstable pole；把 NMP part 作为 all-pass 保留，只逆 minimum-phase part。</li></ul><p>例如 $G(s)=\frac{-Ts+1}{s+3}$ 可分解成 all-pass $(-Ts+1)/(Ts+1)$ 与 minimum-phase $(Ts+1)/(s+3)$。近似 inverse 只逆第二部分。</p>`},
  {title:'2-DOF：feedback 和 feedforward 各做一半',html:String.raw`<p>2-DOF 架构写作</p><p class="cs-equation">$$u=K_{ff}r+K_{fb}(r-y).$$</p><p>feedback $K_{fb}$ 负责 stabilization、disturbance rejection、model uncertainty；feedforward $K_{ff}$ 负责 nominal reference tracking。若 plant inverse 可用，理想 $K_{ff}=G^{-1}$。</p><div class="cs-example"><span class="cs-label">ETH example</span><strong>$G(s)=1/(s^2+3s)$</strong><p>希望跟踪平滑 $r(t)$，feedforward 可用 $u_{ff}=\ddot r+3\dot r$；feedback 用 PD 稳定 tracking error。这样 reference dynamics 与 robustness 被明确分工。</p></div>`},
  {title:'Cascade control：为什么 inner loop 必须快',html:String.raw`<p>cascade 有 inner controller $K_1$ 调节内部变量 $y_1$，outer controller $K_2$ 根据最终输出 $y_2$ 生成 inner reference。它特别适合 disturbance 在 plant 内部某处先影响 $y_1$ 的情况。</p><p>关键假设：inner closed loop 比 outer loop 快很多。于是从 outer loop 看，inner loop 几乎是一个 static gain：</p><p class="cs-equation">$$G_{inner}(s)\approx G_{inner}(0)\quad\text{in outer-loop bandwidth}.$$</p><p>若两个 loops 速度相近，separation 不成立，两个 controllers 会互相影响甚至 destabilize。</p>`},
  {title:'Actuator saturation 与 integrator windup',html:String.raw`<p>理想 PI/PID 假设 controller command $u_c$ 能被 actuator 原样实现。但真实 actuator 有 $u_{min}\le u\le u_{max}$。当 saturated 时，error 仍被积分，integrator state 越积越大；即使 error 之后反号，也需要很久才能“解卷”。</p><p>这就是 windup。它会造成长时间 saturation、大 overshoot 与恢复缓慢。</p>`},
  {title:'Anti-windup：让 integrator 知道 actuator 实际做了什么',html:String.raw`<p>常见 back-calculation 把 $u-u_c$ 反馈到 integrator：</p><p class="cs-equation">$$\dot x_I=e+K_a(u-u_c).$$</p><p>未 saturation 时 $u=u_c$，额外项为 0；saturation 时，差值把 integrator 往可实现 command 拉回。课程给出的等效 transfer function 表明 saturated 时 integrator 被替换为 lag-like dynamics。</p><div class="cs-callout"><strong>设计思维</strong><p>anti-windup 不是“优化 PID 参数”，而是在 controller model 里显式承认 actuator nonlinearity。</p></div>`},
  {title:'Smith predictor：delay 不能消失，但可以从 design loop 中移开',html:String.raw`<p>plant 若为 $G(s)e^{-\lambda s}$，delay 会严重减少 phase margin。Smith predictor 用内部模型预测 delay-free plant output，形成等效 controller</p><p class="cs-equation">$$K'(s)=\frac{K(s)}{1+K(s)G(s)(1-e^{-\lambda s})}.$$</p><p>最终 nominal closed-loop response 是</p><p class="cs-equation">$$T(s)=\frac{KG}{1+KG}e^{-\lambda s}.$$</p><p>因此你可以按 delay-free $G$ 设计 dynamics；但物理 output 仍晚 $\lambda$ 秒出现。因果 controller 不可能让真实输出提前。</p>`},
  {title:'Architecture selection：该用哪一种？',html:String.raw`<div class="cs-table-wrap"><table class="cs-table"><thead><tr><th>问题</th><th>优先结构</th><th>核心条件</th></tr></thead><tbody><tr><td>reference 已知且模型较准</td><td>2-DOF / feedforward</td><td>inverse 可近似实现</td></tr><tr><td>disturbance 可测</td><td>disturbance feedforward</td><td>$G_w,G$ 已知</td></tr><tr><td>内部变量可测且 dynamics 分层</td><td>cascade</td><td>inner loop 明显更快</td></tr><tr><td>actuator saturation</td><td>anti-windup</td><td>有 saturation feedback</td></tr><tr><td>大纯 delay</td><td>Smith predictor</td><td>delay/model 较准</td></tr></tbody></table></div><p>真正工程系统往往把这些结构组合起来，而不是只选一个。</p>`}
 ],
 practice:String.raw`<ol><li>推导 disturbance decoupling 的 $K_f=-G_wG^{-1}$。</li><li>解释为什么 2-DOF 中 $K_{ff}$ 的 causality 限制有时比 feedback 中更宽松。</li><li>画一个 PI + saturation + anti-windup block diagram。</li><li>若 inner bandwidth=50 rad/s、outer target=30 rad/s，为什么 cascade separation 很可疑？</li></ol>`
},
{
 id:'09', title:'State-Space Control Systems', question:'进入 MIMO 和高阶系统以后，“哪些状态能被输入真正影响”要怎样精确回答？',
 goals:['会用 RGA 判断 MIMO input-output pairing。','区分 reachability 与 controllability。','掌握 controllability matrix、PBH、Gramian 三种等价视角。','理解 uncontrollable modes 与 stabilizability。'],
 source:'HS2023 L09 State-Space Control Systems.pdf + B09 + sum8 + Exercise 8',
 sections:[
  {title:'MIMO transfer matrix 与 coupling',html:String.raw`<p>MIMO 系统写成 $y=G(s)u$，其中 $G$ 是 transfer matrix。即使每个 diagonal entry 看起来合理，off-diagonal terms 也会让多个 SISO loops 互相“打架”。</p><p>最简单的 2×2 情况：</p><p class="cs-equation">$$\begin{bmatrix}y_1\\y_2\end{bmatrix}=\begin{bmatrix}g_{11}&g_{12}\\g_{21}&g_{22}\end{bmatrix}\begin{bmatrix}u_1\\u_2\end{bmatrix}.$$</p><p>如果 $g_{12},g_{21}$ 不小，改变 $u_1$ 会同时改变两个 outputs，不能把 loops 当成独立。</p>`},
  {title:'Relative Gain Array (RGA)',html:String.raw`<p>RGA 定义为</p><p class="cs-equation">$$\Lambda(s)=G(s)\odot G(s)^{-T},$$</p><p>$\odot$ 是 element-wise multiplication。static pairing 常看 $\Lambda(0)$。若 $\lambda_{ij}\approx1$，输入 $u_j$ 与输出 $y_i$ 是较自然的 pairing；large negative 或 strongly varying entries 通常意味着 pairing 很脆弱。</p><p>每一行和每一列的 entries 都和为 1，这反映“相对作用”被归一化。</p>`},
  {title:'Decoupling compensator',html:String.raw`<p>可以在 plant 前放 $H(s)$，希望 $G(s)H(s)$ 近似 diagonal，再用多个 SISO controllers。2×2 时一种结构是</p><p class="cs-equation">$$H=\begin{bmatrix}1&-g_{12}/g_{11}\\-g_{21}/g_{22}&1\end{bmatrix}.$$</p><p>但 $H$ 也必须 stable、causal、proper。若需要 inverse RHP zeros 或 time advances，exact decoupling 不可实现，只能做 approximate decoupling。</p>`},
  {title:'Reachability vs controllability',html:String.raw`<p>给定 horizon $T$，state $x_T$ <strong>reachable</strong> 是指存在 input 把 $x(0)=0$ 驱到 $x(T)=x_T$；state $x_0$ <strong>controllable</strong> 是指存在 input 把 $x(0)=x_0$ 驱到 $x(T)=0$。</p><p>连续时间里 $e^{AT}$ 总可逆，所以两者等价。离散时间若 $A$ singular，controllability 与 reachability 可能不完全等价。</p>`},
  {title:'Controllability matrix',html:String.raw`<p>定义</p><p class="cs-equation">$$W_c=[B\ AB\ A^2B\ \cdots\ A^{n-1}B].$$</p><p>系统 reachable / controllable 当且仅当 $\operatorname{rank}W_c=n$。为什么只到 $A^{n-1}$？Cayley–Hamilton 保证更高次 $A^kB$ 都在前面 columns 的 span 中。</p><div class="cs-example"><span class="cs-label">Double integrator</span><p>$A=\begin{bmatrix}0&1\\0&0\end{bmatrix},B=[0,1]^T$，$W_c=[B,AB]=\begin{bmatrix}0&1\\1&0\end{bmatrix}$，full rank。虽然只有一个 actuator，它仍能控制 position 与 velocity 两个 states。</p></div>`},
  {title:'PBH test：逐个 mode 问“输入碰得到吗？”',html:String.raw`<p>PBH test：</p><p class="cs-equation">$$\operatorname{rank}[A-\lambda I\ \ B]=n\quad\forall\lambda\in\sigma(A).$$</p><p>如果对某个 eigenvalue $\lambda$ 失 rank，这个 mode uncontrollable。左 eigenvector 形式更直观：若存在 $w^TA=\lambda w^T$ 且 $w^TB=0$，输入对该 mode 的 projection 永远为 0。</p><p>PBH 特别适合判断“只有哪些 modes 出问题”，而 rank $W_c$ 更像全局 yes/no test。</p>`},
  {title:'Controllability Gramian 与 minimum-energy control',html:String.raw`<p>有限 horizon Gramian</p><p class="cs-equation">$$P_T=\int_0^T e^{A\tau}BB^Te^{A^T\tau}d\tau.$$</p><p>$P_T$ nonsingular 当且仅当 system reachable。更重要的是，它给出“到某个方向有多难”。minimum-energy input 驱动 0→$v$ 为</p><p class="cs-equation">$$u^*(t)=B^Te^{A^T(T-t)}P_T^{-1}v.$$</p><p>能到达不等于容易到达：Gramian 很 ill-conditioned 时，某些方向需要巨大 control energy。</p>`},
  {title:'Uncontrollable modes 与 stabilizability',html:String.raw`<p>通过 staircase / Kalman decomposition，可以把 state 分成 controllable 与 uncontrollable 部分。uncontrollable modes 无法用 state feedback 移动。</p><p>但控制设计不要求每个 mode 都 controllable：如果 uncontrollable modes 本来就 stable，仍能把整个系统稳定。这叫 <strong>stabilizable</strong>。</p><p>PBH 版本：只要求所有 RHP / unstable eigenvalues 满足 controllability rank condition。</p>`}
 ],
 practice:String.raw`<ol><li>计算 double integrator 的 $W_c$ 并解释为什么单输入仍可控。</li><li>用 PBH 判断 $A=\operatorname{diag}(1,-2),B=[0,1]^T$ 是否 stabilizable。</li><li>给一个 2×2 static $G(0)$，计算 RGA 并选择 pairing。</li><li>解释 Gramian eigenvalue 很小时的工程含义。</li></ol><details><summary>答案提示</summary><p>第 2 题 unstable mode $+1$ 不受 B 影响，因此不可 stabilizable。</p></details>`
},
{
 id:'10', title:'State-Space Control Design', question:'如果系统 controllable，我们怎样直接安排 closed-loop poles，并同时解决 reference tracking？',
 goals:['理解 controllable canonical form 为什么让 pole placement 变简单。','会设计 full-state feedback $u=-Kx$。','掌握 pole placement、Ackermann 与二阶性能指标。','会加入 prefilter 或 integral state 实现 tracking。'],
 source:'HS2023 L10_State-Space_Control_Design.pdf + B10 + sum9 + Exercise 9',
 sections:[
  {title:'Controllable canonical form (CCF)',html:String.raw`<p>对 SISO transfer function</p><p class="cs-equation">$$G(s)=\frac{b_{n-1}s^{n-1}+\cdots+b_0}{s^n+a_{n-1}s^{n-1}+\cdots+a_0},$$</p><p>CCF 选</p><p class="cs-equation">$$A_c=\begin{bmatrix}0&1&\cdots&0\\ \vdots&&\ddots&\vdots\\0&0&\cdots&1\\-a_0&-a_1&\cdots&-a_{n-1}\end{bmatrix},\quad B_c=\begin{bmatrix}0\\\vdots\\0\\1\end{bmatrix}.$$</p><p>它的 controllability matrix 自动 full rank，而且 characteristic coefficients 直接写在最后一行。</p>`},
  {title:'Full-state feedback 改变 A，而不是“直接改 state”',html:String.raw`<p>选</p><p class="cs-equation">$$u=-Kx,$$</p><p>闭环变成 $\dot x=(A-BK)x$。因此所有 dynamics 设计都转化为选择 $K$，让 $A-BK$ 的 eigenvalues 合适。</p><p>在 CCF 中，$BK$ 只修改最后一行，所以 characteristic polynomial coefficients 直接变成 $a_i+k_i$。这就是 pole placement 最清楚的代数来源。</p>`},
  {title:'Pole placement 与 Ackermann',html:String.raw`<p>若目标 poles 为 $p_1,\ldots,p_n$，目标多项式</p><p class="cs-equation">$$\phi_d(s)=\prod_i(s-p_i)=s^n+q_{n-1}s^{n-1}+\cdots+q_0.$$</p><p>在 CCF 中直接 coefficient matching 得到 gains，再通过 coordinate transform 回原坐标。Ackermann formula 把这一步压成一个表达式；数值上通常使用可靠的 `place` algorithm，而不是显式算高次 inverse。</p><pre class="cs-code"><code>K = control.place(A, B, desired_poles)</code></pre>`},
  {title:'极点放哪里？把 time-domain specs 翻译成 region',html:String.raw`<p>dominant second-order pair $s^2+2\zeta\omega_ns+\omega_n^2$ 常用近似：</p><p class="cs-equation">$$M_p=e^{-\pi\zeta/\sqrt{1-\zeta^2}},\quad t_s(1\%)\approx\frac{4.6}{\zeta\omega_n},\quad t_r\approx\frac{1.8}{\omega_n}.$$</p><p>因此 specs 可变成 complex-plane region：左边界保证 settling time，cone 保证 damping，右侧不能太靠左则限制 noise amplification / actuator effort。</p>`},
  {title:'Tracking constant reference：steady-state prefilter',html:String.raw`<p>$u=-Kx$ 默认 regulation 到 0。若要 $y\to r$，先找 steady state $(x_s,u_s)$：</p><p class="cs-equation">$$0=Ax_s+Bu_s,\qquad r=Cx_s+Du_s.$$</p><p>令 $x_s=N_xr,u_s=N_ur$，解</p><p class="cs-equation">$$\begin{bmatrix}A&B\\C&D\end{bmatrix}\begin{bmatrix}N_x\\N_u\end{bmatrix}=\begin{bmatrix}0\\1\end{bmatrix}.$$</p><p>于是</p><p class="cs-equation">$$u=-Kx+(N_u+KN_x)r=-Kx+\bar Nr.$$</p><p>这是 model-based prefilter；若模型有 bias，steady-state error 会重新出现。</p>`},
  {title:'Integral augmentation：对 model mismatch 更鲁棒的 tracking',html:String.raw`<p>引入</p><p class="cs-equation">$$x_I=\int_0^t(r-y)d\tau,\qquad \dot x_I=r-Cx-Du.$$</p><p>把 $x_I$ 加入 augmented state，再做 pole placement：</p><p class="cs-equation">$$u=-[K_x\ K_I]\begin{bmatrix}x\\x_I\end{bmatrix}.$$</p><p>若 augmented closed loop stable，steady state 必须有 $\dot x_I=0$，所以 tracking error 为 0。相比 prefilter，它能抵抗 constant model error / disturbance，但会增加 order、可能带来 windup。</p>`},
  {title:'Pole placement 的数值与工程限制',html:String.raw`<p>理论上 controllable 就能“任意放 poles”，工程上却不该这么做：</p><ul><li>far-left poles 需要大 control effort；</li><li>model uncertainty 会让过快 dynamics 不可信；</li><li>poorly conditioned eigenvectors 可能出现大 transient；</li><li>actuator saturation 会破坏线性设计假设；</li><li>state measurement 可能需要 observer，observer noise 又限制速度。</li></ul><p>L13 的 LQR 就是为了用 cost trade-off 替代“拍脑袋选 poles”。</p>`},
  {title:'State-feedback design workflow',html:String.raw`<ol><li>检查 stabilizability / controllability。</li><li>把 performance specs 变成 pole region。</li><li>选 poles，求 $K$。</li><li>决定 tracking：prefilter 还是 integrator。</li><li>检查 input magnitude / saturation。</li><li>如果 states 不全可测，进入 L11 observer。</li><li>对 model perturbation 做 robustness simulation。</li></ol>`}
 ],
 practice:String.raw`<ol><li>对 double integrator 设计 poles at $-2,-3$ 的 $K$。</li><li>从 $M_p<10\%$ 推一个最小 damping ratio 的量级。</li><li>推导 steady-state prefilter $\bar N$。</li><li>写出 $D=0$ 时 integral-augmented system matrices。</li></ol>`
},
{
 id:'11', title:'State Estimation & Output Feedback', question:'如果 state feedback 很好用，但真实系统只能测到一部分 outputs，怎样把“看不见的 state”重建出来？',
 goals:['理解 observability / constructibility 与 controllability 的对偶性。','会用 observability matrix、PBH、Gramian 判断可观性。','掌握 Luenberger observer 与 observer pole placement。','理解 separation principle 与 detectability。'],
 source:'HS2023 L11_State-Estimation-and-Output-Feedback.pdf + B11 + sum10 + Exercise 10',
 sections:[
  {title:'Observability 与 constructibility',html:String.raw`<p>对 $\dot x=Ax, y=Cx$，initial state $x(0)$ 若能从未来一段 output $y(t),t\in[0,T]$ 唯一恢复，就叫 observable；terminal state $x(T)$ 若能从过去 measurements 恢复，叫 constructible。连续时间 LTI 中两者等价。</p><p>直觉：controllability 问“input 能不能碰到这个 mode”；observability 问“sensor 能不能看到这个 mode”。</p>`},
  {title:'Observability matrix 与 derivative viewpoint',html:String.raw`<p>若输入已知，可以从</p><p class="cs-equation">$$y=Cx,\quad \dot y=CAx,\quad y^{(2)}=CA^2x,\ldots$$</p><p>得到</p><p class="cs-equation">$$W_o=\begin{bmatrix}C\\CA\\\vdots\\CA^{n-1}\end{bmatrix}.$$</p><p>系统 observable 当且仅当 $\operatorname{rank}W_o=n$。虽然实际不应该数值微分 noisy measurement，但这个推导清楚解释了 rank test。</p>`},
  {title:'PBH、Gramian 与 duality',html:String.raw`<p>PBH observability test：</p><p class="cs-equation">$$\operatorname{rank}\begin{bmatrix}A-\lambda I\\C\end{bmatrix}=n\quad\forall\lambda\in\sigma(A).$$</p><p>Observability Gramian</p><p class="cs-equation">$$Q_T=\int_0^T e^{A^Tt}C^TCe^{At}dt$$</p><p>nonsingular 也等价于 observable。把 controllability 的 $(A,B)$ 换成 $(A^T,C^T)$，几乎所有 theorem 都变成 observability theorem，这就是 duality。</p>`},
  {title:'Kalman decomposition 与 detectability',html:String.raw`<p>任何系统都能通过 coordinate transform 分成四类 states：controllable/observable、uncontrollable/observable、controllable/unobservable、uncontrollable/unobservable。</p><p>transfer function 只“看见”既 controllable 又 observable 的部分，这解释了 hidden modes / pole-zero cancellations。</p><p><strong>Detectable</strong> 比 observable 弱：允许 unobservable modes 存在，只要它们本身 stable。对 observer stabilization 来说，这就够了。</p>`},
  {title:'Luenberger observer：simulation + correction',html:String.raw`<p>observer 结构：</p><p class="cs-equation">$$\dot{\hat x}=A\hat x+Bu+L(y-C\hat x).$$</p><p>第一部分是 model simulation，第二部分是 innovation / output error correction。定义 estimation error $\epsilon=x-\hat x$：</p><p class="cs-equation">$$\dot\epsilon=(A-LC)\epsilon.$$</p><p>因此 observer design 就是选 $L$ 让 $A-LC$ stable。若 $(A,C)$ observable，可以任意 assign observer poles。</p>`},
  {title:'Observer poles 不是越快越好',html:String.raw`<p>把 observer poles 放更左，initial estimation error 收敛更快；但 correction input 是 $Ly$，$L$ 往往随 pole speed 增大，因此 sensor noise 也被放大。</p><p>所以常见经验“observer 比 controller 快几倍”只是起点，必须结合 noise、sampling、unmodeled dynamics。L14 Kalman filter 会用 process/measurement covariance 自动形成这个 trade-off。</p>`},
  {title:'Separation principle',html:String.raw`<p>使用 estimated state feedback $u=-K\hat x$，在坐标 $[x;\epsilon]$ 下：</p><p class="cs-equation">$$\frac d{dt}\begin{bmatrix}x\\\epsilon\end{bmatrix}=\begin{bmatrix}A-BK&BK\\0&A-LC\end{bmatrix}\begin{bmatrix}x\\\epsilon\end{bmatrix}.$$</p><p>矩阵 block triangular，所以 closed-loop eigenvalues 是 $A-BK$ 与 $A-LC$ eigenvalues 的 union。于是 controller 与 observer 可以独立设计。</p><p>更一般地，只要 $(A,B)$ stabilizable、$(A,C)$ detectable，就存在 stabilizing observer-based output feedback。</p>`},
  {title:'Output-feedback workflow',html:String.raw`<ol><li>检查 stabilizability 与 detectability。</li><li>设计 state feedback $K$。</li><li>设计 observer $L$，先不要过快。</li><li>组合 $u=-K\hat x$。</li><li>验证 noise、initial estimation error、input saturation。</li><li>若噪声统计有意义，考虑 L14 Kalman filter 取代手工 observer poles。</li></ol>`}
 ],
 practice:String.raw`<ol><li>对 $A=\operatorname{diag}(1,-2),C=[0,1]$ 判断 detectability。</li><li>推导 observer error dynamics。</li><li>解释为什么 $W_o$ full rank 与“能从 output history 唯一恢复 state”等价。</li><li>用 block-triangular matrix 证明 separation principle。</li></ol>`
},
{
 id:'12', title:'Sampled-Data / Digital Control', question:'连续 plant 加上采样、保持器和数字算法以后，哪些连续时间直觉还能保留，哪些会失效？',
 goals:['理解 sampling theorem、aliasing 与 anti-alias filtering。','掌握 s-plane 与 z-plane stability mapping。','会比较 forward/backward Euler 与 Tustin。','掌握 ZOH discretization、controller emulation、deadbeat 与 difference-equation implementation。'],
 source:'HS2023 L12_DigitalControl.pdf + B12 Digital Control + sum11 + Exercise 11',
 sections:[
  {title:'Sampling 与 aliasing',html:String.raw`<p>采样周期 $T$，sampling angular frequency $\omega_s=2\pi/T$。对 $f(t)=\cos\omega t$：</p><p class="cs-equation">$$f[k]=\cos(\omega kT).$$</p><p>频率 $\omega$ 与 $\omega\pm n\omega_s$ 在 samples 上完全不可区分，这就是 aliases。可无歧义重建的最高频率是 Nyquist frequency $\omega_s/2$。</p><p>在 control 中 aliasing 特别危险：高频 sensor noise 可能折叠成低频“假振荡”，controller 会真的去纠正它。实际系统常在 A/D 前放 analog anti-alias low-pass filter。</p>`},
  {title:'s-plane 到 z-plane：z=e^(sT)',html:String.raw`<p>连续 mode $e^{st}$ 在 sampling instants $t=kT$ 变成 $(e^{sT})^k$，所以</p><p class="cs-equation">$$z=e^{sT}.$$</p><p>若 $s=\alpha+j\beta$，则 $|z|=e^{\alpha T}$。LHP 映射到 unit disk 内，imaginary axis 映射到 unit circle。不同 continuous frequencies 还会因为 angle modulo $2\pi$ 映射到同一个 discrete angle，这也是 aliasing 的复平面版本。</p>`},
  {title:'Forward Euler、Backward Euler、Tustin',html:String.raw`<p>三种常见 derivative substitutions：</p><p class="cs-equation">$$\text{forward: }s\approx\frac{z-1}{T},\quad \text{backward: }s\approx\frac{z-1}{Tz},\quad \text{Tustin: }s\approx\frac2T\frac{z-1}{z+1}.$$</p><p>Tustin 来自 bilinear transform / trapezoidal integration。它把整个 LHP 映到 unit disk，因此稳定 continuous controller 会变成 stable discrete controller。</p><p>代价是 frequency warping：$j\omega$ 与 unit-circle angle 不是线性对应；关键频率可用 prewarping 校正。</p>`},
  {title:'Controller emulation 与 sampling-rate rule of thumb',html:String.raw`<p>常见 workflow：先在 continuous time 设计 $C(s)$，再选 $T$ 并离散成 $C_d(z)$。HS2023 exercise summary 给的 rule of thumb：</p><p class="cs-equation">$$\omega_s\gtrsim25\,\omega_{bw}.$$</p><p>这不是 theorem，而是让 discrete implementation 足够接近 continuous design 的工程起点。若不能 sample 这么快，应该直接做 discrete-time design，而不是强行 emulation。</p>`},
  {title:'Zero-order hold (ZOH) state-space discretization',html:String.raw`<p>假设 DAC 在每个 sampling interval 保持输入常数。则 exact sampled model：</p><p class="cs-equation">$$A_d=e^{AT},\qquad B_d=\int_0^T e^{A\tau}B\,d\tau,\qquad C_d=C,\ D_d=D.$$</p><p>若 $A$ invertible：</p><p class="cs-equation">$$B_d=A^{-1}(e^{AT}-I)B.$$</p><p>这不是 numerical approximation；在 sampling instants 上它对 piecewise-constant input 是 exact。</p>`},
  {title:'ZOH transfer function 与 step invariance',html:String.raw`<p>频域公式可写为</p><p class="cs-equation">$$G_d(z)=(1-z^{-1})\,\mathcal Z\left\{\mathcal L^{-1}\left[\frac{G(s)}s\right]_{t=kT}\right\}.$$</p><p>它之所以叫 step-invariant，是因为 discrete model 的 step response 正好等于 continuous plant step response 在 sampling instants 的 samples。</p><p>注意：ZOH 可能引入新的 sampling zeros；continuous-time minimum-phase 不保证所有 discrete zeros 都“好看”。</p>`},
  {title:'Discrete-time pole placement 与 deadbeat',html:String.raw`<p>离散稳定要求 closed-loop poles 在 unit disk。最激进的 design 是把所有 poles 放到 $z=0$，称 deadbeat control：理想线性模型中有限步到达目标。</p><p>但 $z=0$ 相当于 continuous pole $s\to-\infty$ 的极端快速 dynamics，通常需要非常大 control action，对 model error、noise 与 saturation 都敏感。</p><div class="cs-callout"><strong>Deadbeat 是极限，不是默认目标</strong><p>它很好地展示“最快 response”和“最小 effort / robustness”之间的冲突。</p></div>`},
  {title:'Difference equation implementation',html:String.raw`<p>最终 microcontroller 运行的不是 transfer function 图，而是递推式。例如</p><p class="cs-equation">$$u[k]=a_1u[k-1]+b_0e[k]+b_1e[k-1].$$</p><p>实现时还要处理 sample timestamp、sensor filtering、numeric precision、saturation、anti-windup、initialization。一个 mathematically stable $C_d(z)$ 如果 timing jitter 或 actual sample period 和设计不同，也可能性能恶化。</p><pre class="cs-code"><code>sysd = control.c2d(sysc, T, method='zoh')
Cd   = control.c2d(Cc, T, method='tustin')</code></pre>`}
 ],
 practice:String.raw`<ol><li>$T=0.01$s 时 $\omega_s$ 与 Nyquist angular frequency 是多少？</li><li>把 continuous pole $s=-2+3j$ 映射到 $T=0.1$s 的 z-plane。</li><li>推导 scalar $\dot x=ax+bu$ 的 $A_d,B_d$。</li><li>解释为什么 deadbeat control 很容易撞 saturation。</li></ol>`
},
{
 id:'13', title:'Optimal Control · Linear-Quadratic Regulator', question:'既然 controllable 系统可以任意 pole placement，为什么还要 LQR？“最优”到底优化了什么？',
 goals:['理解 eigenvalue placement 对 transient 的局限。','掌握 finite/infinite horizon quadratic cost 与 Riccati equation。','理解 Q/R 如何编码 state deviation 与 control effort trade-off。','掌握 CT/DT LQR 的存在条件与基本鲁棒性结论。'],
 source:'HS2023 L13_Optimal_Control.pdf + B13 Optimal Control + summary12 + Exercise 12',
 sections:[
  {title:'Pole placement 的 fallacy：poles 相同，transient 可以完全不同',html:String.raw`<p>课程先给一个 non-normal matrix：</p><p class="cs-equation">$$A=\begin{bmatrix}-1&M\\0&-1\end{bmatrix}.$$</p><p>无论 $M$ 多大，eigenvalues 都是 $-1,-1$；但 $x_2$ 会通过大 gain $M$ 驱动 $x_1$，产生巨大 transient amplification。只看 poles 看不见 eigenvector geometry、control energy、disturbance amplification。</p><p>这正是 LQR 的动机：不要先“猜 poles”，而是直接定义什么行为值得付出代价。</p>`},
  {title:'Quadratic cost：把设计偏好写进数学',html:String.raw`<p>finite horizon cost：</p><p class="cs-equation">$$J_T=x(T)^TP_Tx(T)+\int_0^T\left(x^TQx+u^TRu\right)dt.$$</p><p>$P_T\succeq0$ 惩罚 terminal state，$Q\succeq0$ 惩罚 trajectory state deviation，$R\succ0$ 惩罚 control effort。</p><p>大的 $Q$ 表示“状态偏离很贵”，controller 更 aggressive；大的 $R$ 表示“actuator 动作很贵”，controller 更温和。</p>`},
  {title:'Finite-horizon LQR 与 differential Riccati equation',html:String.raw`<p>最优 control 仍然是线性 state feedback：</p><p class="cs-equation">$$u^*(t)=-K(t)x(t),\qquad K(t)=R^{-1}(t)B^TP(t).$$</p><p>$P(t)$ 从 terminal condition $P(T)=P_T$ 向后解 differential Riccati equation：</p><p class="cs-equation">$$\dot P=-A^TP-PA+PBR^{-1}B^TP-Q.$$</p><p>最优 cost 是 $J_T^*=x_0^TP(0)x_0$。因此 $P$ 同时是 value function 的 quadratic matrix。</p>`},
  {title:'Infinite-horizon LQR 与 algebraic Riccati equation',html:String.raw`<p>若 $A,B,Q,R$ constant 且 horizon $T\to\infty$，$P(t)$ 收敛到 constant $P$，满足 ARE：</p><p class="cs-equation">$$A^TP+PA-PBR^{-1}B^TP+Q=0.$$</p><p>最优 gain</p><p class="cs-equation">$$K=R^{-1}B^TP,$$</p><p>闭环 $A-BK$ asymptotically stable（在标准 stabilizability / detectability 条件下）。这是一种“由 cost 自动选 poles”的 state feedback。</p>`},
  {title:'Double integrator：Q/R 怎样改变 controller',html:String.raw`<p>对</p><p class="cs-equation">$$A=\begin{bmatrix}0&1\\0&0\end{bmatrix},\quad B=\begin{bmatrix}0\\1\end{bmatrix},$$</p><p>若 $Q=\operatorname{diag}(q_1,q_2),R=r$，增大 $q_1$ 会更强地惩罚 position error，通常增加 position feedback gain；增大 $r$ 会让所有 control action 更贵，gain 下降、closed-loop poles 靠近 open-loop poles。</p><p>只有 relative weights 重要：把 $Q,R$ 同时乘同一个正数，不改变最优 $K$。</p>`},
  {title:'如何实际选 Q 和 R',html:String.raw`<p>一种工程起点是 Bryson-style normalization：若 state $x_i$ 可接受最大量级为 $x_{i,max}$，令 $Q_{ii}\sim1/x_{i,max}^2$；若 input 最大合理量级 $u_{max}$，令 $R\sim1/u_{max}^2$。</p><p>然后通过 simulation 看 settling、overshoot、input peaks、disturbance response，再调整 relative weights。不要把 $Q,R$ 当成“物理真理”；它们是 design preferences。</p>`},
  {title:'Existence：stabilizable + detectable',html:String.raw`<p>Infinite-horizon ARE 的 stabilizing solution 需要：</p><ul><li>$(A,B)$ stabilizable：所有 unstable modes 都可控；</li><li>$(A,Q^{1/2})$ detectable：所有不会被 cost “看见”的 unstable modes 必须不存在。</li></ul><p>第二条很有直觉：如果某个 unstable state direction 在 $Q$ 中完全不收费，optimizer 没有理由花 control effort 去压它。</p>`},
  {title:'LQR robustness 与 discrete-time LQR',html:String.raw`<p>标准 continuous-time SISO LQR 有很强的 return-difference robustness 性质；课程 summary 给出至少 60° phase margin 与 infinite gain margin 的经典结论。但这不意味着所有 MIMO/LQG 组合都自动 robust。</p><p>离散系统 $x_{k+1}=Ax_k+Bu_k$ 的 infinite-horizon LQR 使用 DARE：</p><p class="cs-equation">$$P=A^TPA-A^TPB(R+B^TPB)^{-1}B^TPA+Q,$$</p><p class="cs-equation">$$K=(R+B^TPB)^{-1}B^TPA.$$</p><pre class="cs-code"><code>K, P, eigs = control.lqr(A,B,Q,R)
Kd,Pd,eigs_d = control.dlqr(Ad,Bd,Q,R)</code></pre>`}
 ],
 practice:String.raw`<ol><li>解释 $A=[[-1,100],[0,-1]]$ 为什么 poles 稳定却 transient 可很大。</li><li>若把 $R$ 放大 100 倍，直观上 $K$ 会怎样变化？</li><li>说明 $(A,Q^{1/2})$ detectability 的设计含义。</li><li>写出 CT ARE 与 DT DARE，并比较 gain formula。</li></ol>`
},
{
 id:'14', title:'Optimal Estimation · Kalman Filter', question:'当 model 有 process noise、sensor 有 measurement noise 时，怎样“最优地相信模型”和“最优地相信测量”？',
 goals:['建立 process noise / measurement noise 的 stochastic model。','理解 Kalman filter 是 optimal observer，而不是神奇的 smoothing trick。','掌握 continuous Kalman–Bucy 与 discrete Kalman recursion。','理解 LQR–Kalman duality、LQG separation 与 robustness caveat。'],
 source:'HS2023 L14_Optimal-Estimation-Kalman-Filter.pdf + summary13 + Exercise 13',
 sections:[
  {title:'Sensor fusion 的问题形式',html:String.raw`<p>课程从 autonomous car 开始：position、velocity 同时受 unknown road disturbance 影响，而且 GPS、odometry、radar 等 sensors 各自带 noise。模型写成</p><p class="cs-equation">$$\dot x=Ax+Bu+w,\qquad y=Cx+v.$$</p><p>$w$ 是 process noise，表示“模型没解释到的动力学”；$v$ 是 measurement noise，表示 sensor uncertainty。我们想从过去所有 measurements 得到 minimum-mean-square-error state estimate。</p>`},
  {title:'从 Luenberger observer 到 stochastic observer',html:String.raw`<p>L11 observer</p><p class="cs-equation">$$\dot{\hat x}=A\hat x+Bu+L(y-C\hat x)$$</p><p>里 $L$ 由 designer 选 poles。Kalman filter 保留相同结构，但用 noise statistics 自动选择 $L$。因此它不是另一个完全不同的算法，而是“带有最优 gain 选择规则的 observer”。</p>`},
  {title:'LQR–Kalman duality',html:String.raw`<p>LQR 在 $A-BK$ 上选 $K$；observer 在 $A-LC$ 上选 $L$。通过</p><p class="cs-equation">$$(A,B,K)\longleftrightarrow(A^T,C^T,L^T),$$</p><p>control 与 estimation 的 Riccati equations 成为对偶。LQR trade-off 是 state deviation vs control effort；Kalman trade-off 是 model/process uncertainty vs measurement correction/noise。</p>`},
  {title:'Continuous-time Kalman–Bucy filter',html:String.raw`<p>假设 $w,v$ 是 zero-mean white Gaussian noise，covariances $Q\succeq0,R\succ0$，且互不相关。optimal estimator：</p><p class="cs-equation">$$\dot{\hat x}=A\hat x+Bu+L(t)(y-C\hat x),$$</p><p class="cs-equation">$$L(t)=P(t)C^TR^{-1}.$$</p><p>error covariance $P=E[(x-\hat x)(x-\hat x)^T]$ 满足</p><p class="cs-equation">$$\dot P=AP+PA^T-PC^TR^{-1}CP+Q.$$</p><p>constant covariances 下，steady-state $P$ 解 algebraic Riccati equation，gain 也变 constant。</p>`},
  {title:'Q 与 R：到底该更相信 model 还是 sensor',html:String.raw`<p>若 process covariance $Q$ 大，表示你不太信 model，filter 会倾向更快用 measurement correction；Kalman gain 通常变大。若 measurement covariance $R$ 大，表示 sensor 很 noisy，filter 更信 prediction，gain 变小。</p><div class="cs-example"><span class="cs-label">Scalar intuition</span><p>估计 constant state，sensor 很准时 $R\downarrow$，每次 measurement 应强烈纠正 estimate；sensor 很差时 $R\uparrow$，频繁追着 measurement noise 跑反而更糟。</p></div><p>真实 tuning 最困难的是 $Q$：它代表的往往不是“真正白噪声”，而是未建模 dynamics 的有效统计描述。</p>`},
  {title:'Innovation：measurement 中还剩多少新信息',html:String.raw`<p>innovation / residual</p><p class="cs-equation">$$r_y=y-C\hat x$$</p><p>是 measurement 相对 prediction 的 surprise。理想 Kalman filter 下 innovation 应近似 white；如果 residual 有明显 temporal correlation，常说明 model、$Q/R$ 或 sensor bias 有问题。</p><p>这给了实际调试手段：不仅看 state estimate 好不好，还看 innovation statistics 是否符合假设。</p>`},
  {title:'Discrete-time Kalman filter：prediction + correction',html:String.raw`<p>对</p><p class="cs-equation">$$x_{k+1}=Ax_k+Bu_k+w_k,\qquad y_k=Cx_k+v_k,$$</p><p>最常用实现分两步理解：</p><h3>Predict</h3><p class="cs-equation">$$\hat x^-_{k}=A\hat x^+_{k-1}+Bu_{k-1},\quad P^-_k=AP^+_{k-1}A^T+Q.$$</p><h3>Correct</h3><p class="cs-equation">$$K_k=P^-_kC^T(CP^-_kC^T+R)^{-1},$$</p><p class="cs-equation">$$\hat x^+_k=\hat x^-_k+K_k(y_k-C\hat x^-_k).$$</p><p>covariance update 可写成 $P^+=(I-KC)P^-$；数值上常用 Joseph form 提高 positive-semidefinite robustness。</p>`},
  {title:'LQG：LQR controller + Kalman estimator',html:String.raw`<p>LQG 使用</p><p class="cs-equation">$$u=-K_{LQR}\hat x_{KF}.$$</p><p>在 Gaussian / quadratic 假设下，controller 与 estimator 仍可分开最优设计，这叫 stochastic separation principle。结构上和 L11 observer-based feedback 相同，只是 $K$ 与 $L$ 都由 optimization/Riccati equations 得出。</p><div class="cs-callout"><strong>重要 caveat</strong><p>LQR 单独有漂亮 robustness properties，不代表 LQG 也自动 robust。Estimator dynamics 与 plant uncertainty 组合后，gain/phase margins 可能变差，必须重新做 robustness analysis。</p></div>`},
  {title:'Kalman filter 的学习 / 实现检查表',html:String.raw`<ol><li>先确认 $(A,C)$ detectable。</li><li>明确 $w$ 与 $v$ 分别代表什么，不要把所有误差都塞进 $R$。</li><li>给 $Q,R,P_0$ 合理单位与量级。</li><li>检查 innovation 是否有 bias / correlation。</li><li>检查 steady-state gain 与 estimator poles。</li><li>与 controller 组合后重新验证 saturation、delay、robustness。</li></ol><pre class="cs-code"><code>L, P, eigs = control.lqe(sys, QN, RN)</code></pre>`}
 ],
 practice:String.raw`<ol><li>说明 $Q$ 增大与 $R$ 增大分别怎样改变 filter 对 model/measurement 的信任。</li><li>写出 Kalman–Bucy Riccati equation，并与 LQR ARE 对照。</li><li>推导 discrete Kalman gain 的维度。</li><li>为什么 innovation 长期有非零均值通常不是“正常噪声”？</li><li>解释 LQG separation 不等于 LQG robustness。</li></ol>`
}
);