(function(){
window.unitDepth=window.unitDepth||{};
const D=window.unitDepth;
D['03']={main:{
  1:String.raw`<div class="cs-depth-block"><h3>为什么 $e^{At}$ 真的是矩阵 ODE 的解</h3><p>从定义</p><p class="cs-equation">$$e^{At}=I+At+\frac{A^2t^2}{2!}+\frac{A^3t^3}{3!}+\cdots$$</p><p>逐项微分：</p><p class="cs-equation">$$\frac d{dt}e^{At}=A+A^2t+\frac{A^3t^2}{2!}+\cdots=Ae^{At}.$$</p><p>同时 $e^{A0}=I$。因此 $x(t)=e^{At}x_0$ 同时满足 $\dot x=Ax$ 和 $x(0)=x_0$。</p><h3>可对角化时为什么计算特别容易</h3><p>若 $A=V\Lambda V^{-1}$，则 $A^k=V\Lambda^kV^{-1}$，于是整个 power series 中的 $V,V^{-1}$ 都能提出：</p><p class="cs-equation">$$e^{At}=Ve^{\Lambda t}V^{-1}.$$</p><p>真正发生的事只是：先把初始状态拆到 eigenvector coordinates，每个 mode 独立乘 $e^{\lambda_i t}$，最后再变回原坐标。</p></div>`,
  7:String.raw`<div class="cs-depth-block"><h3>Lyapunov equation 为什么能证明稳定</h3><p>取候选“能量” $V=x^TPx$，其中 $P=P^T\succ0$。沿轨迹：</p><p class="cs-equation">$$\dot V=\dot x^TPx+x^TP\dot x=x^T(A^TP+PA)x.$$</p><p>如果我们能让 $A^TP+PA=-Q$ 且 $Q\succ0$，就得到</p><p class="cs-equation">$$\dot V=-x^TQx<0\quad(x\neq0).$$</p><p>意思是：无论 state 从哪个方向出发，这个“能量”都严格下降，所以它不可能在远离原点的地方长期停留。</p><div class="cs-source-example"><span class="cs-label">Scalar sanity check</span><p>$\dot x=-2x$，取 $Q=1$。方程 $-4P=-1$ 给 $P=1/4>0$。于是 $V=x^2/4$，$\dot V=-x^2$，稳定性一眼可见。</p></div></div>`
}};

D['06']={main:{
  1:String.raw`<div class="cs-depth-block"><h3>Argument principle：为什么“绕圈”能数 roots</h3><p>把 rational function 写成</p><p class="cs-equation">$$F(s)=k\frac{\prod_i(s-z_i)}{\prod_j(s-p_j)}.$$</p><p>沿一个 closed contour 走一圈时，每个 factor $(s-z_i)$ 都贡献一个 phase change。若 zero 在 contour 内，向量 $s-z_i$ 会完整转一圈；zero 在外面则不会。pole 在 denominator，所以它的 phase contribution 符号相反。</p><p>因此总 phase change 等于 $2\pi(Z-P)$（orientation 会决定正负号 convention）。Nyquist 只是把这个 complex-analysis 结论应用到 $F(s)=1+L(s)$。</p><h3>为什么危险点从 0 变成 -1</h3><p>闭环 pole 满足 $1+L(s)=0$。argument principle 原本看 $F(s)=1+L(s)$ 是否绕原点；把整条曲线平移 -1 后，就等价于看 $L(s)$ 绕 $-1$。</p></div>`,
  2:String.raw`<div class="cs-depth-block"><h3>Nyquist 的固定做题流程</h3><ol><li>先数 open-loop RHP poles：得到 $P$。</li><li>画/判断 standard Nyquist contour 经 $L(s)$ 的 image。</li><li>数对 $-1$ 的净 encirclement $N$，严格遵守课程使用的 clockwise sign convention。</li><li>用课程公式 $Z=N+P$ 得到 closed-loop RHP poles 数。</li><li>目标是 $Z=0$。</li></ol><div class="cs-misconception"><strong>open-loop unstable 时不能只说“不要绕 -1”</strong>如果 $P>0$，为了让 $Z=0$，反而需要特定数量和方向的 encirclements。</div><p>做题时建议把 $P,N,Z$ 三个数写在图旁边，避免只凭“曲线看起来离 -1 很远”做稳定判断。</p></div>`,
  4:String.raw`<div class="cs-depth-block"><h3>Phase margin 为什么可以换算成 delay margin</h3><p>纯 delay $e^{-s\tau}$ 在 $j\omega$ 上 magnitude 恒为 1，但增加 phase $-\omega\tau$。在 gain crossover $\omega_c$，若原本 phase margin 是 $\phi_m$（用 rad），额外 delay 把 margin 吃完的近似条件是</p><p class="cs-equation">$$\omega_c\tau_{max}\approx\phi_m\quad\Rightarrow\quad \tau_{max}\approx\frac{\phi_m}{\omega_c}.$$</p><p>所以同样的 $60^\circ$ phase margin，cross-over 越高，对绝对时间延迟越敏感。这也是“追求更高 bandwidth”为什么会和 delay robustness 冲突。</p></div>`
}};

D['09']={main:{
  5:String.raw`<div class="cs-depth-block"><h3>Controllability matrix 从哪里来：先看离散时间</h3><p>对 $x_{k+1}=Ax_k+Bu_k$，从 $x_0=0$ 出发：</p><p class="cs-equation">$$x_1=Bu_0,$$</p><p class="cs-equation">$$x_2=ABu_0+Bu_1,$$</p><p class="cs-equation">$$x_3=A^2Bu_0+ABu_1+Bu_2.$$</p><p>所以 $n$ 步后的 reachable state 都是 $B,AB,\ldots,A^{n-1}B$ columns 的线性组合。若这些方向 span $\mathbb R^n$，就能组合出任意 state。</p><p>Cayley–Hamilton 保证 $A^nB,A^{n+1}B,\ldots$ 不会创造超出前 $n$ 个 matrix powers span 的全新方向，所以矩阵只需要到 $A^{n-1}B$。</p></div>`,
  6:String.raw`<div class="cs-depth-block"><h3>PBH 的 left-eigenvector 版本最直观</h3><p>假设存在 left eigenvector $w^TA=\lambda w^T$，并且 $w^TB=0$。看 modal coordinate $\eta=w^Tx$：</p><p class="cs-equation">$$\dot\eta=w^T\dot x=w^TAx+w^TBu=\lambda w^Tx=\lambda\eta.$$</p><p>input $u$ 完全消失了。也就是说，不管 actuator 怎么动作，这个 mode 都按自己的 $\lambda$ 演化，因此不可控。</p><p>这也直接解释 stabilizability：若这种不可控 mode 的 $\Re\lambda<0$，它自己会衰减，可以接受；若它在 RHP，就永远无法靠 feedback 救回来。</p></div>`,
  7:String.raw`<div class="cs-depth-block"><h3>Gramian 为什么和“最小能量”连在一起</h3><p>从 $0$ 到 $x_T$ 的约束是</p><p class="cs-equation">$$x_T=\int_0^T e^{A(T-\tau)}Bu(\tau)d\tau.$$</p><p>这是一个“选函数 $u(\tau)$ 满足线性约束，同时最小化 $\int u^Tu$”的问题。用 Lagrange multiplier 做 functional minimization，会得到最优输入形状</p><p class="cs-equation">$$u^*(t)=B^Te^{A^T(T-t)}W_c(T)^{-1}x_T.$$</p><p>最小能量为 $x_T^TW_c^{-1}x_T$。因此 Gramian 小 eigenvalue 对应 $W_c^{-1}$ 大 eigenvalue：那个 state direction 虽然可能理论上 reachable，但非常“贵”。</p></div>`
}};

D['11']={main:{
  2:String.raw`<div class="cs-depth-block"><h3>Observability matrix 为什么是 $C,CA,CA^2,\ldots$</h3><p>先看无输入系统 $\dot x=Ax,y=Cx$。在 $t=0$：</p><p class="cs-equation">$$y(0)=Cx_0.$$</p><p>再对 output 求导：</p><p class="cs-equation">$$\dot y(0)=CAx_0,\qquad \ddot y(0)=CA^2x_0,\ldots$$</p><p>把这些 measurement 信息叠起来：</p><p class="cs-equation">$$\begin{bmatrix}y(0)\\\dot y(0)\\\vdots\end{bmatrix}=\begin{bmatrix}C\\CA\\\vdots\\CA^{n-1}\end{bmatrix}x_0=\mathcal O x_0.$$</p><p>所以 $\mathcal O$ full column rank 的含义很直接：不同 initial states 不会产生完全相同的 output history。</p></div>`,
  5:String.raw`<div class="cs-depth-block"><h3>Observer error dynamics 为什么 input 会消失</h3><p>plant 和 observer 都使用同一个已知 $u$：</p><p class="cs-equation">$$\dot x=Ax+Bu,$$</p><p class="cs-equation">$$\dot{\hat x}=A\hat x+Bu+L(y-C\hat x).$$</p><p>定义 $e=x-\hat x$ 并相减：</p><p class="cs-equation">$$\dot e=A(x-\hat x)-L(Cx-C\hat x)=(A-LC)e.$$</p><p>$Bu$ 恰好抵消，因为 observer 已经知道 controller 实际发出了什么 command。observer 需要纠正的是未知 initial state、model mismatch 和 measurement information，而不是重新猜 input。</p></div>`,
  7:String.raw`<div class="cs-depth-block"><h3>Separation principle 的矩阵结构</h3><p>令 $u=-K\hat x=-K(x-e)$。用 augmented coordinates $[x^T,e^T]^T$，可以得到 block-triangular dynamics（经过合适排列）：</p><p class="cs-equation">$$\begin{bmatrix}\dot x\\\dot e\end{bmatrix}=\begin{bmatrix}A-BK&BK\\0&A-LC\end{bmatrix}\begin{bmatrix}x\\e\end{bmatrix}.$$</p><p>triangular matrix 的 eigenvalues 就是 diagonal blocks 的 eigenvalues 合集。所以 controller poles 来自 $A-BK$，observer poles 来自 $A-LC$。</p><p>这解释了“可以分开设计”的数学原因；但 noise、saturation、robustness 并不会因此自动分离。</p></div>`
}};

D['13']={main:{
  4:String.raw`<div class="cs-depth-block"><h3>用 scalar LQR 把 ARE 算到底</h3><p>考虑</p><p class="cs-equation">$$\dot x=ax+bu,\qquad J=\int_0^\infty(qx^2+ru^2)dt,$$</p><p>其中 $q\ge0,r>0$。scalar ARE 是</p><p class="cs-equation">$$0=2aP-\frac{b^2}{r}P^2+q.$$</p><p>这是普通二次方程。取使 closed-loop 稳定的正解 $P$，然后</p><p class="cs-equation">$$K=\frac{bP}{r},\qquad \dot x=(a-bK)x.$$</p><p>你可以直接看到参数方向：$q$ 增大通常推高 $P,K$，controller 更努力压 state；$r$ 增大通常降低 gain，更节省 actuator。</p><div class="cs-misconception"><strong>ARE 可能有多个 algebraic roots</strong>LQR 要的是 stabilizing solution，不是“解方程随便取一个根”。高维情况数值算法同样专门寻找 stabilizing Riccati solution。</div></div>`,
  6:String.raw`<div class="cs-depth-block"><h3>Q/R 调参先处理单位，否则数字大小会骗人</h3><p>position 以 meter、angle 以 radian、velocity 以 m/s，数值尺度完全不同。直接设 $Q=I$ 不代表“所有 states 同等重要”。一种实用起点是按允许最大偏差归一化：</p><p class="cs-equation">$$Q_{ii}\approx\frac{1}{x_{i,\max}^2},\qquad R_{jj}\approx\frac{1}{u_{j,\max}^2}.$$</p><p>这样每一项 roughly 表示“占用了允许范围的多少比例”。之后再根据 transient/control effort 调 relative weights。</p><p>看 tuning 时建议同时画 $x(t)$、$u(t)$、closed-loop poles 和两个积分代价，而不是只看一个 step response。</p></div>`
}};

D['14']={main:{
  4:String.raw`<div class="cs-depth-block"><h3>Kalman Riccati equation 的每一项在说什么</h3><p>continuous covariance dynamics</p><p class="cs-equation">$$\dot P=AP+PA^T+Q-PC^TR^{-1}CP.$$</p><ul><li>$AP+PA^T$：系统 dynamics 如何传播/拉伸已有 uncertainty。</li><li>$+Q$：process noise 不断注入新的 uncertainty。</li><li>$-PC^TR^{-1}CP$：measurement 带来信息，降低 uncertainty。</li></ul><p>所以 Riccati equation 不是神秘公式，而是在做一场持续的“不确定度预算”：model/noise 把 covariance 推大，measurement information 把它压小。</p></div>`,
  7:String.raw`<div class="cs-depth-block"><h3>Scalar Kalman update：用数字看“更信谁”</h3><p>假设预测 $\hat x^-=10$，prediction variance $P^-=4$；sensor 测得 $y=12$，measurement variance $R=1$，且 $C=1$。</p><p>Kalman gain：</p><p class="cs-equation">$$K=\frac{P^-}{P^-+R}=\frac45=0.8.$$</p><p>innovation 是 $12-10=2$，所以 posterior estimate</p><p class="cs-equation">$$\hat x^+=10+0.8\times2=11.6.$$</p><p>因为 model uncertainty 4 比 sensor uncertainty 1 大，filter 明显更靠近 measurement。posterior variance 则降为</p><p class="cs-equation">$$P^+=(1-K)P^-=0.8.$$</p><p>如果把 $R$ 改成 100，$K$ 会很小，filter 就更信 model。</p></div>`,
  8:String.raw`<div class="cs-depth-block"><h3>LQG separation 到底分开了什么、没分开什么</h3><p>LQR Riccati 用 $(A,B,Q_{cost},R_{cost})$ 设计 control gain；Kalman Riccati 用 $(A,C,Q_{noise},R_{noise})$ 设计 estimator gain。在线性高斯 assumptions 下，两者可独立求解，再令 $u=-K\hat x$。</p><p>分开的是<strong>最优设计计算和 nominal stability structure</strong>。没有分开的包括：unmodeled high-frequency dynamics、actuator saturation、sensor bias、delay、overall loop robustness。因此完成 LQG 后仍要回到 L06/L07 的 frequency-domain 检查。</p></div>`
}};
})();