(function(){
window.unitDepth=window.unitDepth||{};
window.unitDepth['02']={
  intro:String.raw`<div class="cs-depth-intro"><span class="cs-label">Deep textbook pass · L02</span><h2>这一讲真正要学会的是“同一个系统换语言”</h2><p>下面不是再做一遍摘要，而是把原 PPT 里容易被一句话带过的前提、推导和例子补出来。读法建议：先看主小节建立地图，再看这里的完整推导；每一段都尽量回答“为什么这样定义、这一步从哪里来、什么时候会失效”。</p></div>`,
  main:{
    1:String.raw`<div class="cs-depth-block"><h3>2.1A 什么叫 model？先分清 first-principles、black-box 和 grey-box</h3><p>模型的目的不是复制现实，而是保留对当前任务有用的动态关系。PPT 用一句很重要的话提醒：<em>all models are wrong, but some are useful</em>。对控制来说，“有用”通常意味着它至少能预测 controller 真正在意的频率范围、operating point 和 actuator/sensor 行为。</p><div class="cs-compare"><div><strong>First-principles</strong><p>从 Newton、Kirchhoff、能量守恒等定律开始。优点是参数有物理意义、可解释；缺点是 friction、delay、柔性模态等很难全写准。</p></div><div><strong>Black-box</strong><p>直接用实验输入输出数据拟合模型。优点是快速；缺点是训练数据没覆盖到的 operating region 可能不可靠。</p></div><div><strong>Grey-box</strong><p>保留已知物理结构，只从数据估参数。工程控制里非常常见。</p></div></div><h3>2.1B state 不是“变量越多越好”</h3><p>state 的正式直觉是：给定当前 $x(t_0)$ 和未来 input $u(t)$，未来输出就能被唯一预测。过去历史不需要再额外保存，因为过去对未来的影响已经被 state 压缩进去了。</p><div class="cs-source-example"><span class="cs-label">Cruise control</span><strong>$m\dot v=u-bv+d$</strong><p>若只关心纵向速度，一个最小 state 就是 $x=v$。位置不是必须的，因为未来速度只需要当前速度和未来驱动力；但如果输出还要求位置，就可能把 position 一起放进 state。</p></div><div class="cs-source-example"><span class="cs-label">Mass–spring–damper</span><strong>$m\ddot p+b\dot p+kp=u$</strong><p>系统必须记住 position 和 velocity，所以自然取 $x_1=p,x_2=\dot p$。只知道 position 不够：同一个位置上，向左运动和向右运动的下一刻完全不同。</p></div><h3>2.1C 从物理量到矩阵时先检查单位</h3><p>若 $x=[p,\dot p]^T$，则 $A$ 第一行把 velocity 变成 position derivative，所以对应系数 1 的单位不是“无单位直觉”，而是保证方程左右维度一致。每次建模后检查单位，是发现漏掉质量、惯量、时间常数最便宜的方法之一。</p></div>`,
    2:String.raw`<div class="cs-depth-block"><h3>2.2A 高阶 ODE → state space：完整二阶例子</h3><p>对</p><p class="cs-equation">$$m\ddot p+b\dot p+kp=u,$$</p><p>先解出最高阶导数：</p><p class="cs-equation">$$\ddot p=-\frac{k}{m}p-\frac{b}{m}\dot p+\frac{1}{m}u.$$</p><p>取 $x_1=p,x_2=\dot p$，于是</p><p class="cs-equation">$$\dot x_1=x_2,\qquad \dot x_2=-\frac{k}{m}x_1-\frac{b}{m}x_2+\frac1m u.$$</p><p>写成矩阵：</p><p class="cs-equation">$$\dot x=\begin{bmatrix}0&1\\-k/m&-b/m\end{bmatrix}x+\begin{bmatrix}0\\1/m\end{bmatrix}u.$$</p><p>如果输出是 position，$C=[1\ 0],D=0$；如果输出是 velocity，则 $C=[0\ 1]$。</p><div class="cs-misconception"><strong>常见错误</strong>先写矩阵再猜元素，最容易把符号和系数写错。稳定做法永远是：定义 states → 一行一行写 $\dot x_i$ → 最后收集矩阵。</div><h3>2.2B 为什么 state choice 不唯一</h3><p>若定义新坐标 $z=Tx$，只要 $T$ 可逆，$z$ 与 $x$ 包含完全相同的信息。物理 state 往往直观；canonical state 往往方便代数。控制理论会故意换坐标，因为“计算方便”不等于“系统改变了”。</p></div>`,
    3:String.raw`<div class="cs-depth-block"><h3>2.3A Laplace transform 到底在做什么</h3><p>one-sided Laplace transform 定义为</p><p class="cs-equation">$$F(s)=\int_0^\infty f(t)e^{-st}\,dt,\qquad s=\sigma+j\omega.$$</p><p>$e^{-\sigma t}$ 可以看成一个人为加入的衰减权重，让一些原本不绝对可积的信号也能转换。$e^{-j\omega t}$ 则负责分解频率，所以 Laplace 同时把“增长/衰减”和“振荡”装进复变量 $s$。</p><h3>2.3B 三个基本 transform 建立直觉</h3><ul><li>$\delta(t)\leftrightarrow1$：impulse 在所有频率都提供激励。</li><li>$1(t)\leftrightarrow1/s$：积分器和 step 因此会反复出现 $1/s$。</li><li>$e^{-at}\leftrightarrow1/(s+a)$：time-domain 的指数 mode 对应 s-plane 的 pole。</li></ul><h3>2.3C derivative formula 为什么带 initial condition</h3><p>integration by parts：</p><p class="cs-equation">$$\int_0^\infty \dot f(t)e^{-st}dt=\left[f(t)e^{-st}\right]_0^\infty+s\int_0^\infty f(t)e^{-st}dt=sF(s)-f(0).$$</p><p>所以“导数变成乘 $s$”只在 zero initial condition 时能直接写成 $sF(s)$。这也是 transfer function 必须强调 zero initial condition 的原因。</p><h3>2.3D Final value theorem 不能看到 $s\to0$ 就乱用</h3><p>若 $F(s)$ rational/proper，且 $sF(s)$ 的 poles 除可能在原点外都严格在 LHP，才可用</p><p class="cs-equation">$$\lim_{t\to\infty}f(t)=\lim_{s\to0}sF(s).$$</p><p>例如 $F(s)=3/[s(s-2)]$ 形式上代 $s\to0$ 会得到有限数，但真实 time response 含 $e^{2t}$ 发散；原因是 theorem 的 stability 条件不满足。</p><div class="cs-micro-check"><strong>自检</strong><p>看到 final value theorem 时，第一步不是代 $s=0$，而是先检查 $sF(s)$ 的 poles。</p></div></div>`,
    4:String.raw`<div class="cs-depth-block"><h3>2.4A State space → transfer function：把 inverse 真正算一次</h3><p>考虑</p><p class="cs-equation">$$A=\begin{bmatrix}0&1\\-2&-3\end{bmatrix},\quad B=\begin{bmatrix}0\\1\end{bmatrix},\quad C=\begin{bmatrix}1&0\end{bmatrix},\quad D=0.$$</p><p>第一步：</p><p class="cs-equation">$$sI-A=\begin{bmatrix}s&-1\\2&s+3\end{bmatrix}.$$</p><p>其 determinant 是 $s(s+3)+2=s^2+3s+2$，因此</p><p class="cs-equation">$$(sI-A)^{-1}=\frac1{s^2+3s+2}\begin{bmatrix}s+3&1\\-2&s\end{bmatrix}.$$</p><p>再乘 $B$：</p><p class="cs-equation">$$(sI-A)^{-1}B=\frac1{s^2+3s+2}\begin{bmatrix}1\\s\end{bmatrix}.$$</p><p>最后乘 $C$：</p><p class="cs-equation">$$G(s)=C(sI-A)^{-1}B=\frac1{s^2+3s+2}.$$</p><p>现在可以看到 denominator 为什么来自 $\det(sI-A)$：它编码了 internal eigenvalue structure。</p><h3>2.4B 为什么 transfer function 会丢掉内部信息</h3><p>$G(s)$ 只描述 input 到 output。如果某个 mode 既没有被 $B$ 激发，或没有被 $C$ 看见，它可能不出现在最终 transfer function 中。这就是后面 controllability / observability 和 pole-zero cancellation 会重新出现的原因。</p></div>`,
    5:String.raw`<div class="cs-depth-block"><h3>2.5A 为什么输入导数让标准 realization 变麻烦</h3><p>标准 state-space 希望右侧只依赖当前 $x$ 和 $u$，即 $\dot x=Ax+Bu$。如果原方程出现 $\dot u$，你若直接写进 state equation，就要求模型实时知道 input derivative；对 noisy/digital signal，这通常既不稳健也不必要。</p><p>对于</p><p class="cs-equation">$$y^{(3)}+3\ddot y-2\dot y+y=\dot u-2u,$$</p><p>Laplace 域可写</p><p class="cs-equation">$$Y(s)=\frac{s-2}{s^3+3s^2-2s+1}U(s).$$</p><p>引入内部变量 $V$：</p><p class="cs-equation">$$V=\frac{1}{s^3+3s^2-2s+1}U,\qquad Y=(s-2)V.$$</p><p>于是可以对 $v,\dot v,\ddot v$ 建标准状态，再通过 output equation $y=\dot v-2v$ 生成输出。关键思想是：<strong>把 differentiating input 的麻烦移到内部可实现 dynamics / output combination 中</strong>。</p><div class="cs-misconception"><strong>别把“transfer function 能写出来”当成“任何 realization 都合理”</strong>realization 还必须 causal、finite-dimensional、适合真实信号实现。</div></div>`,
    6:String.raw`<div class="cs-depth-block"><h3>2.6A Linearization 的四步固定套路</h3><ol><li>先找 operating point：解 $0=f(x_e,u_e)$。</li><li>定义 deviations：$\delta x=x-x_e,\ \delta u=u-u_e$。</li><li>算 Jacobians：$A=\partial f/\partial x|_e,\ B=\partial f/\partial u|_e$。</li><li>只保留一阶项：$\delta\dot x\approx A\delta x+B\delta u$。</li></ol><h3>2.6B 用摆的 $\sin\theta$ 看“局部”是什么意思</h3><p>假设某角度 dynamics 中包含 $\sin\theta$。在 $\theta_e=0$ 附近，</p><p class="cs-equation">$$\sin(\theta_e+\delta\theta)\approx \sin\theta_e+\cos\theta_e\,\delta\theta=\delta\theta.$$</p><p>但在 $\theta_e=\pi$ 附近，$\cos\pi=-1$，所以同一个 nonlinear term 的局部符号会反过来。于是不同 equilibria 可以有完全不同的 local stability。</p><h3>2.6C Feedforward equilibrium input + feedback correction</h3><p>实际 controller 常写成</p><p class="cs-equation">$$u=u_e+\delta u,\qquad \delta u=-K\delta x.$$</p><p>$u_e$ 负责维持目标 operating point，feedback 只管附近偏差。若忘记 $u_e$，你可能设计出一个“围绕错误 equilibrium 很稳定”的 controller。</p><div class="cs-misconception"><strong>Linearization 不是 global approximation</strong>离 equilibrium 远时二阶、三阶 Taylor terms 可能不再小；尤其 saturation、dead-zone、large-angle trigonometry 会让线性模型很快失真。</div></div>`,
    7:String.raw`<div class="cs-depth-block"><h3>2.7A Similarity transform 为什么不改变 transfer function</h3><p>采用本页约定 $z=Tx$，因此 $x=T^{-1}z$：</p><p class="cs-equation">$$\dot z=TAT^{-1}z+TBu,\qquad y=CT^{-1}z+Du.$$</p><p>新 transfer function 为</p><p class="cs-equation">$$\tilde G=C T^{-1}\big(sI-TAT^{-1}\big)^{-1}TB+D.$$</p><p>利用</p><p class="cs-equation">$$sI-TAT^{-1}=T(sI-A)T^{-1},$$</p><p>所以 inverse 是 $T(sI-A)^{-1}T^{-1}$。全部代回后 $T^{-1}T$ 逐项消掉，得到 $\tilde G=C(sI-A)^{-1}B+D=G$。</p><h3>2.7B Python 的角色：验证，不替代推导</h3><pre class="cs-code"><code>import control as ct
A = [[0, 1], [-2, -3]]
B = [[0], [1]]
C = [[1, 0]]
D = [[0]]

sys = ct.ss(A, B, C, D)
print(ct.ss2tf(sys))
# expected: 1 / (s^2 + 3 s + 2)</code></pre><p>建议学习顺序：先手推一次 $C(sI-A)^{-1}B+D$，再用软件核对。若二者不一致，优先检查 state 定义、符号和 output matrix，而不是“相信软件然后改答案”。</p></div>`
  },
  source:{
    6:String.raw`<div class="cs-depth-block"><h3>2.6A Discrete time 不是“把 t 换成 k”</h3><p>difference equation 描述 sample-to-sample evolution。例如 $x_{k+1}=0.8x_k+u_k$ 表示每一步旧 state 保留 80%，再叠加当前 input。若 $u=0$，$x_k=0.8^kx_0$，因此 $|0.8|<1$ 直接给出衰减。</p><h3>2.6B z-transform 的 shift rule 要带 initial condition 意识</h3><p>one-sided z-transform 下，严格写 shift 时会出现 initial-condition term；在定义 transfer function 的 zero-initial-condition 场景才简化成“向前一步对应乘 $z$”。所以 CT 的 Laplace derivative rule 与 DT 的 z-shift rule 在逻辑上完全平行。</p><h3>2.6C CT 与 DT 稳定区域为什么不同</h3><p>CT mode 是 $e^{st}$，要让它衰减需 $\Re(s)<0$；DT mode 是 $z^k$，要让它衰减需 $|z|<1$。采样映射 $z=e^{sT}$ 把整个 LHP 映到 unit disk 内。</p><p>L12 会再加入 sampler、zero-order hold、aliasing 和 controller discretization；这里先把“difference equation / z / unit disk”三件事连起来。</p></div>`
  }
};
})();