window.practiceEnhancements=(function(){
const W={};
const worked=(title,body,source='')=>`<div class="cs-worked"><span class="cs-label">Worked example</span><h3>${title}</h3>${body}${source?`<p class="cs-origin">题型来源：${source}；本站数值与讲解为独立改写。</p>`:''}</div>`;
const mistake=(text)=>`<div class="cs-mistake"><strong>常见错误</strong><p>${text}</p></div>`;
const lab=(title,goal,code,read)=>`<section class="cs-lab"><span class="cs-label">Python mini-lab</span><h2>${title}</h2><p>${goal}</p><pre><code>${code}</code></pre><div class="cs-lab-read"><strong>运行后看什么？</strong><p>${read}</p></div></section>`;
W.worked={
'02-2':worked('从三阶 ODE 一步步写出 state space',String.raw`<p>考虑</p><p class="cs-equation">$$y^{(3)}+3\ddot y+2\dot y+y=u.$$</p><p>我们不猜矩阵，直接按“最高阶导数决定 state 数量”的规则做。</p><ol class="cs-solution-steps"><li><strong>选 state：</strong>$x_1=y,\ x_2=\dot y,\ x_3=\ddot y$。</li><li><strong>写前两行：</strong>$\dot x_1=x_2,\ \dot x_2=x_3$。这里没有任何推导，只是定义。</li><li><strong>把原 ODE 解出最高阶导数：</strong>$y^{(3)}=-y-2\dot y-3\ddot y+u$。</li><li><strong>换成 state：</strong>$\dot x_3=-x_1-2x_2-3x_3+u$。</li><li><strong>读出矩阵：</strong>$$A=\begin{bmatrix}0&1&0\\0&0&1\\-1&-2&-3\end{bmatrix},\ B=\begin{bmatrix}0\\0\\1\end{bmatrix},\ C=\begin{bmatrix}1&0&0\end{bmatrix},\ D=0.$$</li></ol><p>检查方法也很直接：从这个 state-space 算 $C(sI-A)^{-1}B$，应当回到 $1/(s^3+3s^2+2s+1)$。</p>${mistake('不要机械地把 $[y,\dot y,\ddot y]$ 当成唯一选择。state-space 表示不唯一；重要的是这些 state 足以描述系统未来。')}`,'HS2023 Exercise 1 的 representations 题型'),
'02-5':worked('Logistic map：为什么同一个 nonlinear system 有的 equilibrium 稳、有的不稳',String.raw`<p>看离散 nonlinear system $x_{k+1}=r x_k(1-x_k)$。</p><ol class="cs-solution-steps"><li><strong>找 equilibrium：</strong>令 $x_{k+1}=x_k=x^*$，得到 $x^*=rx^*(1-x^*)$，所以 $x_1^*=0$，以及 $x_2^*=1-1/r$。</li><li><strong>线性化：</strong>$f'(x)=r-2rx$。</li><li><strong>在 $x_1^*=0$：</strong>$A_1=r$。离散系统局部稳定要求 $|A_1|<1$，所以 $0<r<1$ 时稳定。</li><li><strong>在第二个 equilibrium：</strong>$A_2=2-r$。例如 $r=0.5$ 时 $A_2=1.5$，扰动每一步都会被放大。</li></ol><p>这里最重要的不是 logistic map 本身，而是：<strong>nonlinear system 的稳定性必须围绕某个 operating point 来谈</strong>。</p>`,'HS2023 Exercise 1 的 nonlinear linearization 题型'),
'03-2':worked('Diagonalization 后，matrix exponential 其实只是三个标量指数',String.raw`<p>设 $A=V\Lambda V^{-1}$，且 $\Lambda=\operatorname{diag}(0,-1,1)$。那么</p><p class="cs-equation">$$e^{At}=V\begin{bmatrix}1&0&0\\0&e^{-t}&0\\0&0&e^t\end{bmatrix}V^{-1}.$$</p><p>不用先把所有矩阵乘完，先读物理意义：一个 mode 保持不变，一个 mode 衰减，一个 mode 指数增长。只要初始状态在 unstable eigenvector 上有任何非零投影，最终就会被 $e^t$ 项支配。</p><div class="cs-plain-language"><span class="cs-label">讲人话</span><p>$V^{-1}x_0$ 只是把初始状态拆成“每个 mode 各占多少”；中间的 diagonal matrix 让每个 mode 各自乘上自己的指数；最后 $V$ 再把它们拼回原坐标。</p></div>`,'HS2023 Exercise 2 的 modal solution 题型'),
'04-4':worked('手画 Bode：先拆成积木，再一块块叠',String.raw`<p>考虑</p><p class="cs-equation">$$G(s)=\frac{1+0.1s}{s(s+1)(1+0.02s)^2}.$$</p><p>先改写 corner frequencies：</p><p class="cs-equation">$$1+0.1s=1+s/10,\qquad 1+0.02s=1+s/50.$$</p><ol class="cs-solution-steps"><li>$1/s$ 从一开始就是 $-20$ dB/dec，phase $-90^\circ$。</li><li>$s+1$ 在 $\omega=1$ 后再加 $-20$ dB/dec。</li><li>zero 在 $\omega=10$ 后加回 $+20$ dB/dec。</li><li>两个 pole 在 $\omega=50$ 后共加 $-40$ dB/dec。</li></ol><p>所以 slope 依次大致是 $-20\to-40\to-20\to-60$ dB/dec。phase 也按相同顺序叠加。</p>${mistake('Bode 图不是“每个 corner 处突然跳相位”。真实 phase transition 通常跨大约两个 decade；手画 asymptote 只是近似。')}`,'HS2023 Exercise 3 的 Bode plot 题型'),
'05-5':worked('为什么 P 不能稳定，但 PD 可以',String.raw`<p>plant 取 $G(s)=1/[(s+1)(s-2)]$。P controller $K(s)=k$ 时，characteristic equation 是</p><p class="cs-equation">$$(s+1)(s-2)+k=0\Rightarrow s^2-s+(k-2)=0.$$</p><p>二阶稳定多项式需要 $s$ 的系数为正，但这里系数永远是 $-1$，所以无论怎么调 $k$ 都不可能稳定。</p><p>加入 PD：$K(s)=k(1+s/3)$，characteristic polynomial 变成</p><p class="cs-equation">$$s^2+\left(-1+\frac{k}{3}\right)s+(k-2).$$</p><p>现在两个系数都能被 $k$ 改变。要求它们都正：</p><p class="cs-equation">$$k>3,\qquad k>2,$$</p><p>所以 $k>3$ 就能进入稳定区。<strong>D 项真正做的事，是给 characteristic polynomial 多一个可调系数。</strong></p>`,'HS2023 Exercise 4 的 PD stabilization 题型'),
'06-2':worked('Nyquist 的稳定范围：先找穿过负实轴的位置',String.raw`<p>以 $L(s)=1/(s+1)^3$ 为例。令 $s=j\omega$。它的 phase 是</p><p class="cs-equation">$$\angle L(j\omega)=-3\arctan\omega.$$</p><p>Nyquist 曲线到达 $-180^\circ$ 时：</p><p class="cs-equation">$$3\arctan\omega=180^\circ\Rightarrow \omega=\tan60^\circ=\sqrt3.$$</p><p>该频率的 magnitude 为</p><p class="cs-equation">$$|L|=\frac{1}{(\sqrt{1+\omega^2})^3}=\frac1{2^3}=\frac18.$$</p><p>乘上 proportional gain $k$ 后，负实轴交点是 $-k/8$。open-loop 没有 RHP poles，所以临界情况是交点正好到 $-1$：$k=8$。因此 $0<k<8$ 对应稳定闭环。</p><p>这也直接给出 gain margin：当 $k=1$ 时还能再放大 8 倍。</p>`,'HS2023 Exercise 5 的 Nyquist / margin 题型'),
'07-2':worked('Lead compensator：从缺少 35° phase margin 开始设计',String.raw`<p>假设你希望新的 cross-over 在 $\omega_c=5$ rad/s，但 plant 在这里的 phase 只有 $-170^\circ$。若目标 PM 是 $45^\circ$，理想 open-loop phase 应约为 $-135^\circ$，因此至少需要约 $35^\circ$ phase lead。</p><ol class="cs-solution-steps"><li>留一点设计余量，取 $\phi_{max}=40^\circ$。</li><li>lead 形式 $K_{lead}=\frac{Ts+1}{\alpha Ts+1},\ 0<\alpha<1$，满足 $\sin\phi_{max}=(1-\alpha)/(1+\alpha)$。</li><li>因此 $\alpha=(1-\sin40^\circ)/(1+\sin40^\circ)\approx0.217$。</li><li>令最大 phase boost 出现在 $\omega_c$：$\omega_c=1/(T\sqrt\alpha)$，得到 $T\approx0.43$ s。</li><li>最后再用一个 scalar gain 把 $|KG|$ 在 $5$ rad/s 调到 1。</li></ol>${mistake('不要先随便选一个 zero 再看 phase margin。lead 设计的顺序应从“缺多少 phase”反推 $\alpha,T$。')}`,'HS2023 Exercise 6 / frequency-domain design 的典型能力'),
'08-6':worked('Anti-windup：为什么解除饱和后还会冲过头',String.raw`<p>假设 PI controller 要求 $u_c=18$，但 actuator 上限只有 $u_{max}=10$。真实 plant 只收到 $u=10$，可 error 仍然存在，integrator 继续累积。</p><p>如果 3 秒后 error 已经变成负值，但 integrator state 仍很大，controller command 可能还是 $u_c>10$。于是 actuator 继续卡在上限，系统还在朝错误方向走。</p><p>back-calculation 加入</p><p class="cs-equation">$$\dot x_I=e+K_a(u-u_c).$$</p><p>此时 $u-u_c=-8$，第二项会主动把 integrator state 拉回来。未饱和时 $u=u_c$，这条额外 feedback 自动消失。</p><div class="cs-plain-language"><span class="cs-label">一句话</span><p>anti-windup 是让 controller 知道：“你想输出 18，但 actuator 实际只做了 10，别再假装命令被执行了。”</p></div>`,'HS2023 augmented architectures / anti-windup 题型'),
'09-4':worked('一个 actuator 为什么能控制 position 和 velocity 两个 states',String.raw`<p>double integrator：</p><p class="cs-equation">$$A=\begin{bmatrix}0&1\\0&0\end{bmatrix},\qquad B=\begin{bmatrix}0\\1\end{bmatrix}.$$</p><p>$B$ 表示 input 立刻只改变 velocity 方向。再看</p><p class="cs-equation">$$AB=\begin{bmatrix}1\\0\end{bmatrix}.$$</p><p>dynamics 会把 velocity 的变化“传播”到 position。于是</p><p class="cs-equation">$$W_c=[B\ AB]=\begin{bmatrix}0&1\\1&0\end{bmatrix},\quad \operatorname{rank}W_c=2.$$</p><p>所以虽然只有一个 actuator，它通过系统 dynamics 间接影响了第二个 state direction。</p>${mistake('“输入个数少于 state 个数”不代表不可控。关键不是 actuator 数量，而是 $B,AB,A^2B,\ldots$ 能否张成整个 state space。')}`,'HS2023 Exercise 8 的 controllability 题型'),
'10-3':worked('Pole placement：把 −2 和 −4 放进 closed loop',String.raw`<p>考虑 controllable canonical form</p><p class="cs-equation">$$A=\begin{bmatrix}0&1\\-c_1&-c_2\end{bmatrix},\quad B=\begin{bmatrix}0\\1\end{bmatrix},\quad u=-[k_1\ k_2]x.$$</p><p>closed-loop matrix 为</p><p class="cs-equation">$$A-BK=\begin{bmatrix}0&1\\-(c_1+k_1)&-(c_2+k_2)\end{bmatrix}.$$</p><p>它的 characteristic polynomial 是</p><p class="cs-equation">$$s^2+(c_2+k_2)s+(c_1+k_1).$$</p><p>目标 poles $-2,-4$ 对应 $(s+2)(s+4)=s^2+6s+8$。逐项比较即可：</p><p class="cs-equation">$$k_2=6-c_2,\qquad k_1=8-c_1.$$</p><p>这就是 canonical form 强大的地方：pole placement 几乎变成“对系数”。</p>`,'HS2023 Exercise 9 的 state-feedback 题型'),
'11-5':worked('Observer gain：为什么 observer poles 通常放得更快',String.raw`<p>考虑</p><p class="cs-equation">$$A=\begin{bmatrix}0&1\\0&-10\end{bmatrix},\qquad C=\begin{bmatrix}1&0\end{bmatrix},\qquad L=\begin{bmatrix}l_1\\l_2\end{bmatrix}.$$</p><p>error matrix：</p><p class="cs-equation">$$A-LC=\begin{bmatrix}-l_1&1\\-l_2&-10\end{bmatrix}.$$</p><p>若希望 observer poles 都在 $-40$，目标 polynomial 是 $(s+40)^2=s^2+80s+1600$。实际 characteristic polynomial 是</p><p class="cs-equation">$$s^2+(10+l_1)s+(10l_1+l_2).$$</p><p>比较系数：</p><p class="cs-equation">$$l_1=70,\qquad l_2=900.$$</p><p>observer 很快意味着 estimation error 很快消失；但 gain 太大也会把 measurement noise 放大，这就是后面 Kalman filter 要解决的 trade-off。</p>`,'HS2023 Exercise 10 的 observer-design 题型'),
'12-2':worked('Difference equation → transfer function → 稳定性',String.raw`<p>考虑独立改写的二阶差分方程</p><p class="cs-equation">$$y[k]-1.2y[k-1]+0.32y[k-2]=u[k-1].$$</p><ol class="cs-solution-steps"><li>zero initial condition 下做 Z-transform：$Y-1.2z^{-1}Y+0.32z^{-2}Y=z^{-1}U$。</li><li>所以 $$P(z)=\frac{Y}{U}=\frac{z^{-1}}{1-1.2z^{-1}+0.32z^{-2}}=\frac{z}{z^2-1.2z+0.32}.$$</li><li>denominator factor 为 $(z-0.8)(z-0.4)$。</li><li>两个 poles 都在 unit circle 内，因此 BIBO stable。</li></ol><p>数字控制里最重要的翻译规则就是：连续时间看 LHP，离散时间看 unit circle。</p>`,'HS2023 Exercise 11 的 discrete-model 题型'),
'13-3':worked('Scalar LQR 手算：unstable plant 也能从 Riccati 得到 stabilizing gain',String.raw`<p>取 scalar system $\dot x=6x+2u$，cost 为 $J=\int_0^\infty(Qx^2+Ru^2)dt$。</p><p>CARE 在 scalar 情况是</p><p class="cs-equation">$$0=2AP-\frac{B^2}{R}P^2+Q=12P-\frac4R P^2+Q.$$</p><p>整理成二次方程：</p><p class="cs-equation">$$4P^2-12RP-QR=0.$$</p><p>取正的 stabilizing solution：</p><p class="cs-equation">$$P=\frac{12R+\sqrt{144R^2+16QR}}{8}.$$</p><p>LQR gain 为 $K=R^{-1}BP=2P/R$，closed-loop pole 是 $6-2K$。例如 $Q=R=1$ 时，$P\approx3.081$、$K\approx6.162$，closed-loop pole 约 $-6.324$，原本 unstable 的 $+6$ 被拉进 LHP。</p>${mistake('CARE 往往有多个代数解，但 LQR 要选 stabilizing positive-semidefinite solution，不是“随便一个 root”。')}`,'HS2023 Exercise 12 的 hand LQR 题型'),
'14-3':worked('Matterhorn sensor fusion：模型和 GPS 各信多少？',String.raw`<p>把高度和垂直速度作为 state：</p><p class="cs-equation">$$x=\begin{bmatrix}z\\v\end{bmatrix},\qquad \dot x=\begin{bmatrix}0&1\\0&0\end{bmatrix}x+\begin{bmatrix}0\\1\end{bmatrix}a+w.$$</p><p>GPS 直接量高度：</p><p class="cs-equation">$$y=\begin{bmatrix}1&0\end{bmatrix}x+v_{gps}.$$</p><p>accelerometer 给的是 input $a$，但它有 bias/noise，所以 process covariance $Q$ 告诉 filter：“我用 acceleration 往前推时有多不放心”；GPS covariance $R$ 告诉 filter：“新高度测量有多不放心”。</p><ul><li>若 $R$ 很大：GPS 很吵，Kalman gain 变小，估计更信 model prediction。</li><li>若 $R$ 很小：GPS 很准，Kalman gain 变大，每次 measurement 都强力纠正 prediction。</li><li>若 $Q$ 变大：model 更不可信，filter 会更积极地利用 measurement。</li></ul><p>这比死记 $L=PC^TR^{-1}$ 更重要：<strong>Kalman gain 是“不确定度换出来的信任权重”。</strong></p>`,'HS2023 Exercise 13 的 Matterhorn sensor-fusion 场景')
};
W.labs={
'02':lab('L02 Lab · 在 Python 中互转 transfer function / state space','用同一个系统验证“两种表示只是两种语言”。',`import control as ct\n\ns = ct.TransferFunction.s\nG = 1/(s**3 + 3*s**2 + 2*s + 1)\nss = ct.ss(G)\nprint(ss)\nprint(ct.tf(ss))`,`最后打印出的 transfer function 应与原来的 G 等价。再改动 state-space 坐标，你会看到 A/B/C 变了，但 transfer function 不变。`),
'03':lab('L03 Lab · 看见 stable / unstable mode','画三个 scalar modes，直观看 eigenvalue 的实部。',`import numpy as np\nimport matplotlib.pyplot as plt\n\nt = np.linspace(0, 5, 400)\nfor lam in [-1, 0, 0.6]:\n    plt.plot(t, np.exp(lam*t), label=f"lambda={lam}")\nplt.xlabel("t")\nplt.ylabel("e^(lambda t)")\nplt.legend()\nplt.grid(True)\nplt.show()`,`负 eigenvalue 衰减到 0；0 对应常数 mode；正 eigenvalue 指数增长。矩阵系统只是这些 modes 的线性组合。`),
'04':lab('L04 Lab · 自己画 Bode 并读 corner','验证手画 asymptote 与真实曲线的区别。',`import control as ct\nimport matplotlib.pyplot as plt\n\ns = ct.TransferFunction.s\nG = (1+0.1*s)/(s*(s+1)*(1+0.02*s)**2)\nct.bode_plot(G, dB=True, grid=True)\nplt.show()`,`找出约 1、10、50 rad/s 的 corner；观察 magnitude slope 如何改变，并注意 phase transition 不是瞬间发生。`),
'05':lab('L05 Lab · P vs PD 的 root locus','验证“P 永远不稳，PD 可以稳定”。',`import control as ct\nimport matplotlib.pyplot as plt\n\ns = ct.TransferFunction.s\nG = 1/((s+1)*(s-2))\nct.root_locus(G, grid=True)\nplt.show()\n\nKpd = 1 + s/3\nct.root_locus(Kpd*G, grid=True)\nplt.show()`,`第一张图的 locus 无法把两根都留在 LHP；第二张图因为加入 zero，轨迹形状被改变，存在稳定 gain 区间。`),
'06':lab('L06 Lab · Nyquist、gain margin、phase margin 一起看','把稳定边界和 margins 联系起来。',`import control as ct\nimport matplotlib.pyplot as plt\n\ns = ct.TransferFunction.s\nL = 1/(s+1)**3\nprint(ct.margin(L))\nct.nyquist_plot(L)\nplt.show()`,`margin() 给出的 gain margin 应接近 8。再把 L 乘 4、8、10，观察 Nyquist 曲线与 -1 的相对位置。`),
'09':lab('L09 Lab · controllability 不是看 B 有几列','比较两个系统的 controllability rank。',`import numpy as np\nimport control as ct\n\nA = np.array([[0.,1.],[0.,0.]])\nB = np.array([[0.],[1.]])\nWc = ct.ctrb(A,B)\nprint(Wc)\nprint("rank =", np.linalg.matrix_rank(Wc))\n\nB_bad = np.array([[1.],[0.]])\nprint("bad rank =", np.linalg.matrix_rank(ct.ctrb(A,B_bad)))`,`第一个系统只有一个 input 但 rank=2；第二个 input 的作用方向无法经 A 传播到另一个 state，因此 rank 会下降。`),
'10':lab('L10 Lab · pole placement 后直接检查 eigenvalues','不要相信自己手算，设计后一定 read-back。',`import numpy as np\nimport control as ct\n\nA = np.array([[0.,1.],[-2.,-1.]])\nB = np.array([[0.],[1.]])\nK = ct.place(A,B,[-2,-4])\nprint("K =", K)\nprint("closed-loop poles =", np.linalg.eigvals(A-B@K))`,`输出 poles 应正好在 -2 和 -4。接着把目标改成 -10,-20，比较 gain 大小，体会“更快 poles = 更大 control effort”。`),
'11':lab('L11 Lab · observer poles 越快越好吗？','先用 pole placement 得到 L，再观察 noise amplification 的趋势。',`import numpy as np\nimport control as ct\n\nA = np.array([[0.,1.],[0.,-10.]])\nC = np.array([[1.,0.]])\nL = ct.place(A.T, C.T, [-40,-40]).T\nprint("L =", L)\nprint("observer poles =", np.linalg.eigvals(A-L@C))`,`把目标从 -20,-20 改到 -100,-100，你会看到 L 急剧变大。实际 noisy sensor 下，这通常意味着 correction channel 更敏感。`),
'12':lab('L12 Lab · ZOH discretization','看 sampling time 如何改变离散 poles。',`import control as ct\n\ns = ct.TransferFunction.s\nG = 1/(s+1)\nfor T in [0.05, 0.2, 1.0]:\n    Gd = ct.c2d(G, T, method='zoh')\n    print(T, ct.poles(Gd))`,`continuous pole -1 会映射到 z=e^{-T}。T 越大，sample-to-sample pole 越靠近 0，但别把这误解成“采样越慢越好”：delay/aliasing 会恶化闭环。`),
'13':lab('L13 Lab · 改 Q/R 看 LQR 变得多激进','把“state 很贵 / actuator 很贵”变成可见的 gain 变化。',`import numpy as np\nimport control as ct\n\nA = np.array([[0.,1.],[0.,0.]])\nB = np.array([[0.],[1.]])\nfor q in [0.1, 1, 10, 100]:\n    Q = np.diag([q,1.])\n    R = np.array([[1.]])\n    K, P, poles = ct.lqr(A,B,Q,R)\n    print("q=", q, "K=", K, "poles=", poles)`,`随着 position weight q 变大，controller 通常会更积极地压 position error，gain 和 closed-loop bandwidth 都会上升。`),
'14':lab('L14 Lab · measurement 越准，Kalman gain 越大','用 lqe 比较不同 measurement noise。',`import numpy as np\nimport control as ct\n\nA = np.diag([-2.,-2.])\nG = np.eye(2)\nC = np.diag([1.,2.])\nQ = np.eye(2)\nfor r in [1e3, 1., 1e-4]:\n    R = r*np.eye(2)\n    L, P, poles = ct.lqe(A,G,C,Q,R)\n    print("R scale=", r)\n    print("L=", L)\n    print("poles=", poles)`,`R 很大时 L 会很小，filter 更信 model；R 很小时 L 变大，observer error poles 往左移动，filter 更快跟随 measurement。`)
};
return W;
})();
