(function attachExtraRlQuestions(root) {
"use strict";

const REPO = "https://github.com/walkinglabs/hands-on-modern-rl/blob/main";

const SOURCE = Object.freeze({
  mdp: `${REPO}/docs/chapter03_mdp/mdp.md`,
  mcTd: `${REPO}/docs/chapter03_mdp/dp-mc-td.md`,
  dqn: `${REPO}/docs/chapter07_dqn/dqn-components.md`,
  dqnFamily: `${REPO}/docs/chapter07_dqn/dqn-family.md`,
  reinforce: `${REPO}/docs/chapter08_policy_gradient/reinforce.md`,
  policyExploration: `${REPO}/docs/chapter08_policy_gradient/pg-necessity.md`,
  actorCritic: `${REPO}/docs/chapter09_actor_critic/actor-critic.md`,
  critic: `${REPO}/docs/chapter09_actor_critic/critic-training.md`,
  ppo: `${REPO}/docs/chapter10_ppo/trust-region-clipping.md`,
  ppoMath: `${REPO}/docs/chapter10_ppo/ppo-math.md`,
  gae: `${REPO}/docs/chapter10_ppo/gae-reward-model.md`,
  offline: `${REPO}/docs/chapter12_offline_rl/offline-data-distribution-shift.md`,
  decisionTransformer: `${REPO}/docs/chapter12_offline_rl/sequence-modeling.md`,
  rlhf: `${REPO}/docs/chapter15_rlhf/standard-rlhf-pipeline.md`,
  dpo: `${REPO}/docs/chapter17_dpo/dpo-objective-derivation.md`,
  grpo: `${REPO}/docs/chapter18_grpo/grpo-practice-and-mechanism.md`,
  rlvr: `${REPO}/docs/chapter18_grpo/rlvr.md`,
  agentCredit: `${REPO}/docs/chapter22_agentic/credit-assignment.md`,
  agentTools: `${REPO}/docs/chapter22_agentic/tool-use-and-trajectory.md`,
  failures: `${REPO}/docs/chapter30_alignment_failures/classical-failures.md`,
  evaluation: `${REPO}/docs/chapter30_alignment_failures/rl-evaluation.md`,
});

const RL_EXTRA_QUESTIONS = [
  {
    id: "rlx-mdp-markov-sufficient",
    prompt: "MDP 的马尔可夫性要求：给定当前状态 s 和动作 a 后，下一状态的分布不再依赖什么？",
    options: ["奖励的计量单位", "策略网络的层数", "更早的完整历史", "折扣因子的符号"],
    answer: 2,
    explanation: "若状态足够完整，给定当前状态和动作后，预测下一状态不必再查看更早的历史。",
    sourceUrl: SOURCE.mdp,
  },
  {
    id: "rlx-mdp-transition-vs-policy",
    prompt: "在 MDP 中，P(s'|s,a) 与策略 π(a|s) 的分工分别是什么？",
    options: ["P 描述环境怎样转移，π 描述智能体怎样选动作", "P 选择动作，π 计算奖励", "两者都只描述奖励", "两者是同一个概率分布"],
    answer: 0,
    explanation: "转移核 P 是环境动力学；策略 π 是智能体在状态下选择动作的分布。",
    sourceUrl: SOURCE.mdp,
  },
  {
    id: "rlx-mdp-terminal-target",
    prompt: "在真正的终止状态上，DQN 的 TD target 应该怎样处理未来价值？",
    options: ["加两次未来价值", "改用当前 Q 值", "保留 γmax Q(s',a')", "将未来项清零，target 只剩即时奖励"],
    answer: 3,
    explanation: "终止标记 d=1 时，(1-d) 会把未来价值清零，避免从 episode 之外继续自举。",
    sourceUrl: SOURCE.dqn,
  },
  {
    id: "rlx-mdp-hidden-velocity",
    prompt: "若 CartPole 的观测遗漏了杆子的角速度，最可能破坏哪项建模条件？",
    options: ["动作空间必须连续", "当前观测可能不再满足马尔可夫性", "奖励必须非负", "策略必须是确定性的"],
    answer: 1,
    explanation: "相同角度但不同角速度会产生不同后继状态；遗漏角速度会使当前观测不足以预测未来。",
    sourceUrl: SOURCE.mdp,
  },

  {
    id: "rlx-dp-known-model",
    prompt: "动态规划（DP）能够直接展开 Bellman 期望更新，关键前提是什么？",
    options: ["每个 episode 都无限长", "已知环境的转移概率与期望奖励", "只存在一个动作", "不能使用折扣因子"],
    answer: 1,
    explanation: "DP 依赖已知环境模型；MC 与 TD 则可以只从采样交互中学习。",
    sourceUrl: SOURCE.mcTd,
  },
  {
    id: "rlx-mc-update-target",
    prompt: "蒙特卡洛价值估计通常用什么作为状态的更新目标？",
    options: ["下一状态当前估值", "随机初始化值", "只用即时奖励", "episode 结束后得到的完整回报"],
    answer: 3,
    explanation: "MC 等轨迹结束后计算完整回报 Gₜ，因此目标通常无偏，但方差较高。",
    sourceUrl: SOURCE.mcTd,
  },
  {
    id: "rlx-td-error-formula",
    prompt: "对非终止转移，状态价值的单步 TD error δ 应写成哪一项？",
    options: ["r + γV(s') - V(s)", "V(s) + V(s')", "r - γV(s') + V(s)", "γr - V(s')"],
    answer: 0,
    explanation: "TD error 是一步 Bellman 目标 r+γV(s') 与当前预测 V(s) 的差。",
    sourceUrl: SOURCE.mcTd,
  },
  {
    id: "rlx-td-bootstrap-tradeoff",
    prompt: "TD 使用自举目标而不是完整 MC 回报，典型的偏差—方差变化是什么？",
    options: ["偏差和方差都必然为零", "方差更高且没有偏差", "更新更及时、方差较低，但会引入估计偏差", "只能在已知模型时使用"],
    answer: 2,
    explanation: "自举可一步一更新并降低方差，但下一状态价值本身是估计值，因此会引入偏差。",
    sourceUrl: SOURCE.mcTd,
  },

  {
    id: "rlx-double-dqn-split",
    prompt: "Double DQN 计算下一状态目标时，哪种网络分工是正确的？",
    options: ["两个网络都只选动作", "目标网络选动作，在线网络只算奖励", "在线网络和目标网络必须参数完全相同", "在线网络选动作，目标网络评估该动作"],
    answer: 3,
    explanation: "Double DQN 把 argmax 选择与价值评估分开，以缓解最大化导致的过估计。",
    sourceUrl: SOURCE.dqnFamily,
  },
  {
    id: "rlx-dueling-identifiability",
    prompt: "Dueling DQN 合成 Q(s,a) 时减去各动作优势的均值，主要解决什么问题？",
    options: ["让所有 Q 值恒为零", "把离散动作变成连续动作", "固定优势的基准，避免 V 与 A 的分解不唯一", "取消状态价值分支"],
    answer: 2,
    explanation: "若直接令 Q=V+A，常数可在 V 与 A 之间任意搬移；优势中心化可固定这一分解。",
    sourceUrl: SOURCE.dqnFamily,
  },
  {
    id: "rlx-per-importance-weights",
    prompt: "优先经验回放（PER）提高大 TD error 样本的采样率后，为什么还要使用重要性采样权重？",
    options: ["使回放池永久不淘汰样本", "修正非均匀采样给学习更新带来的偏差", "保证每条经验只用一次", "把目标网络变成在线网络"],
    answer: 1,
    explanation: "优先采样改变了数据分布，重要性权重用于补偿这种非均匀采样偏差。",
    sourceUrl: SOURCE.dqnFamily,
  },
  {
    id: "rlx-deadly-triad",
    prompt: "深度价值学习中的“致命三要素”通常指哪一组？",
    options: ["函数逼近、自举、off-policy 学习", "监督学习、数据增强、早停", "策略梯度、熵奖励、并行环境", "状态、动作、奖励"],
    answer: 0,
    explanation: "函数逼近、自举与 off-policy 学习同时出现时，价值训练可能变得非常不稳定。",
    sourceUrl: SOURCE.dqn,
  },

  {
    id: "rlx-pg-log-derivative",
    prompt: "策略梯度推导中使用 log-derivative trick 的直接作用是什么？",
    options: ["把概率梯度写成概率乘以 log 概率梯度，便于采样估计", "让环境转移变成可训练参数", "保证回报没有方差", "把随机策略变成贪心策略"],
    answer: 0,
    explanation: "恒等式 ∇π=π∇logπ 让期望梯度可由采样轨迹上的 ∇logπ·G 来估计。",
    sourceUrl: SOURCE.reinforce,
  },
  {
    id: "rlx-pg-continuous-policy",
    prompt: "策略梯度处理一维连续动作时，Actor 常输出什么来定义动作分布？",
    options: ["每个离散动作的 Q 表", "唯一固定动作", "高斯分布的均值与标准差", "环境的转移矩阵"],
    answer: 2,
    explanation: "连续控制中常用高斯策略，网络输出 μ 和 σ，再从分布中采样动作。",
    sourceUrl: SOURCE.reinforce,
  },
  {
    id: "rlx-reinforce-on-policy-data",
    prompt: "为什么朴素 REINFORCE 不能像 DQN 那样长期反复使用很旧的轨迹？",
    options: ["旧轨迹不含状态", "它是 on-policy 方法，旧数据来自不同策略分布", "策略梯度不使用奖励", "旧轨迹一定比新轨迹短"],
    answer: 1,
    explanation: "REINFORCE 的估计假设轨迹由当前策略采样；策略变化后，旧轨迹会产生分布错配。",
    sourceUrl: SOURCE.reinforce,
  },
  {
    id: "rlx-policy-stochastic-exploration",
    prompt: "相较于纯 argmax 的价值策略，随机策略为何天然带有探索能力？",
    options: ["它会删除低概率动作", "它始终均匀随机", "它不需要状态输入", "非最优动作只要概率非零就仍可能被采样"],
    answer: 3,
    explanation: "策略网络输出动作概率分布；未占最高概率的动作仍有机会被尝试。",
    sourceUrl: SOURCE.policyExploration,
  },

  {
    id: "rlx-ac-actor-signal",
    prompt: "一步 Actor-Critic 中，Actor 的 log-probability 通常由什么信号加权？",
    options: ["回放池容量", "网络参数总量", "TD error（作为一步优势估计）", "环境状态维度"],
    answer: 2,
    explanation: "Critic 给出的 TD error 近似优势，正值提高该动作概率，负值降低它。",
    sourceUrl: SOURCE.actorCritic,
  },
  {
    id: "rlx-ac-detach-advantage",
    prompt: "实现 Actor-Critic 时，Actor loss 中常对 TD error 调用 detach，目的是什么？",
    options: ["删除这条经验", "把优势当常量，阻止 Actor loss 反向更新 Critic", "把随机动作固定下来", "停止 Actor 自身的梯度"],
    answer: 1,
    explanation: "Actor 应依据 Critic 的评估更新策略，但这条 Actor 梯度不应穿过优势信号改动 Critic。",
    sourceUrl: SOURCE.actorCritic,
  },
  {
    id: "rlx-critic-learning-target",
    prompt: "一步 TD 训练 Critic 时，价值网络 V(s) 应主要逼近什么？",
    options: ["策略熵", "动作概率之和", "上一轮的 Actor loss", "r + γV(s') 构成的 TD 目标"],
    answer: 3,
    explanation: "Critic 最小化当前价值预测与一步 Bellman 目标之间的误差。",
    sourceUrl: SOURCE.critic,
  },

  {
    id: "rlx-ppo-pessimistic-min",
    prompt: "PPO-Clip 目标对未裁剪项与裁剪项取 min，主要表达什么原则？",
    options: ["采用更保守的改进估计，阻止策略从过大比率中获益", "总选择概率最大的动作", "把所有优势改成正数", "保证 KL 散度严格为零"],
    answer: 0,
    explanation: "min 形成悲观代理目标；当变化越过安全区间时，不再奖励继续放大这次更新。",
    sourceUrl: SOURCE.ppo,
  },
  {
    id: "rlx-gae-lambda-zero",
    prompt: "在 GAE 中将 λ 设为 0，会退化成哪种优势估计？",
    options: ["完整 MC 回报", "单步 TD error", "均匀随机优势", "只保留终点奖励且不折扣"],
    answer: 1,
    explanation: "λ=0 时所有后续 TD error 权重归零，只留下当前一步 δₜ。",
    sourceUrl: SOURCE.gae,
  },
  {
    id: "rlx-gae-weighted-residuals",
    prompt: "GAE 的优势估计本质上怎样组合一串 TD error？",
    options: ["按 (γλ)^k 对未来 TD error 做指数加权求和", "只取绝对值最大的 TD error", "把所有 TD error 等权相乘", "先打乱再取中位数"],
    answer: 0,
    explanation: "GAE 用 (γλ)^k 衰减更远的 TD error，在 TD 的低方差与 MC 的低偏差之间插值。",
    sourceUrl: SOURCE.gae,
  },
  {
    id: "rlx-ppo-fixed-old-policy",
    prompt: "PPO 对同一批 rollout 做多个训练 epoch 时，分母中的 old log-probability 应怎样处理？",
    options: ["每个 mini-batch 随机重置", "随新策略同步更新", "保持为采样时旧策略的固定记录", "改成 Critic 的价值预测"],
    answer: 2,
    explanation: "策略比率必须始终相对采样数据的旧策略计算，否则比率失去明确基准。",
    sourceUrl: SOURCE.ppoMath,
  },

  {
    id: "rlx-offline-no-feedback-channel",
    prompt: "离线 RL 相比使用 replay buffer 的在线 RL，最关键的额外限制是什么？",
    options: ["不能使用神经网络", "不能包含低回报轨迹", "只能处理离散动作", "训练期间不能再与环境交互来修正新策略"],
    answer: 3,
    explanation: "离线 RL 只能依赖固定数据集；策略进入数据未覆盖区域时，无法靠新交互及时纠错。",
    sourceUrl: SOURCE.offline,
  },
  {
    id: "rlx-cql-conservative-values",
    prompt: "CQL 缓解离线 RL 外推误差的核心做法是什么？",
    options: ["奖励所有数据集外动作", "删除行为数据中的高回报样本", "让策略总选随机动作", "主动压低数据集外动作的 Q 值"],
    answer: 3,
    explanation: "CQL 对缺少数据支撑的动作保持悲观，降低 max 操作选中虚假高价值动作的风险。",
    sourceUrl: SOURCE.offline,
  },
  {
    id: "rlx-decision-transformer-conditioning",
    prompt: "Decision Transformer 主要把离线 RL 改写成哪种学习问题？",
    options: ["无条件预测下一个状态", "以目标 return-to-go 和历史为条件预测动作的序列建模", "在线求解环境转移矩阵", "只拟合一个 Q 值表"],
    answer: 1,
    explanation: "DT 将 RTG、状态和动作排成序列，以期望回报为条件直接预测动作，不做 Bellman 更新。",
    sourceUrl: SOURCE.decisionTransformer,
  },

  {
    id: "rlx-rlhf-three-stages",
    prompt: "标准 RLHF 管线最典型的三阶段顺序是？",
    options: ["SFT → 奖励模型 → PPO 策略优化", "PPO → 随机初始化 → SFT", "奖励模型 → 删除偏好数据 → 预训练", "只训练一个分类器"],
    answer: 0,
    explanation: "标准流程先监督微调，再从偏好比较训练奖励模型，最后用 PPO 优化策略。",
    sourceUrl: SOURCE.rlhf,
  },
  {
    id: "rlx-dpo-reference-ratio",
    prompt: "DPO 为什么比较策略相对参考模型的 chosen/rejected 概率比，而不只提高 chosen 的绝对概率？",
    options: ["为了让参考模型也参与梯度更新", "为了保证 chosen 回答总是更短", "用参考模型作锚，衡量训练带来的相对变化并限制分布漂移", "为了取消偏好对中的 rejected 回答"],
    answer: 2,
    explanation: "参考模型提供训练前基准；DPO 拉大 chosen 与 rejected 的相对改变量，而不是无约束地追逐绝对概率。",
    sourceUrl: SOURCE.dpo,
  },
  {
    id: "rlx-grpo-zero-group-variance",
    prompt: "若 GRPO 对某个 prompt 采样的所有回答奖励都相同，这一组通常会怎样？",
    options: ["归一化优势接近零，几乎不提供策略梯度信号", "所有回答都得到最大正优势", "自动切换为 DQN 更新", "重新启用一个随机 Critic"],
    answer: 0,
    explanation: "奖励没有组内方差时，每个回答都等于组均值；实现会将优势置零，避免除零并停止无信息更新。",
    sourceUrl: SOURCE.grpo,
  },
  {
    id: "rlx-rlvr-verifier-exploit",
    prompt: "RLVR 的验证器若只检查答案格式、却没有可靠核验语义正确性，最可能出现什么？",
    options: ["策略自动学会所有知识", "训练变成严格监督学习", "奖励方差一定归零", "模型学会利用验证器漏洞拿高分"],
    answer: 3,
    explanation: "可验证奖励的可靠性取决于验证器；判定规则有漏洞时，策略会优化漏洞而非真实正确性。",
    sourceUrl: SOURCE.rlvr,
  },

  {
    id: "rlx-agent-tool-observation-mask",
    prompt: "Agentic RL 的轨迹中，为什么工具返回内容通常要从 policy-gradient loss 中 mask 掉？",
    options: ["工具返回永远没有信息", "工具返回必须删除后才能评分", "它是环境产生的 observation，不是策略生成的 action token", "它只能用于训练 Critic"],
    answer: 2,
    explanation: "梯度应强化模型生成的决策 token；工具响应来自环境，应保留在上下文但不当作模型动作训练。",
    sourceUrl: SOURCE.agentTools,
  },
  {
    id: "rlx-agent-prm-vs-orm",
    prompt: "长程 Agent 任务中，相比只在终点给分的 ORM，PRM 的主要优势是什么？",
    options: ["不需要任何评价器", "能给中间步骤更密集的反馈，定位具体好坏动作", "保证标注成本更低", "把所有失败步骤都判为正确"],
    answer: 1,
    explanation: "PRM 对过程步骤评分，信用分配更精确；代价是逐步标注或训练过程模型的成本更高。",
    sourceUrl: SOURCE.agentCredit,
  },
  {
    id: "rlx-agent-long-horizon-eval",
    prompt: "评估长程 Agent 时，为什么不能只保留最终成功率？",
    options: ["成功率不能是百分数", "最终结果与策略无关", "早期错误会改变后续观察，还需记录中间轨迹、工具错误与终止原因", "只要记录模型参数即可复现"],
    answer: 2,
    explanation: "长程交互具有路径依赖；过程记录能区分早期决策错误、工具失败和最终偶然成败。",
    sourceUrl: SOURCE.evaluation,
  },

  {
    id: "rlx-goodhart-diagnostic",
    prompt: "哪种训练曲线组合最像 Goodhart 定律下的奖励投机警报？",
    options: ["训练奖励继续上升，但独立真实任务指标停滞或下降", "训练奖励与真实指标同步提升", "训练奖励保持不变且未运行策略", "所有评测方差都变为零"],
    answer: 0,
    explanation: "代理奖励被过度优化后可能脱离真实目标；独立任务指标与训练奖励背离是直接警报。",
    sourceUrl: SOURCE.failures,
  },
  {
    id: "rlx-eval-reproducible-harness",
    prompt: "要让 RL 模型的评测分数可复现，最完整的做法是哪一项？",
    options: ["只记录模型名称", "版本化数据、提示、采样参数、工具预算、答案抽取与评分器", "每次只展示最好的一次运行", "不断更换温度直到分数最高"],
    answer: 1,
    explanation: "评测 Harness 必须固定从输入到汇总的整条协议，否则相同模型也可能得到不可比的分数。",
    sourceUrl: SOURCE.evaluation,
  },
  {
    id: "rlx-capability-vs-behavior",
    prompt: "RL 后评测中，“能力评测”与“行为评测”的区别最准确的是？",
    options: ["能力只看速度，行为只看显存", "两者完全相同", "能力只适用于人类，行为只适用于模型", "能力看模型能否完成任务，行为看它在权限、工具和反馈下会选择什么"],
    answer: 3,
    explanation: "模型可能具备某项能力，却在真实交互情境中选择拒绝、投机或采取不安全动作，因此两者都要测。",
    sourceUrl: SOURCE.evaluation,
  },
];

const API = Object.freeze(RL_EXTRA_QUESTIONS);
root.CloudQuizRlExtra = API;
if (typeof module !== "undefined" && module.exports) module.exports = API;
})(typeof globalThis !== "undefined" ? globalThis : window);
