(function attachIronData(root, factory) {
  const data = factory();
  if (typeof module === 'object' && module.exports) module.exports = data;
  if (root) root.IronData = data;
})(typeof window !== 'undefined' ? window : globalThis, function createIronData() {
  'use strict';

  function deepFreeze(value) {
    if (!value || typeof value !== 'object' || Object.isFrozen(value)) return value;
    Object.keys(value).forEach((key) => deepFreeze(value[key]));
    return Object.freeze(value);
  }

  const MAP = {
    width: 2400,
    height: 1500,
    gridSize: 40,
    edgePadding: 64,
  };

  const TEAM = {
    player: {
      label: '北境同盟',
      color: '#45d6e8',
      accent: '#b8f7ff',
      dark: '#123b43',
    },
    enemy: {
      label: '赤砂军团',
      color: '#df604a',
      accent: '#ffb39e',
      dark: '#4b211d',
    },
  };

  const UNIT_TYPES = {
    rifle: {
      label: '突击步兵',
      shortLabel: '步兵',
      cost: 100,
      buildTime: 4,
      hp: 100,
      armor: 1,
      radius: 10,
      collisionRadius: 8,
      speed: 96,
      range: 130,
      damage: 12,
      cooldown: 0.8,
      vision: 300,
      armorClass: 'infantry',
      weaponClass: 'rifle',
      targetLayers: ['ground'],
      population: 1,
    },
    rocket: {
      label: '反装甲兵',
      shortLabel: '导弹',
      cost: 260,
      buildTime: 8,
      hp: 90,
      armor: 0,
      radius: 11,
      collisionRadius: 9,
      speed: 84,
      range: 210,
      damage: 40,
      cooldown: 1.6,
      vision: 320,
      armorClass: 'infantry',
      weaponClass: 'rocket',
      targetLayers: ['ground', 'air'],
      population: 1,
    },
    scout: {
      label: '猎犬侦察车',
      shortLabel: '侦察',
      cost: 450,
      buildTime: 12,
      hp: 400,
      armor: 4,
      radius: 18,
      collisionRadius: 15,
      speed: 165,
      range: 150,
      damage: 14,
      cooldown: 0.4,
      vision: 400,
      armorClass: 'light',
      weaponClass: 'autocannon',
      targetLayers: ['ground', 'air'],
      population: 2,
    },
    tank: {
      label: '堡垒主战坦克',
      shortLabel: '坦克',
      cost: 850,
      buildTime: 20,
      hp: 850,
      armor: 8,
      radius: 24,
      collisionRadius: 20,
      speed: 72,
      range: 190,
      damage: 70,
      cooldown: 1.7,
      vision: 340,
      armorClass: 'heavy',
      weaponClass: 'cannon',
      targetLayers: ['ground'],
      population: 3,
    },
    harvester: {
      label: '晶矿采集车',
      shortLabel: '采集',
      cost: 800,
      buildTime: 18,
      hp: 700,
      armor: 6,
      radius: 25,
      collisionRadius: 21,
      speed: 62,
      range: 0,
      damage: 0,
      cooldown: 0,
      vision: 300,
      armorClass: 'heavy',
      weaponClass: null,
      targetLayers: [],
      population: 2,
      cargo: 240,
      mineTime: 2.5,
      unloadTime: 0.8,
    },
    fighter: {
      label: '曙光截击机',
      shortLabel: '截击',
      cost: 900,
      buildTime: 18,
      hp: 420,
      armor: 3,
      radius: 21,
      collisionRadius: 18,
      speed: 210,
      range: 185,
      damage: 24,
      cooldown: 0.58,
      vision: 430,
      armorClass: 'air',
      weaponClass: 'autocannon',
      targetLayers: ['ground', 'air'],
      movementLayer: 'air',
      altitude: 24,
      population: 3,
    },
  };

  const BUILDING_TYPES = {
    hq: {
      label: '指挥核心',
      shortLabel: '核心',
      cost: 2500,
      buildTime: 45,
      hp: 2800,
      armor: 8,
      armorClass: 'structure',
      radius: 74,
      collisionRadius: 63,
      width: 150,
      height: 124,
      powerSupply: 20,
      powerUse: 0,
      income: 0,
      production: ['powerPlant', 'refinery', 'barracks', 'factory', 'airfield', 'turret'],
      range: 0,
      damage: 0,
      cooldown: 0,
    },
    powerPlant: {
      label: '裂变电厂',
      shortLabel: '电厂',
      cost: 450,
      buildTime: 8,
      hp: 650,
      armor: 3,
      armorClass: 'structure',
      radius: 48,
      collisionRadius: 41,
      width: 94,
      height: 84,
      powerSupply: 100,
      powerUse: 0,
      income: 0,
      production: [],
      range: 0,
      damage: 0,
      cooldown: 0,
    },
    refinery: {
      label: '晶矿精炼站',
      shortLabel: '精炼',
      cost: 1400,
      buildTime: 18,
      hp: 1200,
      armor: 6,
      armorClass: 'structure',
      radius: 76,
      collisionRadius: 65,
      width: 150,
      height: 108,
      powerSupply: 0,
      powerUse: 20,
      income: 0,
      production: [],
      range: 0,
      damage: 0,
      cooldown: 0,
    },
    barracks: {
      label: '前线兵营',
      shortLabel: '兵营',
      cost: 500,
      buildTime: 10,
      hp: 700,
      armor: 4,
      armorClass: 'structure',
      radius: 56,
      collisionRadius: 48,
      width: 112,
      height: 86,
      powerSupply: 0,
      powerUse: 10,
      income: 0,
      production: ['rifle', 'rocket'],
      range: 0,
      damage: 0,
      cooldown: 0,
    },
    factory: {
      label: '战车工厂',
      shortLabel: '工厂',
      cost: 1200,
      buildTime: 20,
      hp: 1500,
      armor: 7,
      armorClass: 'structure',
      radius: 78,
      collisionRadius: 66,
      width: 156,
      height: 112,
      powerSupply: 0,
      powerUse: 30,
      income: 0,
      production: ['scout', 'tank', 'harvester'],
      range: 0,
      damage: 0,
      cooldown: 0,
    },
    airfield: {
      label: '天穹空军基地',
      shortLabel: '机场',
      cost: 1500,
      buildTime: 24,
      hp: 1400,
      armor: 6,
      armorClass: 'structure',
      radius: 82,
      collisionRadius: 70,
      width: 164,
      height: 118,
      powerSupply: 0,
      powerUse: 35,
      income: 0,
      production: ['fighter'],
      range: 0,
      damage: 0,
      cooldown: 0,
    },
    turret: {
      label: '哨戒机炮塔',
      shortLabel: '炮塔',
      cost: 700,
      buildTime: 10,
      hp: 650,
      armor: 5,
      armorClass: 'structure',
      radius: 34,
      collisionRadius: 29,
      width: 68,
      height: 68,
      powerSupply: 0,
      powerUse: 25,
      income: 0,
      production: [],
      range: 220,
      damage: 32,
      cooldown: 0.8,
      weaponClass: 'turret',
      targetLayers: ['ground', 'air'],
    },
  };

  const DAMAGE_MULTIPLIERS = {
    rifle: {
      infantry: 1,
      light: 0.5,
      heavy: 0.2,
      air: 0.25,
      structure: 0.15,
    },
    rocket: {
      infantry: 0.5,
      light: 1,
      heavy: 1.6,
      air: 1.25,
      structure: 1.2,
    },
    autocannon: {
      infantry: 1.5,
      light: 1,
      heavy: 0.2,
      air: 1.25,
      structure: 0.2,
    },
    cannon: {
      infantry: 0.7,
      light: 1.25,
      heavy: 1,
      air: 0.3,
      structure: 1.2,
    },
    turret: {
      infantry: 1,
      light: 1.15,
      heavy: 0.85,
      air: 1.5,
      structure: 0.4,
    },
  };

  const DIFFICULTY = {
    easy: {
      label: '新兵',
      aiIncomeMultiplier: 0.85,
      aiBuildTimeMultiplier: 1.15,
      firstWaveTime: 110,
      waveInterval: 95,
      waveStrengthMultiplier: 0.8,
      defenders: 3,
    },
    normal: {
      label: '指挥官',
      aiIncomeMultiplier: 1,
      aiBuildTimeMultiplier: 1,
      firstWaveTime: 85,
      waveInterval: 78,
      waveStrengthMultiplier: 1,
      defenders: 4,
    },
    hard: {
      label: '老兵',
      aiIncomeMultiplier: 1.15,
      aiBuildTimeMultiplier: 0.9,
      firstWaveTime: 70,
      waveInterval: 65,
      waveStrengthMultiplier: 1.2,
      defenders: 5,
    },
  };

  const STARTING_RESOURCES = 1200;

  const BALANCE = {
    defaultDifficulty: 'normal',
    startingResources: STARTING_RESOURCES,
    populationCap: 60,
    fixedStep: 1 / 60,
    buildRadius: 390,
    buildPadding: 18,
    spawnPadding: 20,
    commandQueueLimit: 16,
    controlGroupDoubleTapMs: 350,
    guardAcquirePadding: 90,
    guardLeashMinimum: 160,
    guardLeashMultiplier: 1.35,
    oreNodeCapacity: 9000,
    mineralCollisionScale: 0.72,
    navigationPadding: 4,
    navigationRepathSeconds: 0.75,
    navigationEscapeSeconds: 0.5,
    harvesterSearchRange: 720,
    lowPowerProductionMultiplier: 0.5,
    lowPowerFireRateMultiplier: 0.5,
    buildRefundRatio: 0.75,
    targetFirstContactSeconds: 50,
    targetMatchSeconds: 600,
    maximumMatchSeconds: 720,
  };

  return deepFreeze({
    MAP,
    TEAM,
    UNIT_TYPES,
    BUILDING_TYPES,
    DAMAGE_MULTIPLIERS,
    DIFFICULTY,
    STARTING_RESOURCES,
    BALANCE,
  });
});
