import {ChapterState} from './chapter-model.js';
import {ChapterMap,MAP_POINTS} from './chapter-map.js';
import {CHAPTER_TITLE,INTRO,DIALOGUES,ENDING_CHOICES,JOURNAL_TEXT} from './chapter-content.js';
const $=id=>document.getElementById(id),SAVE_KEY='yanyu.chapter-one.v1';
let saved=null,storageAvailable=true;try{saved=localStorage.getItem(SAVE_KEY);}catch{storageAvailable=false;}
let chapter=new ChapterState(saved),mode='welcome',started=false,near=null,toastTimer,battleTimer,battleConfig=null,battleInitialized=false,lastFocus=null;
const map=new ChapterMap($('world'),{onInteract:interact,onNear:point=>{near=point;renderNear();},getFlags:()=>chapter.snapshot().flags,onMove:position=>{chapter.moveTo(position.x,position.y);save();followHero(position);}});
const portraits={陆行舟:0,阿蘅:1,顾药师:2,沈青竹:3,裴照:4,'陆听雨 · 刻痕':5,'裴照 · 后来的口信':4};
function setMode(next){mode=next;document.querySelector('.site-header').inert=next!=='explore';document.querySelector('main').inert=next!=='explore';map.setPaused(next!=='explore');document.body.classList.toggle('modal-open',!['explore','welcome'].includes(next));document.body.dataset.mode=next;renderNear();}
function save(){if(!started)return;try{localStorage.setItem(SAVE_KEY,JSON.stringify(chapter.snapshot()));$('saveStatus').textContent='进度已存于本机';storageAvailable=true;}catch{storageAvailable=false;$('saveStatus').textContent='浏览器未允许保存';}}
function toast(text){clearTimeout(toastTimer);$('toast').textContent=text;$('toast').classList.remove('hidden');toastTimer=setTimeout(()=>$('toast').classList.add('hidden'),5000);}
function followHero(p){const wrap=$('world').parentElement;if(wrap.scrollWidth>wrap.clientWidth){const x=p.x/1600*$('world').clientWidth;if(x<wrap.scrollLeft+90||x>wrap.scrollLeft+wrap.clientWidth-90)wrap.scrollLeft=Math.max(0,x-wrap.clientWidth/2);}}
function renderNear(){const ready=mode==='explore';$('nearName').textContent=near?near.name:'漫步青溪';$('interactButton').disabled=!ready||!near;$('interactButton').firstChild.textContent=near?'交谈 / 查看 ':'附近无人 ';document.querySelectorAll('#locations button').forEach(b=>b.disabled=!ready);}
function render(){const s=chapter.snapshot(),h=s.hero,f=s.flags;$('objective').textContent=chapter.getObjective();$('level').textContent=`${['','初入江湖','气息渐稳','剑心初明'][h.level]} · ${h.level} 级`;
 for(const [name,v,max]of[['Hp',h.hp,h.maxHp],['Qi',h.qi,h.maxQi]]){$('hero'+name).textContent=`${v} / ${max}`;$('hero'+name+'Bar').style.width=v/max*100+'%';}
 const threshold=h.level===1?50:h.level===2?120:130,base=h.level===1?0:h.level===2?50:120;
 $('heroXp').textContent=h.level===3?`${h.xp} · 本章满级`:`${h.xp} / ${threshold}`;$('heroXpBar').style.width=Math.min(100,(h.xp-base)/(threshold-base)*100)+'%';$('heroPotions').textContent=`金疮药 × ${h.potions}`;$('herbInventory').textContent=f.herbs&&!f.medicine?'青露草 × 1 · 待交药师':'半枚铜钱 · 听雨留下的信物';$('skillBadge').textContent=h.skillPoints?`+${h.skillPoints}`:'';
 $('sideObjective').textContent=f.medicine?'孩子们的药已续上。顾药师记下了这份情。':f.herbs?'青露草已采到，回药庐交给顾药师。':f.herbQuest?'到江畔花坛采青露草，只取成熟叶。':'药庐里，还有人等一碗药。';
 $('questSteps').replaceChildren();for(const [done,text]of[[f.tea,'茶摊口信'],[f.shrine,'旧碑刻痕'],[f.battleWon,'桥头问心'],[!!f.ending,'原信的去留']]){const el=document.createElement('div');el.className='step'+(done?' done':'');el.textContent=text;$('questSteps').append(el);}
 $('progressCount').textContent=`${[f.tea,f.shrine,f.medicine,f.chest].filter(Boolean).length} / 4`;
 for(const b of document.querySelectorAll('#locations button')){const id=b.dataset.place,done=id==='herbalist'?f.medicine:id==='bridge'?f.battleWon:!!f[id];b.classList.toggle('visited',done);b.querySelector('span').textContent=done?'已访 · 再谈':'步行前往';}renderNear();}
for(const point of MAP_POINTS){const b=document.createElement('button');b.dataset.place=point.id;b.textContent=point.name.split(' · ')[0];const note=document.createElement('span');note.textContent='步行前往';b.append(note);b.onclick=()=>{if(mode!=='explore')return;if(map.goTo(point.id)){$('nearName').textContent='前往 '+point.name;$('world').scrollIntoView({block:'nearest',behavior:'auto'});}else toast('暂时无法到达，请先回到石板路。');};$('locations').append(b);}
function makeButton(label,fn,detail,primary=false){const b=document.createElement('button');b.textContent=label;if(primary)b.className='gold';if(detail){const small=document.createElement('small');small.textContent=detail;b.append(small);}b.onclick=fn;return b;}
function showLines(lines,done=()=>{}){setMode('dialog');$('dialogue').classList.remove('hidden');let index=0;
 const advance=()=>{if(index>=lines.length){$('dialogue').classList.add('hidden');setMode('explore');done();return;}const item=lines[index++];$('speaker').textContent=item.speaker;$('dialogueText').textContent=item.text;$('dialogueLabel').textContent=CHAPTER_TITLE;const portrait=portraits[item.speaker];$('dialoguePortrait').style.setProperty('--col',(portrait??0)%3);$('dialoguePortrait').style.setProperty('--row',Math.floor((portrait??0)/3));$('dialoguePortrait').style.opacity=portrait===undefined?'.45':'1';$('dialoguePortrait').setAttribute('aria-label',portrait===undefined?'青溪见闻':item.speaker+'肖像');const b=makeButton(index===lines.length?'记下了 →':'继续 →',advance,null,true);$('dialogueChoices').replaceChildren(b);b.focus({preventScroll:true});};advance();}
function showChoice(title,text,choices){setMode('dialog');$('dialogue').classList.remove('hidden');$('speaker').textContent=title;$('dialogueText').textContent=text;$('dialogueLabel').textContent='一念之间';$('dialoguePortrait').style.setProperty('--col',1);$('dialoguePortrait').style.setProperty('--row',1);$('dialoguePortrait').style.opacity='1';$('dialoguePortrait').setAttribute('aria-label','裴照肖像');$('dialogueChoices').replaceChildren();for(const choice of choices){$('dialogueChoices').append(makeButton(choice.label,()=>{$('dialogue').classList.add('hidden');setMode('explore');choice.action();},choice.detail));}$('dialogueChoices').querySelector('button')?.focus({preventScroll:true});}
function interact(id){if(mode!=='explore')return;const before=chapter.snapshot().hero.level;try{const result=chapter.interact(id);save();render();showLines(DIALOGUES[result.dialogue]??[{speaker:'旁白',text:'渡口的风，带来新的消息。'}],()=>{if(result.reward)toast(result.reward+(chapter.snapshot().hero.level>before?' · 升级！获得修习点':''));if(result.startBattle)showChoice('刀背问心','裴照的重击每三回合到来。可先在渡口完成委托、修习武学，再来过招。',[{label:'拔剑过招',detail:'当前气血 '+chapter.snapshot().hero.hp+' / '+chapter.snapshot().hero.maxHp,action:startBattle},{label:'先回渡口整备',action:()=>{}}]);else if(result.choice)chooseEnding();});}catch(error){toast(error.message);}}
function chooseEnding(){showChoice('原信的两面','一面是决堤案证物，一面是十七个孩子的住处。这个选择会写进本章结局。',ENDING_CHOICES.map(choice=>({...choice,action:()=>{const key=chapter.chooseEnding(choice.id);save();render();showLines(DIALOGUES[key],showEnding);}})));}
function showEnding(){const s=chapter.snapshot(),ending=s.flags.ending;if(!ending)return;openPanel('第一章 · 终',ending==='witness'?'灯在江上':'人过青溪',content=>{const p=document.createElement('p');p.textContent=JOURNAL_TEXT[ending];content.append(p);const stats=document.createElement('p');stats.textContent=`陆行舟 · ${s.hero.level} 级　阅历 ${s.hero.xp}　渡口见闻 ${[s.flags.tea,s.flags.shrine,s.flags.medicine,s.flags.chest].filter(Boolean).length}/4`;content.append(stats);content.append(makeButton('回看渡口，补全过江前的见闻',closePanel,null,true));content.append(makeButton('重开章节，体验另一条路',confirmRestart,'将从本章起点重新开始。'));});}
function openPanel(eyebrow,title,build){if(mode==='battle')return;lastFocus=document.activeElement;setMode('panel');$('panelEyebrow').textContent=eyebrow;$('panelTitle').textContent=title;$('panelContent').replaceChildren();build($('panelContent'));$('panelModal').classList.remove('hidden');$('closePanel').focus({preventScroll:true});}
function closePanel(){$('panelModal').classList.add('hidden');setMode(started?'explore':'welcome');if(lastFocus?.isConnected)lastFocus.focus({preventScroll:true});}
$('closePanel').onclick=closePanel;
const journalLabels={tea:'茶摊口信',herbs:'药庐之托',shrine:'旧碑刻痕',battle:'原信两面',witness:'灯在江上',shelter:'人过青溪'};
function openJournal(){if(!started)return;openPanel('江湖札记','路过的人，记下的事',content=>{const f=chapter.snapshot().flags,keys=[];if(f.tea)keys.push('tea');if(f.medicine)keys.push('herbs');if(f.shrine)keys.push('shrine');if(f.battleWon)keys.push('battle');if(f.ending)keys.push(f.ending);if(!keys.length){const p=document.createElement('p');p.textContent='这一页还空着。去茶摊坐一坐，故事会从人声里开始。';content.append(p);}for(const key of keys){const div=document.createElement('section');div.className='journal-entry';const h=document.createElement('h3');h.textContent=journalLabels[key];const p=document.createElement('p');p.textContent=JOURNAL_TEXT[key];div.append(h,p);content.append(div);}if(f.ending)content.append(makeButton('重看章节结局',()=>{closePanel();showEnding();}));});}
function openGrowth(){if(!started)return;openPanel('武学修习','剑未出，心先稳',content=>{const s=chapter.snapshot(),p=document.createElement('p');p.textContent=`当前 ${s.hero.level} 级 · 可用修习点 ${s.hero.skillPoints}。阅历累计达到 50 / 120 时升级，每次获得 1 修习点、20 气血与 6 真气上限。`;content.append(p);for(const [id,name,description]of[['sword','流云剑 · 精进','每次剑击伤害 +5，蓄势连击的每一击都生效。'],['vitality','经脉 · 淬炼','气血上限 +25，并立即补足新增气血。']]){const card=document.createElement('div');card.className='training-card';const h=document.createElement('h3');h.textContent=name;const d=document.createElement('p');d.textContent=description;const b=makeButton(s.learned[id]?'已修习':'修习 · 1 点',()=>{try{const r=chapter.learn(id);save();render();openGrowth();toast(r.reward);}catch(e){toast(e.message);}});b.disabled=s.learned[id]||s.hero.skillPoints===0;card.append(h,d,b);content.append(card);}const info=document.createElement('p');info.textContent='阅历来自调查、寻物、完成药师委托与桥头交锋。同一份收获只结算一次。';content.append(info);});}
$('journalButton').onclick=openJournal;$('growthButton').onclick=openGrowth;$('trainButton').onclick=openGrowth;
$('helpButton').onclick=()=>openPanel('游玩指南','先走一走，再出剑',content=>{for(const text of ['点地图地面行走，点人物或左侧地点会自动寻路并交谈。电脑也可用 WASD / 方向键移动，E 与附近人物互动。','手机可以横向滑动查看地图，用下方摇杆移动。地图会在行走时跟随你；地点按钮始终可用。','主线：茶摊口信 → 旧碑线索 → 桥头交锋 → 原信抉择。药师委托与宝箱为可选探索，可获得经验与补给。','修习点需在“修习”中主动分配，效果会带入战斗。驿亭休息免费恢复气血与真气；药品不会凭空补充。','进度只存在当前浏览器中，完成互动与移动时自动保存。战斗中刷新会回到交锋前；战败保留线索，可休息后再挑战。']){const p=document.createElement('p');p.textContent=text;content.append(p);}});
function confirmRestart(){openPanel('重开章节','再走一遍青溪渡',content=>{const p=document.createElement('p');p.textContent='这会替换本机的第一章进度，包括修习、物品与结局。';content.append(p,makeButton('确认重开',()=>{chapter=new ChapterState();started=true;$('panelModal').classList.add('hidden');map.start(chapter.snapshot().position);render();chapter.markIntro();save();showLines(INTRO);},null,true),makeButton('保留进度，回到渡口',closePanel));});}
$('restartButton').onclick=confirmRestart;
$('interactButton').onclick=()=>map.interactNearest();
function startBattle(){try{battleConfig=chapter.battleConfig();}catch(e){toast(e.message);return;}save();setMode('battle');battleInitialized=false;$('battleShell').classList.remove('hidden');$('battleLoading').classList.remove('hidden');$('battleLoading').textContent='正在进入桥头交锋…';$('battleFrame').src='./battle.html?chapter=1';clearTimeout(battleTimer);battleTimer=setTimeout(()=>{if(!battleInitialized)$('battleLoading').textContent='战斗素材仍在加载，可稍候或退回渡口重试。';},30000);}
function receiveBattle(won,hero){if(mode!=='battle')return;const before=chapter.snapshot().hero.level;const result=chapter.finishBattle(won,hero);if(!result)return;clearTimeout(battleTimer);$('battleShell').classList.add('hidden');$('battleFrame').src='about:blank';battleInitialized=false;save();render();map.start(chapter.snapshot().position);showLines(DIALOGUES[result.dialogue],()=>{if(result.reward)toast(result.reward+(chapter.snapshot().hero.level>before?' · 升级！获得修习点':''));if(result.choice)chooseEnding();else toast('线索和修习仍在。可去驿亭休息，再战桥头。');});}
window.addEventListener('message',event=>{if(mode!=='battle'||event.origin!==location.origin||event.source!==$('battleFrame').contentWindow)return;if(event.data?.type==='chapter-battle-ready'){battleInitialized=true;clearTimeout(battleTimer);$('battleLoading').classList.add('hidden');$('battleFrame').contentWindow.postMessage({type:'chapter-battle-start',hero:battleConfig},location.origin);$('battleFrame').focus();}if(event.data?.type==='chapter-battle-result')receiveBattle(event.data.won,event.data.hero);});
$('retreatButton').onclick=()=>{if(!battleInitialized)receiveBattle(false,battleConfig);else $('battleFrame').contentWindow.postMessage({type:'chapter-battle-abort'},location.origin);};
let stickPointer=null;
function stickMove(event){if(event.pointerId!==stickPointer)return;const r=$('stick').getBoundingClientRect(),dx=(event.clientX-r.left-r.width/2)/(r.width*.38),dy=(event.clientY-r.top-r.height/2)/(r.height*.38),mag=Math.max(1,Math.hypot(dx,dy));map.setStick(dx/mag,dy/mag);$('stickThumb').style.transform=`translate(${dx/mag*18}px,${dy/mag*18}px)`;}
function stickEnd(){stickPointer=null;map.setStick(0,0);$('stickThumb').style.transform='';}
$('stick').addEventListener('pointerdown',e=>{if(mode!=='explore')return;e.preventDefault();stickPointer=e.pointerId;$('stick').setPointerCapture(e.pointerId);stickMove(e);});$('stick').addEventListener('pointermove',stickMove);$('stick').addEventListener('pointerup',stickEnd);$('stick').addEventListener('pointercancel',stickEnd);window.addEventListener('blur',stickEnd);
window.addEventListener('keydown',event=>{if(event.key==='Escape'&&mode==='panel'){closePanel();return;}if(event.key==='Tab'&&['dialog','panel','welcome'].includes(mode)){const container=mode==='panel'?$('panelModal'):mode==='dialog'?$('dialogue'):$('welcome'),buttons=[...container.querySelectorAll('button:not(:disabled)')].filter(x=>!x.classList.contains('hidden'));if(buttons.length){const first=buttons[0],last=buttons.at(-1);if(event.shiftKey&&document.activeElement===first){event.preventDefault();last.focus();}else if(!event.shiftKey&&document.activeElement===last){event.preventDefault();first.focus();}}}});
window.addEventListener('pagehide',()=>{chapter.moveTo(map.position.x,map.position.y);save();});
$('startButton').onclick=()=>{started=true;$('welcome').classList.add('hidden');map.start(chapter.snapshot().position);chapter.moveTo(map.position.x,map.position.y);render();if(!chapter.snapshot().flags.intro){chapter.markIntro();save();showLines(INTRO);}else{setMode('explore');save();if(chapter.snapshot().flags.ending)showEnding();}followHero(map.position);if(!storageAvailable)toast('当前浏览器未允许存档，本次仍可正常游玩。');};
$('retryLoad').onclick=()=>location.reload();render();map.load().then(()=>{$('startButton').disabled=false;$('startButton').textContent=chapter.restored?'续上这一程 →':'走进青溪渡 →';$('loadStatus').textContent=chapter.invalidSave?'旧存档无法读取，已准备新的旅程。':'地图已就绪 · 手机与电脑均可游玩';}).catch(error=>{$('loadStatus').textContent=error.message;$('retryLoad').classList.remove('hidden');});
