import { SpriteAtlas } from './sprites.js';
const W=1440,H=900;
const WALK=[[325,300],[500,225],[635,255],[745,320],[890,290],[1020,205],[1190,190],[1310,245],[1370,355],[1360,540],[1260,640],[1100,625],[950,555],[840,500],[745,500],[580,565],[425,540],[325,465]];
function walkable(x,y){let inside=false;for(let i=0,j=WALK.length-1;i<WALK.length;j=i++){const a=WALK[i],b=WALK[j];if((a[1]>y)!==(b[1]>y)&&x<(b[0]-a[0])*(y-a[1])/(b[1]-a[1])+a[0])inside=!inside;}return inside;}
function constrain(p){if(walkable(p.x,p.y))return;let best=Infinity,point=null;for(let i=0;i<WALK.length;i++){const a=WALK[i],b=WALK[(i+1)%WALK.length],dx=b[0]-a[0],dy=b[1]-a[1],t=Math.max(0,Math.min(1,((p.x-a[0])*dx+(p.y-a[1])*dy)/(dx*dx+dy*dy))),x=a[0]+t*dx,y=a[1]+t*dy,d=(x-p.x)**2+(y-p.y)**2;if(d<best){best=d;point={x,y};}}p.x=point.x;p.y=point.y;}
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
const dist=(a,b)=>Math.hypot(a.x-b.x,a.y-b.y);
const stages={intro:'前往村口，与沈青竹交谈',hunt:'采集三株灵草，击退三名山匪',boss:'前往竹林空地，击败黑风寨主',return:'返回村口，向沈青竹复命',won:'青溪平安 · 此间侠名初成',lost:'胜败乃兵家常事，请重新启程'};
export class Game {
 constructor(canvas,callbacks={}){
  this.canvas=canvas;this.ctx=canvas.getContext('2d');canvas.width=W;canvas.height=H;this.cb=callbacks;this.keys=new Set();this.running=false;this.paused=false;this.dialog=null;this.last=0;this.time=0;this.audio=null;
  this.sprites=new SpriteAtlas(()=>{if(this.player)this.draw();});this.world=new Image();this.world.src='./assets/world.png';this.world.onload=()=>this.draw();
  this._keydown=e=>{if(['INPUT','TEXTAREA'].includes(document.activeElement?.tagName))return;const k=e.key.toLowerCase();if(['arrowup','arrowdown','arrowleft','arrowright',' ','escape'].includes(k))e.preventDefault();this.keys.add(k);if(e.repeat)return;if(k==='e')this.interact();if(k==='j'||k===' ')this.attack();if(k==='k')this.dash();if(k==='l')this.skill();if(k==='h')this.heal();};
  this._keyup=e=>this.keys.delete(e.key.toLowerCase());window.addEventListener('keydown',this._keydown);window.addEventListener('keyup',this._keyup);window.addEventListener('blur',()=>this.keys.clear());
  this.reset();this.draw();
 }
 reset(){this.player={x:390,y:480,r:19,facing:0,hp:100,qi:100,inv:0,dash:0,actionTime:0,actionDuration:0,moving:false};this.stage='intro';this.herbs=0;this.kills=0;this.potions=3;this.elapsed=0;this.cooldowns={attack:0,dash:0,skill:0};this.effects=[];this.projectiles=[];this.shake=0;this.dialog=null;this.npc={x:320,y:390};this.plants=[{x:530,y:510},{x:780,y:350},{x:1090,y:590}].map(p=>({...p,taken:false}));this.enemies=[{x:750,y:450},{x:960,y:400},{x:1170,y:555},{x:1190,y:360,boss:true}].map((e,i)=>({...e,id:i,r:e.boss?28:19,hp:e.boss?210:70,maxHp:e.boss?210:70,cd:0.7+i*.4,wind:0,stun:0,active:!e.boss}));this.notify();}
 start(){if(this.running)return;this.running=true;this.last=performance.now();requestAnimationFrame(t=>this.frame(t));}
 restart(){this.reset();this.paused=false;this.cb.onDialog?.(null);this.start();}
 pause(value){this.paused=!!value;this.keys.clear();this.notify();}
 getState(){return{hp:Math.ceil(this.player.hp),maxHp:100,qi:Math.floor(this.player.qi),maxQi:100,herbs:this.herbs,kills:this.kills,objective:stages[this.stage],stage:this.stage,potions:this.potions,elapsed:this.elapsed,cooldowns:{...this.cooldowns},paused:this.paused,dialog:!!this.dialog,player:{x:this.player.x,y:this.player.y}};}
 notify(){this.cb.onUpdate?.(this.getState());}
 toast(text){this.cb.onToast?.(text);}
 canAct(){return this.running&&!this.paused&&!this.dialog&&!['won','lost'].includes(this.stage);}
 setMuted(value){this.muted=!!value;}
 tone(freq=440,duration=.1,type='sine',gain=.04){if(this.muted)return;try{this.audio??=new(window.AudioContext||window.webkitAudioContext)();this.audio.resume();const o=this.audio.createOscillator(),g=this.audio.createGain();o.type=type;o.frequency.setValueAtTime(freq,this.audio.currentTime);o.frequency.exponentialRampToValueAtTime(freq*.4,this.audio.currentTime+duration);g.gain.setValueAtTime(gain,this.audio.currentTime);g.gain.exponentialRampToValueAtTime(.001,this.audio.currentTime+duration);o.connect(g);g.connect(this.audio.destination);o.start();o.stop(this.audio.currentTime+duration);}catch{}}
 attack(){if(!this.canAct()||this.cooldowns.attack>0)return;this.cooldowns.attack=.38;const p=this.player;p.action='attack';p.actionTime=.36;p.actionDuration=.36;this.effects.push({type:'slash',x:p.x,y:p.y,angle:p.facing,life:.23,max:.23,r:100});this.tone(260,.13,'triangle');for(const e of this.enemies){if(e.hp<=0||!e.active||dist(e,p)>110)continue;const a=Math.atan2(e.y-p.y,e.x-p.x);if(Math.cos(a-p.facing)>-.25)this.hit(e,27,p.facing);}}
 dash(){if(!this.canAct()||this.cooldowns.dash>0)return;this.cooldowns.dash=1.7;this.player.dash=.19;this.player.actionTime=0;this.player.inv=.30;this.tone(700,.15,'sine',.025);}
 skill(){if(!this.canAct()||this.cooldowns.skill>0)return;if(this.player.qi<30){this.toast('内力不足，稍作调息');return;}this.player.qi-=30;this.cooldowns.skill=3.8;const p=this.player;p.action='skill';p.actionTime=.48;p.actionDuration=.48;this.projectiles.push({x:p.x,y:p.y,a:p.facing,life:1.2,hit:new Set()});this.tone(900,.3,'triangle');this.effects.push({type:'ring',x:p.x,y:p.y,r:50,life:.3,max:.3,color:'#b9f8df'});}
 heal(){if(!this.canAct())return;if(this.potions<=0){this.toast('金疮药已用尽');return;}if(this.player.hp>=100){this.toast('气血充盈，无须服药');return;}this.potions--;this.player.hp=Math.min(100,this.player.hp+45);this.effects.push({type:'text',x:this.player.x,y:this.player.y-40,text:'+45 气血',life:1.2,max:1.2,color:'#9ee7b8'});this.tone(600,.4);this.notify();}
 interact(){if(!this.canAct())return;const p=this.player;if(dist(p,this.npc)<105){if(this.stage==='intro')this.showDialog('老渡夫 · 沈青竹','少侠，黑风寨的人占了东边竹林空地。村中伤者急需灵草，烦请采回三株，再替我们击退那些山匪。',['交给我吧'],()=>{this.stage='hunt';this.toast('委托已接取：青溪除患');});else if(this.stage==='return')this.showDialog('老渡夫 · 沈青竹','灵草齐了，黑风寨主也已伏诛。多谢少侠！这柄青溪剑，便赠与你。愿你行走江湖，心中常存一盏灯。',['收下青溪剑'],()=>{this.stage='won';this.cb.onEnd?.(this.getState());});else this.showDialog('老渡夫 · 沈青竹',this.stage==='hunt'?`灵草已得 ${this.herbs}/3 株，山匪已退 ${this.kills}/3 人。小心他们出招前的红圈，闪身绕后便能取胜。`:'寨主就在东边竹林空地。剑气可以远攻，金疮药可用 H 服下。',['我这就去'],()=>{});return;}
  const plant=this.plants.find(a=>!a.taken&&dist(a,p)<85);if(plant){if(this.stage==='intro'){this.toast('先与沈青竹交谈，了解村中困境');return;}plant.taken=true;this.herbs++;this.player.qi=Math.min(100,this.player.qi+12);this.effects.push({type:'text',x:plant.x,y:plant.y-30,text:'灵草 +1',color:'#d4ef9a',life:1.4,max:1.4});this.tone(850,.23);this.advance();this.notify();return;}this.toast('靠近村民或灵草，按 E 互动');}
 showDialog(speaker,text,choices,action){this.dialog={action};this.keys.clear();this.cb.onDialog?.({speaker,text,choices});this.notify();}
 chooseDialog(index){if(!this.dialog||index!==0)return;const action=this.dialog.action;this.dialog=null;this.cb.onDialog?.(null);action();this.notify();}
 hit(e,damage,angle){e.hp-=damage;e.stun=.16;e.wind=0;e.x=clamp(e.x+Math.cos(angle)*(e.boss?10:22),475,1380);e.y=clamp(e.y+Math.sin(angle)*(e.boss?10:22),165,810);constrain(e);this.effects.push({type:'text',x:e.x,y:e.y-35,text:String(damage),color:'#fff1c0',life:.7,max:.7});this.shake=e.boss?5:3;if(e.hp<=0){e.hp=0;if(!e.boss){this.kills++;this.player.qi=Math.min(100,this.player.qi+15);}else{this.stage='return';this.toast('黑风寨主已败！返回村口复命');}this.effects.push({type:'ring',x:e.x,y:e.y,r:65,life:.5,max:.5,color:'#d8c99b'});this.advance();}}
 advance(){if(this.stage==='hunt'&&this.herbs===3&&this.kills>=3){this.stage='boss';this.enemies[3].active=true;this.toast('竹林空地传来怒喝：黑风寨主现身！');}}
 frame(now){if(!this.running)return;const dt=Math.max(0,Math.min((now-this.last)/1000,.035));this.last=now;if(!this.paused&&!this.dialog)this.time+=dt;if(!this.paused&&!this.dialog&&!['won','lost'].includes(this.stage))this.update(dt);this.draw();requestAnimationFrame(t=>this.frame(t));}
 update(dt){const p=this.player;this.elapsed+=dt;p.actionTime=Math.max(0,p.actionTime-dt);p.inv=Math.max(0,p.inv-dt);p.dash=Math.max(0,p.dash-dt);p.qi=Math.min(100,p.qi+7*dt);for(const k in this.cooldowns)this.cooldowns[k]=Math.max(0,this.cooldowns[k]-dt);let dx=(this.keys.has('d')||this.keys.has('arrowright')?1:0)-(this.keys.has('a')||this.keys.has('arrowleft')?1:0),dy=(this.keys.has('s')||this.keys.has('arrowdown')?1:0)-(this.keys.has('w')||this.keys.has('arrowup')?1:0);const n=Math.hypot(dx,dy);p.moving=n>0;if(n){dx/=n;dy/=n;if(!p.dash)p.facing=Math.atan2(dy,dx);}if(p.dash){dx=Math.cos(p.facing);dy=Math.sin(p.facing);this.effects.push({type:'ghost',x:p.x,y:p.y,life:.2,max:.2,facing:p.facing,dash:.1});}const speed=p.dash?790:220;p.x=clamp(p.x+dx*speed*dt,60,1380);p.y=clamp(p.y+dy*speed*dt,165,815);constrain(p);
  for(const e of this.enemies){if(e.hp<=0||!e.active)continue;e.moving=false;e.attackAnim=Math.max(0,(e.attackAnim||0)-dt);e.facing=Math.atan2(p.y-e.y,p.x-e.x);e.cd-=dt;e.stun=Math.max(0,e.stun-dt);const d=dist(e,p);if(e.wind>0){e.wind-=dt;if(e.wind<=0){e.attackAnim=.3;e.cd=e.boss?1.15:1.5;const range=e.boss?115:75;this.effects.push({type:'ring',x:e.x,y:e.y,r:range,life:.25,max:.25,color:'#ed9976'});if(dist(e,p)<range+10&&p.inv<=0){p.hp=Math.max(0,p.hp-(e.boss?23:12));p.inv=.55;this.shake=11;this.tone(90,.16,'sawtooth',.035);this.effects.push({type:'text',x:p.x,y:p.y-50,text:e.boss?'-23':'-12',color:'#ff9e8e',life:.8,max:.8});if(!p.hp){this.stage='lost';this.cb.onEnd?.(this.getState());}}}continue;}if(e.stun>0)continue;if(d<(e.boss?440:295)&&p.x>440&&this.stage!=='intro'){if(d>(e.boss?88:53)){e.moving=true;const speed=e.boss?105:93;e.x+=(p.x-e.x)/d*speed*dt;e.y+=(p.y-e.y)/d*speed*dt;constrain(e);}else if(e.cd<=0){e.wind=e.boss?.85:.65;e.windMax=e.wind;}}}
  for(const b of this.projectiles){b.x+=Math.cos(b.a)*740*dt;b.y+=Math.sin(b.a)*740*dt;b.life-=dt;for(const e of this.enemies)if(e.hp>0&&e.active&&!b.hit.has(e.id)&&dist(e,b)<55){b.hit.add(e.id);this.hit(e,45,b.a);}}this.projectiles=this.projectiles.filter(b=>b.life>0&&b.x>0&&b.x<W&&b.y>0&&b.y<H);for(const e of this.effects)e.life-=dt;this.effects=this.effects.filter(e=>e.life>0);this.shake=Math.max(0,this.shake-dt*45);this.notify();}
 draw(){const c=this.ctx;c.save();c.clearRect(0,0,W,H);if(this.shake)c.translate((Math.random()-.5)*this.shake,(Math.random()-.5)*this.shake);if(this.world.complete&&this.world.naturalWidth)c.drawImage(this.world,0,0,W,H);else this.drawMap(c);c.fillStyle='rgba(8,25,25,.13)';c.fillRect(0,0,W,H);
  this.label(c,380,260,'青 溪 村','#e7ddb6',19);this.label(c,1180,240,'竹 林','#e7ddb6',19);
  for(const plant of this.plants){if(plant.taken)continue;const pulse=1+Math.sin(this.time*3+plant.x)*.13;c.save();c.translate(plant.x,plant.y);c.fillStyle='#d8ef9b22';c.beginPath();c.ellipse(0,5,35*pulse,15*pulse,0,0,Math.PI*2);c.fill();c.strokeStyle='#b0d079';c.lineWidth=3;for(let i=0;i<5;i++){const a=-Math.PI+i*Math.PI/4;c.beginPath();c.moveTo(0,7);c.quadraticCurveTo(Math.cos(a)*24,Math.sin(a)*25,Math.cos(a)*18,Math.sin(a)*18);c.stroke();c.fillStyle=i%2?'#b6d7a0':'#729f76';c.beginPath();c.ellipse(Math.cos(a)*15,Math.sin(a)*18,9,4,a,0,Math.PI*2);c.fill();}c.fillStyle='#f7db9a';c.beginPath();c.arc(0,-18,4,0,Math.PI*2);c.fill();c.restore();if(dist(plant,this.player)<85)this.label(c,plant.x,plant.y-53,'[E] 采集灵草','#f3ebcc',15);}
  this.drawActor(c,this.npc,'#c9c0a2','#456761',false);this.label(c,320,301,'老渡夫 · 沈青竹','#eadfba',15);this.label(c,320,279,this.stage==='return'?'◆':'!', '#f0c570',25);if(dist(this.player,this.npc)<105)this.label(c,320,435,'[E] 交谈','#ffefd0',15);
  for(const e of this.enemies){if(e.hp<=0){c.fillStyle='#342c2d55';c.beginPath();c.ellipse(e.x,e.y+9,24,8,.3,0,Math.PI*2);c.fill();continue;}if(!e.active){c.globalAlpha=.45;this.drawActor(c,e,'#514548','#292f34',true);c.globalAlpha=1;this.label(c,e.x,e.y-125,'黑风寨主 · 尚未现身','#bfb69e',14);continue;}if(e.wind>0){const r=e.boss?115:75;c.fillStyle=`rgba(202,69,42,${.16+(1-e.wind/e.windMax)*.25})`;c.strokeStyle='#e68b61';c.lineWidth=2;c.beginPath();c.arc(e.x,e.y,r,0,Math.PI*2);c.fill();c.stroke();c.fillStyle='#f4af6c';c.beginPath();c.arc(e.x,e.y,6,0,Math.PI*2);c.fill();}this.drawActor(c,e,e.boss?'#735055':'#82624c',e.boss?'#302e36':'#45433b',true);const bw=e.boss?90:52;c.fillStyle='#172726';c.fillRect(e.x-bw/2,e.y-(e.boss?111:86),bw,5);c.fillStyle=e.boss?'#d08065':'#c7a070';c.fillRect(e.x-bw/2,e.y-(e.boss?111:86),bw*Math.max(0,e.hp/e.maxHp),5);if(e.boss)this.label(c,e.x,e.y-131,'黑风寨主','#efcb9e',15);}
  for(const e of this.effects)if(e.type==='ghost'){c.globalAlpha=e.life/e.max*.3;this.drawActor(c,e,'#aadcd4','#a2cfc2',false);c.globalAlpha=1;}
  c.save();if(this.player.inv>0&&!this.player.dash&&Math.floor(this.time*18)%2)c.globalAlpha=.45;this.drawActor(c,this.player,'#d5ddd0','#477572',false,true);c.restore();
  for(const b of this.projectiles){c.save();c.translate(b.x,b.y);c.rotate(b.a);c.shadowColor='#c2f7e1';c.shadowBlur=18;c.strokeStyle='#d0f5de';c.lineWidth=7;c.beginPath();c.arc(-12,0,37,-1.2,1.2);c.stroke();c.strokeStyle='#77bfa6';c.lineWidth=2;c.beginPath();c.moveTo(-60,-10);c.lineTo(14,0);c.lineTo(-60,10);c.stroke();c.restore();}
  for(const e of this.effects){const t=e.life/e.max;c.save();c.globalAlpha=t;if(e.type==='slash'){c.translate(e.x,e.y);c.rotate(e.angle);c.strokeStyle='#eef6d5';c.shadowColor='#daebbd';c.shadowBlur=12;c.lineWidth=4+8*t;c.beginPath();c.arc(0,0,e.r*(1.1-.25*t),-1.15,1.15);c.stroke();c.strokeStyle='#b7d5b7';c.lineWidth=2;c.beginPath();c.arc(0,0,e.r*.7,-1,1.3);c.stroke();}else if(e.type==='ring'){c.strokeStyle=e.color;c.lineWidth=3*t;c.beginPath();c.arc(e.x,e.y,e.r*(1.2-.7*t),0,Math.PI*2);c.stroke();}else if(e.type==='text')this.label(c,e.x,e.y-(1-t)*38,e.text,e.color,19);c.restore();}
  const target=this.stage==='intro'||this.stage==='return'?this.npc:this.stage==='boss'?this.enemies[3]:null;if(target&&dist(target,this.player)>160){const p=this.player,a=Math.atan2(target.y-p.y,target.x-p.x),x=p.x+Math.cos(a)*85,y=p.y+Math.sin(a)*85;c.save();c.translate(x,y);c.rotate(a);c.fillStyle='#eed497';c.beginPath();c.moveTo(9,0);c.lineTo(-5,-5);c.lineTo(-2,0);c.lineTo(-5,5);c.closePath();c.fill();c.restore();}
  c.restore();}
 label(c,x,y,text,color,size=16){c.save();c.font=`500 ${size}px "Noto Serif SC", "Songti SC", serif`;c.textAlign='center';c.textBaseline='middle';c.shadowColor='#102421';c.shadowBlur=6;c.lineWidth=4;c.strokeStyle='#18332daa';c.strokeText(text,x,y);c.fillStyle=color;c.fillText(text,x,y);c.restore();}
 drawActor(c,p,robe,coat,enemy,hero=false){if(this.sprites.draw(c,hero||p.type==='ghost'?'hero':enemy?(p.boss?'boss':'bandit'):'npc',p,this.time,{ghost:p.type==='ghost'}))return;c.save();c.translate(p.x,p.y);const scale=p.boss?1.3:1;c.scale(scale,scale);c.fillStyle='#0c24204d';c.beginPath();c.ellipse(0,19,25,9,0,0,Math.PI*2);c.fill();if(hero){c.strokeStyle='#e4ce8c88';c.lineWidth=1;c.beginPath();c.ellipse(0,20,26,10,0,0,Math.PI*2);c.stroke();}const sway=hero&&[...this.keys].some(k=>['w','a','s','d','arrowup','arrowdown','arrowleft','arrowright'].includes(k))?Math.sin(this.time*15)*3:Math.sin(this.time*2)*.8;c.fillStyle='#283c36';c.fillRect(-10,12+sway,7,11);c.fillRect(4,12-sway,7,11);c.fillStyle=coat;c.strokeStyle='#142f2c';c.lineWidth=1.5;c.beginPath();c.moveTo(-10,-16);c.lineTo(10,-16);c.lineTo(19,18);c.quadraticCurveTo(0,26,-18,18);c.closePath();c.fill();c.stroke();c.fillStyle=robe;c.beginPath();c.moveTo(-7,-16);c.lineTo(1,-2);c.lineTo(8,-16);c.lineTo(12,17);c.lineTo(-11,18);c.closePath();c.fill();c.fillStyle=coat;c.fillRect(-12,-1,24,5);c.strokeStyle=robe;c.lineWidth=8;c.lineCap='round';c.beginPath();c.moveTo(-10,-12);c.lineTo(-18,3+sway);c.moveTo(11,-12);c.lineTo(19,1-sway);c.stroke();c.fillStyle='#d7b997';c.beginPath();c.ellipse(0,-23,9,11,0,0,Math.PI*2);c.fill();c.fillStyle='#1f302c';c.beginPath();c.arc(0,-28,10,Math.PI,Math.PI*2);c.lineTo(9,-21);c.lineTo(5,-24);c.lineTo(-8,-23);c.closePath();c.fill();c.beginPath();c.arc(0,-39,5,0,Math.PI*2);c.fill();if(hero){c.strokeStyle='#d2c9a9';c.lineWidth=2;c.beginPath();c.moveTo(-9,-27);c.lineTo(9,-27);c.lineTo(18,-19+sway);c.stroke();}c.strokeStyle='#d4dcd0';c.lineWidth=3;c.beginPath();c.moveTo(19,0);c.lineTo(enemy?37:32,enemy?-23:-28);c.stroke();c.strokeStyle='#c2a577';c.lineWidth=3;c.beginPath();c.moveTo(15,-7);c.lineTo(25,-2);c.stroke();c.restore();}
 drawMap(c){c.fillStyle='#667762';c.fillRect(0,0,W,H);const g=c.createLinearGradient(0,0,W,H);g.addColorStop(0,'#3c645d');g.addColorStop(.5,'#879777');g.addColorStop(1,'#4e7366');c.fillStyle=g;c.fillRect(0,0,W,H);c.lineCap='round';c.strokeStyle='#b8b393';c.lineWidth=110;c.beginPath();c.moveTo(80,670);c.bezierCurveTo(390,670,500,420,720,510);c.bezierCurveTo(930,610,1100,250,1420,400);c.stroke();c.strokeStyle='#aec0a088';c.lineWidth=80;c.stroke();c.fillStyle='#304f48';for(let i=0;i<40;i++){let x=(i*197+47)%W,y=(i*313+27)%H;if(y>180&&y<770&&x>150&&x<1300)continue;c.beginPath();c.arc(x,y,44+(i%4)*10,0,Math.PI*2);c.fill();}c.fillStyle='#486b68';c.beginPath();c.moveTo(1090,0);c.bezierCurveTo(1000,200,1340,510,1300,900);c.lineTo(1460,900);c.lineTo(1460,0);c.fill();c.fillStyle='#8e8a6e';c.fillRect(1120,300,200,100);c.strokeStyle='#4b5047';c.lineWidth=4;for(let x=1120;x<1320;x+=20){c.beginPath();c.moveTo(x,300);c.lineTo(x,400);c.stroke();}for(const [x,y]of[[120,310],[330,230],[90,490]]){c.fillStyle='#b5b299';c.fillRect(x-50,y,100,75);c.fillStyle='#445b56';c.beginPath();c.moveTo(x-70,y+5);c.lineTo(x,y-45);c.lineTo(x+70,y+5);c.closePath();c.fill();c.fillStyle='#4d574b';c.fillRect(x-12,y+30,24,45);}}
}
