import {TurnBattle} from './turn-model.js';
import {SpriteAtlas} from './sprites.js';
import {prologue,preBattle,victory,endChoice,endings} from './story.js';
const $=id=>document.getElementById(id),canvas=$('scene'),c=canvas.getContext('2d'),atlas=new SpriteAtlas();
const background=new Image();background.src='./assets/qingxi-battle.png';background.onerror=()=>{background.onerror=null;background.src='./assets/world.png';};
let battle=new TurnBattle(),shown=battle.snapshot(),mode='opening',storyPhase='prologue',target='guard',boost=0,time=0,last=performance.now(),paused=false,help=false,queue=[],current=null,eventTime=0,lines=[],lineIndex=0,afterDialog=()=>{},outcome='';
function renderUI(){document.body.dataset.gameMode=mode;const h=shown.hero;for(const [id,key,max]of[['hp','hp','maxHp'],['qi','qi','maxQi']]){$(id).textContent=`${h[key]} / ${h[max]}`;$(id+'Bar').style.width=`${h[key]/h[max]*100}%`;}$('bp').textContent='●'.repeat(h.bp)+'○'.repeat(5-h.bp);$('potions').textContent=`金疮药 × ${h.potions}`;$('round').textContent=`第 ${shown.round} 回合`;$('boostCount').textContent=boost;const ready=mode==='battle'&&!current&&!queue.length&&!paused&&!help&&battle.phase==='player';$('phase').textContent=mode==='battle'?(ready?'你的回合':'招式演出中'):'剧情';document.querySelectorAll('[data-action]').forEach(b=>{b.disabled=!ready||(b.dataset.action==='qi'&&h.qi<12)||(b.dataset.action==='heal'&&(!h.potions||h.hp===h.maxHp));});$('boost').disabled=!ready;for(const e of shown.enemies){$(e.id+'Hp').textContent=`${e.hp} / ${e.maxHp}`;$(e.id+'Shield').textContent=e.hp<=0?'已止战':e.broken>0?`破防 · 余 ${e.broken} 次停手`:`架势 ${'◆'.repeat(e.shield)} · 弱点：${e.weak==='sword'?'剑':'气'}`;const b=$(e.id+'Target');b.classList.toggle('selected',e.id===target);b.setAttribute('aria-pressed',String(e.id===target));b.disabled=!ready||e.hp<=0;}$('turnHero').classList.toggle('active',ready||current?.actor==='hero');$('turnGuard').classList.toggle('active',current?.actor==='guard');$('turnChief').classList.toggle('active',current?.actor==='chief');}
function playDialog(list,done){mode='dialog';lines=list;lineIndex=0;afterDialog=done;$('dialog').classList.remove('hidden');nextLine();renderUI();}
function nextLine(){if(lineIndex>=lines.length){$('dialog').classList.add('hidden');afterDialog();return;}const line=lines[lineIndex++];$('speaker').textContent=line.speaker;$('line').textContent=line.text;$('choices').replaceChildren();const b=document.createElement('button');b.textContent=lineIndex===lines.length?'继续 →':'下一句 →';b.onclick=()=>{if(!paused&&!help)nextLine();};$('choices').append(b);}
function start(){battle=new TurnBattle();shown=battle.snapshot();target='guard';boost=0;current=null;queue=[];outcome='';paused=false;storyPhase='prologue';$('opening').classList.add('hidden');$('end').classList.add('hidden');playDialog(prologue,()=>{storyPhase='battle';playDialog(preBattle,()=>{mode='battle';$('log').textContent='此战分胜负，不取性命。选择目标与招式。';renderUI();});});}
$('begin').onclick=start;$('restart').onclick=start;
function finishWin(){storyPhase='aftermath';playDialog(victory,()=>{mode='choice';$('dialog').classList.remove('hidden');$('speaker').textContent=endChoice.speaker;$('line').textContent=endChoice.text;$('choices').replaceChildren();for(const choice of endChoice.choices){const b=document.createElement('button');b.textContent=choice.label;b.onclick=()=>{if(paused||help)return;outcome=choice.id;playDialog(endings[choice.id],()=>{mode='end';$('endTitle').textContent=choice.id==='witness'?'灯在江上':'人过青溪';$('endText').textContent=choice.id==='witness'?'原令成为证据，旧案得以受理；第十七个孩子仍无下落。陆行舟的寻人路，才刚刚开始。':'十七个孩子平安过江，原令却化为灰烬。你与裴照同行，寻找能让亡者重见天日的证人。';$('end').classList.remove('hidden');renderUI();});};$('choices').append(b);}renderUI();});}
function act(action){if(mode!=='battle'||current||queue.length||paused||help)return;try{queue=battle.act(action,target,boost);boost=0;advanceEvent();}catch(e){$('log').textContent=e.message;}}
function advanceEvent(){current=queue.shift()||null;eventTime=0;if(!current){shown=battle.snapshot();if(shown.phase==='won'){finishWin();return;}if(shown.phase==='lost'){mode='end';$('endTitle').textContent='剑尚未稳';$('endText').textContent='裴照收刀，给你留了退路。重新尝试：用气破开他的架势，蓄势连击，把握守心与用药的时机。';$('end').classList.remove('hidden');}const alive=shown.enemies.filter(e=>e.hp>0);if(!alive.some(e=>e.id===target)&&alive.length)target=alive[0].id;renderUI();return;}shown=current.state;$('log').textContent=current.text;if(current.amount){$('damage').textContent=(current.kind==='heal'?'+':'−')+current.amount+ (current.breaking?' 破防':'');$('damage').style.left=current.target==='hero'?'27%':current.target==='chief'?'79%':'66%';$('damage').classList.remove('show');void $('damage').offsetWidth;$('damage').classList.add('show');}renderUI();}
document.querySelectorAll('[data-action]').forEach(b=>b.onclick=()=>act(b.dataset.action));document.querySelectorAll('[data-target]').forEach(b=>b.onclick=()=>{target=b.dataset.target;renderUI();});$('boost').onclick=()=>{boost=(boost+1)%(Math.min(3,shown.hero.bp)+1);renderUI();};
function setPause(v){paused=v;$('pauseOverlay').classList.toggle('hidden',!v);$('pause').textContent=v?'继续':'暂停';renderUI();}$('pause').onclick=()=>setPause(!paused);$('resume').onclick=()=>setPause(false);$('help').onclick=()=>{help=true;$('helpOverlay').classList.remove('hidden');renderUI();};$('closeHelp').onclick=()=>{help=false;$('helpOverlay').classList.add('hidden');renderUI();};
document.addEventListener('visibilitychange',()=>{if(document.hidden&&mode!=='opening'&&!paused)setPause(true);});
window.addEventListener('keydown',e=>{if(e.repeat)return;if(e.key==='Escape'){if(help)$('closeHelp').click();else setPause(!paused);return;}if(paused||help)return;if(mode==='dialog'&&(e.key===' '||e.key==='Enter')){e.preventDefault();nextLine();return;}if(mode!=='battle'||current||queue.length)return;if(['1','2','3','4'].includes(e.key)){e.preventDefault();act(['sword','qi','guard','heal'][Number(e.key)-1]);}if(e.key.toLowerCase()==='b')$('boost').click();if(e.key.toLowerCase()==='t'){e.preventDefault();const live=shown.enemies.filter(e=>e.hp>0);target=live[(live.findIndex(e=>e.id===target)+1)%live.length].id;renderUI();}});
function draw(){c.clearRect(0,0,1440,810);if(background.complete&&background.naturalWidth)c.drawImage(background,0,0,1440,810);else{c.fillStyle='#21373f';c.fillRect(0,0,1440,810);}const vignette=c.createRadialGradient(730,390,180,720,400,840);vignette.addColorStop(0,'#08162400');vignette.addColorStop(1,'#030d1baa');c.fillStyle=vignette;c.fillRect(0,0,1440,810);
 const attack=current?.kind==='hit'&&eventTime<.7,from=current?.actor,to=current?.target,lunge=Math.sin(Math.min(1,eventTime/.7)*Math.PI)*55;
 const hero={x:355+(attack&&from==='hero'?lunge:0),y:590,facing:0,actionTime:attack&&from==='hero'?Math.max(.001,.7-eventTime):0,actionDuration:.7,action:'attack'};
 if(current?.kind==='guard'&&eventTime<.9){c.strokeStyle='#a8dbe580';c.lineWidth=3;c.beginPath();c.ellipse(hero.x,hero.y-50,60,100,0,0,Math.PI*2);c.stroke();}
 atlas.draw(c,'hero',hero,time,{previewScale:1.75});
 if(storyPhase==='prologue'||storyPhase==='aftermath')atlas.draw(c,'npc',{x:890,y:580},time,{previewScale:1.7});
 else for(const e of shown.enemies){if(e.hp<=0)continue;const p={x:(e.id==='guard'?1000:1150)-(attack&&from===e.id?lunge:0),y:e.id==='guard'?550:590,facing:Math.PI,attackAnim:attack&&from===e.id?.3:0};if(e.id===target&&mode==='battle'){c.strokeStyle='#edce83';c.lineWidth=2;c.beginPath();c.ellipse(p.x,p.y+20,42,12,0,0,Math.PI*2);c.stroke();}atlas.draw(c,e.id==='chief'?'boss':'bandit',p,time,{previewScale:e.id==='chief'?1.7:1.6});c.font='16px serif';c.textAlign='center';c.fillStyle=e.broken?'#ffd29a':'#e3d5b0';c.shadowColor='#000';c.shadowBlur=5;c.fillText(e.broken?'破 防':`${'◆'.repeat(e.shield)}  ${e.weak==='sword'?'剑':'气'}`,p.x,p.y-(e.id==='chief'?185:150));c.shadowBlur=0;}
 if(attack&&eventTime>.18&&eventTime<.55){const px=to==='hero'?hero.x:to==='guard'?1000:1150;c.save();c.translate(px,530);c.strokeStyle=current.breaking?'#ffe5a2':'#d4f6e8';c.lineWidth=6;c.shadowBlur=20;c.shadowColor=c.strokeStyle;c.beginPath();c.arc(0,0,85,-1.2+eventTime*2,1.1+eventTime*2);c.stroke();c.restore();const light=c.createRadialGradient(px,540,0,px,540,230);light.addColorStop(0,'#dfefbc35');light.addColorStop(1,'#dfefbc00');c.fillStyle=light;c.fillRect(px-230,310,460,460);}
 c.strokeStyle='#b2d4de28';c.lineWidth=1;for(let i=0;i<60;i++){const x=(i*197+time*30)%1440,y=(i*131+time*240)%810;c.beginPath();c.moveTo(x,y);c.lineTo(x-3,y+12);c.stroke();}
}
const reduceMotion=window.matchMedia('(prefers-reduced-motion: reduce)').matches;
function tick(now){const dt=Math.max(0,Math.min(.05,(now-last)/1000));last=now;if(!paused&&!help){if(!reduceMotion)time+=dt;if(current){eventTime+=dt;if(eventTime>(current.kind==='round'?.6:1.05))advanceEvent();}}draw();requestAnimationFrame(tick);}renderUI();requestAnimationFrame(tick);

// Keep play disabled until real assets have loaded, including slower phone networks.
function imageReady(img){return new Promise((resolve,reject)=>{if(img.complete&&img.naturalWidth){resolve();return;}let timer=setTimeout(()=>reject(new Error('timeout')),25000);const clean=()=>{clearTimeout(timer);img.removeEventListener('load',ok);img.removeEventListener('error',bad);};const ok=()=>{clean();resolve();};const bad=()=>{clean();reject(new Error('image'));};img.addEventListener('load',ok,{once:true});img.addEventListener('error',bad,{once:true});});}
Promise.all([imageReady(background),imageReady(atlas.hero),imageReady(atlas.cast)]).then(()=>{$('begin').disabled=false;$('assetStatus').textContent='已就绪 · 手机可直接触屏游玩';}).catch(()=>{$('assetStatus').textContent='素材未能载入，请检查网络后重试。';$('retryAssets').classList.remove('hidden');});
$('retryAssets').onclick=()=>location.reload();
