import {TurnBattle} from './turn-model.js';
import {SpriteAtlas} from './sprites.js';
import {prologue,preBattle,victory,endChoice,endings} from './story.js';
const $=id=>document.getElementById(id),canvas=$('scene'),c=canvas.getContext('2d'),atlas=new SpriteAtlas();
const ultimateSheet=new Image();ultimateSheet.src='./assets/hero-ultimate.png';
const background=new Image();background.src='./assets/qingxi-pixel-v2.png';background.onerror=()=>{background.onerror=null;background.src='./assets/world.png';};
let battle=new TurnBattle(),shown=battle.snapshot(),mode='opening',storyPhase='prologue',target='guard',boost=0,time=0,last=performance.now(),paused=false,help=false,queue=[],current=null,eventTime=0,lines=[],lineIndex=0,afterDialog=()=>{},outcome='';
function renderUI(){document.body.dataset.gameMode=mode;const h=shown.hero;$('ultimateValue').textContent=`${h.ultimate} / 100`;$('ultimateBar').style.width=h.ultimate+'%';document.querySelector('.ultimate-button').classList.toggle('charged',h.ultimate>=100);for(const [id,key,max]of[['hp','hp','maxHp'],['qi','qi','maxQi']]){$(id).textContent=`${h[key]} / ${h[max]}`;$(id+'Bar').style.width=`${h[key]/h[max]*100}%`;}$('bp').textContent='●'.repeat(h.bp)+'○'.repeat(5-h.bp);$('potions').textContent=`金疮药 × ${h.potions}`;$('round').textContent=`第 ${shown.round} 回合`;$('boostCount').textContent=boost;const ready=mode==='battle'&&!current&&!queue.length&&!paused&&!help&&battle.phase==='player';$('phase').textContent=mode==='battle'?(ready?'你的回合':'招式演出中'):'剧情';document.querySelectorAll('[data-action]').forEach(b=>{b.disabled=!ready||(b.dataset.action==='ultimate'&&h.ultimate<100)||(b.dataset.action==='qi'&&h.qi<12)||(b.dataset.action==='heal'&&(!h.potions||h.hp===h.maxHp));});$('boost').disabled=!ready;for(const e of shown.enemies){$(e.id+'Intent').textContent='意图 · '+e.intent;$(e.id+'Hp').textContent=`${e.hp} / ${e.maxHp}`;$(e.id+'Shield').textContent=e.hp<=0?'已止战':e.broken>0?`破防 · 余 ${e.broken} 次停手`:`架势 ${'◆'.repeat(e.shield)} · 弱点：${e.weak==='sword'?'剑':'气'}`;const b=$(e.id+'Target');b.classList.toggle('selected',e.id===target);b.setAttribute('aria-pressed',String(e.id===target));b.disabled=!ready||e.hp<=0;}$('turnHero').classList.toggle('active',ready||current?.actor==='hero');$('turnGuard').classList.toggle('active',current?.actor==='guard');$('turnChief').classList.toggle('active',current?.actor==='chief');}
function playDialog(list,done){mode='dialog';lines=list;lineIndex=0;afterDialog=done;$('dialog').classList.remove('hidden');nextLine();renderUI();}
function nextLine(){if(lineIndex>=lines.length){$('dialog').classList.add('hidden');afterDialog();return;}const line=lines[lineIndex++];$('speaker').textContent=line.speaker;$('line').textContent=line.text;$('choices').replaceChildren();const b=document.createElement('button');b.textContent=lineIndex===lines.length?'继续 →':'下一句 →';b.onclick=()=>{if(!paused&&!help)nextLine();};$('choices').append(b);}
function start(){battle=new TurnBattle();shown=battle.snapshot();target='guard';boost=0;current=null;queue=[];outcome='';paused=false;storyPhase='prologue';$('opening').classList.add('hidden');$('end').classList.add('hidden');playDialog(prologue,()=>{storyPhase='battle';playDialog(preBattle,()=>{mode='battle';$('log').textContent='此战分胜负，不取性命。选择目标与招式。';renderUI();});});}
$('begin').onclick=start;$('restart').onclick=start;
function finishWin(){storyPhase='aftermath';playDialog(victory,()=>{mode='choice';$('dialog').classList.remove('hidden');$('speaker').textContent=endChoice.speaker;$('line').textContent=endChoice.text;$('choices').replaceChildren();for(const choice of endChoice.choices){const b=document.createElement('button');b.textContent=choice.label;b.onclick=()=>{if(paused||help)return;outcome=choice.id;playDialog(endings[choice.id],()=>{mode='end';$('endTitle').textContent=choice.id==='witness'?'灯在江上':'人过青溪';$('endText').textContent=choice.id==='witness'?'原令成为证据，旧案得以受理；第十七个孩子仍无下落。陆行舟的寻人路，才刚刚开始。':'十七个孩子平安过江，原令却化为灰烬。你与裴照同行，寻找能让亡者重见天日的证人。';$('end').classList.remove('hidden');renderUI();});};$('choices').append(b);}renderUI();});}
function act(action){if(mode!=='battle'||current||queue.length||paused||help)return;try{queue=battle.act(action,target,boost);boost=0;advanceEvent();}catch(e){$('log').textContent=e.message;}}
function advanceEvent(){current=queue.shift()||null;eventTime=0;if(!current){shown=battle.snapshot();if(shown.phase==='won'){finishWin();return;}if(shown.phase==='lost'){mode='end';$('endTitle').textContent='剑尚未稳';$('endText').textContent='裴照收刀，给你留了退路。重新尝试：用气破开他的架势，蓄势连击，把握守心与用药的时机。';$('end').classList.remove('hidden');}const alive=shown.enemies.filter(e=>e.hp>0);if(!alive.some(e=>e.id===target)&&alive.length)target=alive[0].id;renderUI();return;}if(current.kind!=='ultimate')shown=current.state;$('log').textContent=current.text;if(current.amount){$('damage').textContent=(current.kind==='heal'?'+':'−')+current.amount+ (current.breaking?' 破防':'');$('damage').style.left=current.target==='hero'?'27%':current.target==='chief'?'79%':'66%';$('damage').classList.remove('show');void $('damage').offsetWidth;$('damage').classList.add('show');}renderUI();}
document.querySelectorAll('[data-action]').forEach(b=>b.onclick=()=>act(b.dataset.action));document.querySelectorAll('[data-target]').forEach(b=>b.onclick=()=>{target=b.dataset.target;renderUI();});$('boost').onclick=()=>{boost=(boost+1)%(Math.min(3,shown.hero.bp)+1);renderUI();};
function setPause(v){paused=v;$('pauseOverlay').classList.toggle('hidden',!v);$('pause').textContent=v?'继续':'暂停';renderUI();}$('pause').onclick=()=>setPause(!paused);$('resume').onclick=()=>setPause(false);$('help').onclick=()=>{help=true;$('helpOverlay').classList.remove('hidden');renderUI();};$('closeHelp').onclick=()=>{help=false;$('helpOverlay').classList.add('hidden');renderUI();};
document.addEventListener('visibilitychange',()=>{if(document.hidden&&mode!=='opening'&&!paused)setPause(true);});
window.addEventListener('keydown',e=>{if(e.repeat)return;if(e.key==='Escape'){if(help)$('closeHelp').click();else setPause(!paused);return;}if(paused||help)return;if(mode==='dialog'&&(e.key===' '||e.key==='Enter')){e.preventDefault();nextLine();return;}if(mode!=='battle'||current||queue.length)return;if(['1','2','3','4','5'].includes(e.key)){e.preventDefault();act(['sword','qi','guard','heal','ultimate'][Number(e.key)-1]);}if(e.key.toLowerCase()==='b')$('boost').click();if(e.key.toLowerCase()==='t'){e.preventDefault();const live=shown.enemies.filter(e=>e.hp>0);target=live[(live.findIndex(e=>e.id===target)+1)%live.length].id;renderUI();}});
function draw(){c.clearRect(0,0,1440,810);c.save();if(current?.kind==='ultimate'&&!reduceMotion){const z=1+.04*Math.sin(Math.min(eventTime/3.8,1)*Math.PI);c.translate(720,405);c.scale(z,z);c.translate(-720,-405);}if(background.complete&&background.naturalWidth)c.drawImage(background,0,0,1440,810);else{c.fillStyle='#21373f';c.fillRect(0,0,1440,810);}const vignette=c.createRadialGradient(730,390,180,720,400,840);vignette.addColorStop(0,'#08162400');vignette.addColorStop(1,'#030d1baa');c.fillStyle=vignette;c.fillRect(0,0,1440,810);
 const attack=['hit','counter'].includes(current?.kind)&&eventTime<.7,from=current?.actor,to=current?.target,lunge=Math.sin(Math.min(1,eventTime/.7)*Math.PI)*55;
 const hero={x:355+(attack&&from==='hero'?lunge:0),y:590,facing:0,actionTime:attack&&from==='hero'?Math.max(.001,.7-eventTime):0,actionDuration:.7,action:'attack'};
 if(current?.kind==='guard'&&eventTime<.9){c.strokeStyle='#a8dbe580';c.lineWidth=3;c.beginPath();c.ellipse(hero.x,hero.y-50,60,100,0,0,Math.PI*2);c.stroke();}
 if(current?.kind!=='ultimate')atlas.draw(c,'hero',hero,time,{previewScale:1.75});
 if(storyPhase==='prologue'||storyPhase==='aftermath')atlas.draw(c,'npc',{x:890,y:580},time,{previewScale:1.7});
 else for(const e of shown.enemies){if(e.hp<=0)continue;const p={x:(e.id==='guard'?1000:1150)-(attack&&from===e.id?lunge:0),y:e.id==='guard'?550:590,facing:Math.PI,attackAnim:attack&&from===e.id?.3:0};if(e.id===target&&mode==='battle'){c.strokeStyle='#edce83';c.lineWidth=2;c.beginPath();c.ellipse(p.x,p.y+20,42,12,0,0,Math.PI*2);c.stroke();}atlas.draw(c,e.id==='chief'?'boss':'bandit',p,time,{previewScale:e.id==='chief'?1.7:1.6});c.font='16px serif';c.textAlign='center';c.fillStyle=e.broken?'#ffd29a':'#e3d5b0';c.shadowColor='#000';c.shadowBlur=5;c.fillText(e.broken?'破 防':`${'◆'.repeat(e.shield)}  ${e.weak==='sword'?'剑':'气'}`,p.x,p.y-(e.id==='chief'?185:150));c.shadowBlur=0;}
 if(attack&&current?.actor==='hero'&&eventTime>.1&&eventTime<.65){const px=current.target==='chief'?1150:1000,travel=Math.min(1,(eventTime-.1)/.3);c.save();c.globalCompositeOperation='lighter';c.strokeStyle=current.action==='qi'?'#48e9d9':'#f3d990';c.shadowColor=c.strokeStyle;c.shadowBlur=14;c.lineWidth=current.action==='qi'?7:3;for(let k=0;k<5;k++){c.globalAlpha=(1-k/6)*.6;c.beginPath();c.moveTo(400,520+k*5);c.quadraticCurveTo(680,410+k*12,400+(px-400)*travel,510+k*5);c.stroke();}for(let k=0;k<18;k++){const a=k*2.4,r=Math.max(0,eventTime-.3)*260;c.fillStyle=k%2?'#eaffd8':'#55d9d0';c.fillRect(px+Math.cos(a)*r,520+Math.sin(a)*r,4,4);}c.restore();}
 if(attack&&eventTime>.18&&eventTime<.55){const px=to==='hero'?hero.x:to==='guard'?1000:1150;c.save();c.translate(px,530);c.strokeStyle=current.breaking?'#ffe5a2':'#d4f6e8';c.lineWidth=6;c.shadowBlur=20;c.shadowColor=c.strokeStyle;c.beginPath();c.arc(0,0,85,-1.2+eventTime*2,1.1+eventTime*2);c.stroke();c.restore();const light=c.createRadialGradient(px,540,0,px,540,230);light.addColorStop(0,'#dfefbc35');light.addColorStop(1,'#dfefbc00');c.fillStyle=light;c.fillRect(px-230,310,460,460);}
 c.restore();if(current?.kind==='ultimate')drawUltimate(eventTime);
 c.strokeStyle='#b2d4de28';c.lineWidth=1;for(let i=0;i<60;i++){const x=(i*197+time*30)%1440,y=(i*131+time*240)%810;c.beginPath();c.moveTo(x,y);c.lineTo(x-3,y+12);c.stroke();}
}
const reduceMotion=window.matchMedia('(prefers-reduced-motion: reduce)').matches;
function tick(now){const elapsed=Math.max(0,(now-last)/1000),dt=Math.min(.05,elapsed);last=now;if(!paused&&!help){if(!reduceMotion)time+=dt;if(current){eventTime+=Math.min(1,elapsed);if(current.kind==='ultimate'&&eventTime>=2.25&&!current.presented){current.presented=true;shown=current.state;renderUI();}if(eventTime>(current.kind==='ultimate'?3.8:current.kind==='round'?.6:1.05))advanceEvent();}}draw();requestAnimationFrame(tick);}renderUI();requestAnimationFrame(tick);

// Keep play disabled until real assets have loaded, including slower phone networks.
function imageReady(img){return new Promise((resolve,reject)=>{if(img.complete&&img.naturalWidth){resolve();return;}let timer=setTimeout(()=>reject(new Error('timeout')),25000);const clean=()=>{clearTimeout(timer);img.removeEventListener('load',ok);img.removeEventListener('error',bad);};const ok=()=>{clean();resolve();};const bad=()=>{clean();reject(new Error('image'));};img.addEventListener('load',ok,{once:true});img.addEventListener('error',bad,{once:true});});}
Promise.all([imageReady(background),imageReady(ultimateSheet),imageReady(atlas.hero),imageReady(atlas.cast)]).then(()=>{$('begin').disabled=false;$('assetStatus').textContent='已就绪 · 手机可直接触屏游玩';}).catch(()=>{$('assetStatus').textContent='素材未能载入，请检查网络后重试。';$('retryAssets').classList.remove('hidden');});
$('retryAssets').onclick=()=>location.reload();

// Dedicated six-keyframe choreography. A dark theatrical cutaway lets the
// generated black-backed frames composite naturally without a false alpha mask.
function drawUltimate(t){
 const fade=Math.min(1,t/.25,(3.8-t)/.4),phase=t<.65?0:t<1.25?1:t<1.7?2:t<2.25?3:t<2.8?4:5;
 c.save();c.fillStyle=`rgba(2,12,23,${.86*Math.max(0,fade)})`;c.fillRect(0,0,1440,810);
 const x=reduceMotion?720:t<1.25?480:t<2.25?480+(t-1.25)*380:900;
 c.globalAlpha=Math.max(0,fade);c.strokeStyle='#53cfc666';
 for(let i=0;i<32;i++){const y=170+i*17,offset=reduceMotion?0:(t*600+i*97)%600;c.lineWidth=i%4===0?3:1;c.beginPath();c.moveTo(offset-400,y);c.lineTo(offset+240,y-32);c.stroke();}
 const aura=c.createRadialGradient(x,480,5,x,480,360);aura.addColorStop(0,'#65eddb55');aura.addColorStop(1,'#07131d00');c.fillStyle=aura;c.fillRect(x-360,120,720,720);
 c.imageSmoothingEnabled=false;c.globalCompositeOperation='screen';
 const cellW=ultimateSheet.naturalWidth/3,cellH=ultimateSheet.naturalHeight/2;
 const size=reduceMotion?410:phase===0?480:440;
 if(ultimateSheet.naturalWidth)c.drawImage(ultimateSheet,(phase%3)*cellW,Math.floor(phase/3)*cellH,cellW,cellH,x-size/2,610-size,size,size);
 c.globalCompositeOperation='source-over';
 if(t>1.7&&t<3.15){const progress=Math.min(1,(t-1.7)/.55);c.save();c.globalAlpha=fade*Math.min(1,(3.15-t)*2);c.strokeStyle='#caffef';c.shadowColor='#52e7d2';c.shadowBlur=26;c.lineWidth=reduceMotion?5:10;
 c.beginPath();c.moveTo(480,650);c.bezierCurveTo(690,300,1120,540,1320,210+180*(1-progress));c.stroke();c.lineWidth=3;c.strokeStyle='#d9b974';c.beginPath();c.moveTo(490,300);c.lineTo(1300,580);c.stroke();
 for(let i=0;i<34;i++){const a=i*2.4,r=(t-1.7)*(90+i*7);c.fillStyle=i%3?'#8cf1dd':'#ffe6a0';c.fillRect(1070+Math.cos(a)*r,430+Math.sin(a)*r*.6,4+i%4,4+i%4);}c.restore();}
 c.fillStyle='#041019';c.fillRect(0,0,1440,100);c.fillRect(0,720,1440,90);c.textAlign='left';c.fillStyle='#8be4d1';c.font='18px serif';c.fillText('陆 行 舟    /    剑 意 解 放',80,153);c.fillStyle='#f6e8bf';c.font='bold 54px serif';c.fillText('一剑断江',80,218);c.font='18px serif';c.fillStyle='#c3d4cf';c.fillText(t<2.25?'雨停一瞬，剑过两岸。':'剑落 · 江潮无声',83,254);
 if(t>=2.25){c.textAlign='center';for(const hit of current.targets){const px=hit.id==='chief'?1170:960;c.fillStyle='#fff0ad';c.font='bold 46px serif';c.fillText('−'+hit.amount,px,360);c.font='21px serif';c.fillText(hit.breaking?'架势崩解':'奥义命中',px,395);}}
 c.restore();
}
